### ISSUE TITLE
Quest: Escape from Coilskar Cistern (10451)

### ISSUE THREAD

**Issue by mikedej** [Progressive335/Progressive335#1003]
It's an escort quest in Shadowmoon valley, Coilskar Cistern.

At some point the npc walks straight through a wall, then going out of your range and dissapairing entierly.

Wowhead link: https://www.wowhead.com/quest=10451/escape-from-coilskar-cistern

Youtube link: https://www.youtube.com/watch?v=i_CpElkm5q4

Could only find a link of a higher wow patch. But you'll get the idea.

Also the cavern seems rather empty. I think there should be more npc's around, not sure though.

**Comment by Wice-Prog** [comment]
Hi Mikedej,

Can you please provide a screenshot or video of what exactly is happening to you? When I tested this quest on my character it works without any issues.

**Comment by mikedej** [comment]
I did this quest again, this time I kept my distance from the quest npc. The adds that spawn are not attacking the quest npc, rather they despawn if you dont aggro them after 3-4 seconds. This way I was able to complete this quest.
