### ISSUE TITLE
Divine Purpose Talent

### ISSUE THREAD

**Issue by cts17** [Progressive335/Progressive335#1010]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[31872] Spell
[] NPC
[] Quest

**Description of the bug:**
Hand of Freedom is not removing Stun effects.

**Current behaviour:**
Hand of Freedom does not remove stun effects from your target when talented into Divine Purpose

**Steps to reproduce the problem:**
Get Divine Purpose talent
Use hand of Freedom on a stunned ally (like Lady Vashj's Static Charge)

**How it should work:**
Hand of Freedom should remove stun effects from your target when talented into Divine Purpose

**Any other documentation that could be helpful:**
N.B. Hand of Freedom shouldn't remove stun on yourself of course, since you can't cast spells when you yourself are stunned

**Comment by silverech0** [comment]
some bosses spells are excluded from those kind of mechanics.
it's similar to the idea that some people have that you can cloak of shadow every spell bosses do, which is obviously wrong.
is better to investigate lady vashj spell because i suspect you cannot remove the effect that way.

**Comment by silverech0** [comment]
also note that most of those effects apply mostly to PVP and not to all PVE situations.
