### ISSUE TITLE
[Warlock] [Spell] Searing Pain threatgenerating is low again

### ISSUE THREAD

**Issue by Miranai** [Progressive335/Progressive335#1017]
**ID of the Spell/NPC/Quest:**
Searing Pain - Warlock Spell
https://wotlk.evowow.com/?spell=17922#modified-by

**Description of the bug:**
Is now reverted back as it was before the change. Probably after the crash that caused by A'lar on the 20.07.2020. 

**Current behaviour:**
Doesn't do enough threat, is basically same as before the changes. 

**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
it's doing threat, got 800 TPS on a creature with searing pain.
