### ISSUE TITLE
[Loot] Master Loot

### ISSUE THREAD

**Issue by pwtaka** [Progressive335/Progressive335#1024]
Since some weeks (months?) if you use Master Loot in a Raid or Group, the only one that can loot items below the rarity threshhold is the Master Looter.
But as stated in the in-game tooltip, items below the threshold should be distributed by the round robin rules.

The main problem with this bug is, that you can't use skinning/herbalsim/mining in raids if you aren't the loot master because you can't loot the gathering materials.

**Comment by Progressive335** [comment]
duplicate...
https://github.com/Progressive335/Progressive335/issues/999
