### ISSUE TITLE
[Quest]The Vials of Eternity

### ISSUE THREAD

**Issue by Psychh** [Progressive335/Progressive335#1025]
[Quest]The Vials of Eternity
https://wow.gamepedia.com/The_Vials_of_Eternity
https://wotlk.evowow.com/?quest=13432
not available
should be

edit: should had been available before hyjal patch hit.

**Comment by Progressive335** [comment]
![image](https://user-images.githubusercontent.com/44980177/89723678-67339180-d9f1-11ea-90b7-75619ff82a25.png)
it's available before, there is no limitation.
