### ISSUE TITLE
[Shaman] Windfury Weapon missing ICD

### ISSUE THREAD

**Issue by SylVanish** [Progressive335/Progressive335#1038]
At the moment it seems that is better to use [Windfury Weapon](https://wotlkdb.com/?spell=16362) on both weapons because there is no ICD which means it will proc twice at the same time. Making shamans doing absurd DPS in Classic phase.

The only thing I found are some comments saying it should be 3s ICD and https://wotlkdb.com/?spell=32911

**Comment by Progressive335** [comment]
this was due .cheat cooldown. closing.
