### ISSUE TITLE
Blade of Eternal Darkness not working

### ISSUE THREAD

**Issue by spaccacerque** [Progressive335/Progressive335#1052]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**17780**

__x17780__

[] Quest
[] NPC
[] Quest

does not proc

**tested on dummy for 1 min... no procs**

**tested on dummy for 1 min... no procs**

**I asked some people about this a few weeks ago and there's a few things to it:
-it's around 3 to 5 procs per minute
-it can proc on the application of dots like shadow word: pain
-it can proc multiple times in a row (meaning no internal cd)
-it can proc multiple times at the same time (when using blizzard or hellfire)**

**https://www.reddit.com/r/lightshope/comments/9c11i5/blade_of_eternal_darkness_ppm/**

**Comment by Progressive335** [comment]
the link is not valid as evidence.
