### ISSUE TITLE
[Progression] High-powered Flashlight

### ISSUE THREAD

**Issue by awatenn** [Progressive335/Progressive335#1060]
This engineering pattern was added in Ulduar patch and is an extremely powerful trinket in Vanilla content. Remove?
https://wotlk.evowow.com/?spell=63750
https://wotlk.evowow.com/?item=45631

**Comment by spaccacerque** [comment]
i oppose to this. give so much help to dps that need hit ^_^ is an amazing trinket to have.
Need to find someone with engineering and its not so easy on vanilla content ^_^

**Comment by Progressive335** [comment]
> i oppose to this. give so much help to dps that need hit ^_^ is an amazing trinket to have. Need to find someone with engineering and its not so easy on vanilla content ^_^

if you think you want op things, think again, op things ruin gameplay
