### ISSUE TITLE
Pet can't properly cast acid spit to 2 stacks spell id 55752

### ISSUE THREAD

**Issue by spaccacerque** [Progressive335/Progressive335#1061]
**Acid Spit stacking 1 and not 2  **
 
**55752**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**debuff don't stack automatically, pet just refresh the 1 stack when he expires, instead of stacking to 2 properly**

**debuff don't stack automatically, pet just refresh the 1 stack when he expires**

**Steps to reproduce the problem: just use on a dummy everyewhere **

**How it should work: should stack to 2 till pet has focus ( not an issue with bm hunters ) **

**could do a video.... here the link    https://youtu.be/TYuwW87dEAQ   **

**Comment by Progressive335** [comment]
it's working for me.
