### ISSUE TITLE
[Item] Black Lotus

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#165]
Herbalism: Black Lotus
Issue: Spawning incorrectly
Current Behavior: Zones that spawn this herb are spawning it on EVERY node in the zone on their own 60 minute timers.
Proper Behavior: All nodes of Black Lotus in zones that spawn are connected and when black lotus spawns it should spawn on only ONE node every 60 minutes in each respective zone that spawns Black Lotus.

**Comment by Progressive335** [comment]
Black lotus spawning 1 per zone (missing script to randomize spawn locations)
