### ISSUE TITLE
[Event] Scourge Invasion

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#169]
Script scourge invasion for the opening of naxxramas
https://wow.gamepedia.com/Scourge_Invasion

note: maps and locations of spawns

also, we need to set necrotic runes back to be specific on this event or change currency for this.

**Comment by Progressive335** [comment]
https://www.youtube.com/watch?v=C65pQRSZh6A 
useful video

**Comment by Progressive335** [comment]
1 more:
https://www.youtube.com/watch?v=YTTLp3jqMBY

**Comment by Progressive335** [comment]
https://www.youtube.com/watch?v=vdlirDXY7ec

**Comment by Progressive335** [comment]
https://wowwiki.fandom.com/wiki/Plague_Zombie

**Comment by Progressive335** [comment]
https://wowwiki.fandom.com/wiki/Zombie_Infestation

**Comment by Progressive335** [comment]
https://www.wowhead.com/forums&topic=48283

**Comment by Progressive335** [comment]
https://wowwiki.fandom.com/wiki/A_Torn_Letter_(starter)

**Comment by Progressive335** [comment]
https://wowwiki.fandom.com/wiki/Plague_Zombie

**Comment by Progressive335** [comment]
https://wowwiki.fandom.com/wiki/Argent_Emissary

**Comment by Progressive335** [comment]
https://github.com/Progressive335/Progressive335/issues/599 followup
