### ISSUE TITLE
[Spells] Baby Spice

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#170]
Can be used on bosses

**Comment by Progressive335** [comment]
it seems to be valid according to wowhead.

https://www.wowhead.com/item=44228/baby-spice#comments

on patch 3.0.3

_Apparently when you use this on Thaddius in Naxx it makes his hitbox so small that the melee with different polarities can no longer get close enough to attack him without crossing the charges and doing 2k dps per melee.

Have 5 melee classes in your 25 man?

Use this and watch the melee helplessly try to get into range doing a grand total of 250,000 damage per second to the raid.

You either have melee that stands out of range and does no damage or melee that kills everyone in the raid in 6 seconds._
