### ISSUE TITLE
[Spells] Viper aspect + volley

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#175]
Shouldnt regenerate mana

**Comment by Progressive335** [comment]
> Aspect of the Viper causes each ranged attack (including the initial application of Serpent Sting, all three charges of Explosive Shot, all three missiles of Multi-Shot, but not including the ticks of Serpent Sting or the damage of Volley) to generate a percentage of the Hunter's maximum mana.
> For more information go to: http://wowwiki.wikia.com/wiki/Aspect_of_the_Viper
