### ISSUE TITLE
[Graveyards] Eastern Plaguelands

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#188]
If you die anywhere in the "The Noxious Galde" north of lights hope chapel in Easter Plague Lands, it will put your ghost near a deatha gnle that sits on top of Ebonhold and theres no way to jump off and run back to your corpse so you currently just have to eat a repair bill to get down.

**Comment by Progressive335** [comment]
Cannot reproduce, i'm always dead at Death's Breach.
