### ISSUE TITLE
[Quest] Rites of the Earthmother

### ISSUE THREAD

**Issue by Chumanoyasha** [Progressive335/Progressive335#190]
**https://classicdb.ch/?quest=776**

[776] Quest
[3058] NPC

**Description of the bug:
Mob missing or wrong path or respawn timer is way too big.**

**Current behaviour:
Have been trying to find it with my friend by using classic route for 20 mins. Also tried to wait for it in the respawn place (49.18 coordinates on the map)**

**Steps to reproduce the problem:
Go and try to find it. Because we didn't find him even after 30 mins.**

**How it should work:
Most reputated comment on wowhead says : "spawns at 49,19 and is on a one minute spawn timer" and another one says that "He walks clockwise, really hard to find kodo."**

**Any other documentation that could be helpful:**

**Comment by Jparoche** [comment]
Not an issue, Tested on PTR
