### ISSUE TITLE
Dark Strand Cultists Imps

### ISSUE THREAD

**Issue by chescatt** [Progressive335/Progressive335#192]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[X] NPC 8279
[] Quest 

**Description of the bug:** The imps the npcs summon, Dark Strand Cultists in The Ruins of Ordil'Aran have 1k health at level 19 triple the health of other mobs at that level. I've heard the shamans fire  totem quest has the issue with its imps also.

**Current behaviour:** Too much health

**Steps to reproduce the problem:** Go find mob check hp

**How it should work:** Probably shouldn't have 1.1k health

**Any other documentation that could be helpful:**

**Comment by Jparoche** [comment]
fixed on PTR, needs pull to main realm
