### ISSUE TITLE
Freewind Post Lifts are glitchey

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#193]
**Description of the bug:**
The Freewind Post Lifts in Thousand Needles have something wrong with them.  It appears like there's multiple instances of them running at the same time, which are all slightly off-sync.

**Any other documentation that could be helpful:**
https://i.imgur.com/4S7JY73.png  Notice how the bottom is graphically accordian'd?  It also does a weird hitbox where you are partially in the "floor" of the lift when going down.

**Comment by Jparoche** [comment]
Validated on PTR. Not an issue.

**Comment by LezChap** [comment]
It's not gamebreaking, but it's definitely still doing something weird...taken just a few minutes ago: https://i.imgur.com/6eJDkMb.png
