### ISSUE TITLE
Faerie Fire (Feral) not doing damage

### ISSUE THREAD

**Issue by ovifla25** [Progressive335/Progressive335#194]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**  --> 16857

__Place an X between the brackets to specify the ID__

[x] Spell
[] NPC
[] Quest

**Description of the bug:**
The spell does not doea damage, only applies debuff effect on the target.

**Comment by Chumanoyasha** [comment]
Can confirm, my druid in bear form doesn't do damage with Faerie Fire as well.
