### ISSUE TITLE
Server crash rollbacks --> quest issue

### ISSUE THREAD

**Issue by ovifla25** [Progressive335/Progressive335#195]
when server crashes rollbacks occur.

If you turn in a quest and afterwards there is a server crash, when you log back in the quest rearwards are musing  and the quest is no longer in the player's quest log.

Please  make the quests rollback as well and re-appear in quest log.
A website feature to auto-complete a quest in order to not break chain-quests in game would be nice.

**Comment by silverech0** [comment]
this should be a ticket issue, not a bug report since these rollbacks are related to crashes.

**Comment by silverech0** [comment]
should be solved now anyway
