### ISSUE TITLE
Aggro radius of mobs is too big (-15% to 25% would be ok)

### ISSUE THREAD

**Issue by ovifla25** [Progressive335/Progressive335#197]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**

**Current behaviour:**

**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**

**Comment by Chumanoyasha** [comment]
Confirm, annoying range aggro distance

**Comment by Progressive335** [comment]
it has been already lowered.
