### ISSUE TITLE
[Paladin] Paladins retain Greater Blessing of Sanctuary

### ISSUE THREAD

**Issue by jQuery69** [Progressive335/Progressive335#2]
ID of the Spell/NPC:
25899

Description of the bug:
Paladins retain Greater Blessing of Sanctuary even if they switch out of prot

Current behaviour:
Paladins retain Greater Blessing of Sanctuary even if they switch out of prot

Steps to reproduce the problem:

How it should work:
Paladins should not retain Greater Blessing of Sanctuary even if they switch out of prot

Any other documentation that could be helpful:

**Comment by silverech0** [comment]
Related to https://github.com/Progressive335/Progressive335/issues/62
