### ISSUE TITLE
[Spell] Drain Soul, Player spell.

### ISSUE THREAD

**Issue by Jparoche** [Progressive335/Progressive335#202]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
1120 - Rank 1
8288 - Rank 2
8289 - Rank 3
11675 - Rank 4
27217 - Rank 5
47855 - Rank 6

__Place an X between the brackets to specify the ID__

[X] Spell
[] NPC
[] Quest

**Description of the bug:**
Spell is mean't to do x4 damage when target is below 25%, Currently doing same damage as if target is above 25% health.

[Drain Soul should have the effect "If the target is at or below 25% health, Drain Soul causes four times normal damage," but I do not observe this in testing (for level 1, the number stays 11 for the duration). This includes when I attempt to recast it after the mob is already below 25% health.] 

**Current behaviour:**

**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**
https://wotlk.evowow.com/?spell=1120

**Comment by Progressive335** [comment]
The spells seems to be working correctly , like the description says.
