### ISSUE TITLE
[Spell] [Mage] Frost Nova CC breaking too early

### ISSUE THREAD

**Issue by idohealz** [Progressive335/Progressive335#203]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
122 (Frost nova)
All ranks

__Place an X between the brackets to specify the ID__

[X] Spell
[] NPC
[] Quest

**Description of the bug:**
When you cast frost nova, sometimes a mob will randomly break out of it.

**How it should work:**
Some spells, such as fear and sheep, have a random chance to break during its duration.
Frost Nova is currently functioning this way, but it should not be acting this way. Frost nova should only break, on damage or after the timed duration (8s)

**Comment by Chumanoyasha** [comment]
Not sure about other CCs like fear and sheep, but can confirm the frost nova bug.
P.s. I made bug report about frost nova little earilier, you can watch captured video of this bug there.
Link : https://github.com/Progressive335/Progressive335/issues/199

**Comment by Tatoepaladin** [comment]
This is a normal thing back since vanilla where resistance kicks in. If you have enough resistance you can resist 25%/50%/100% of the spell dmg and or duration. So when some break early you have to becareful of it.

**Comment by Progressive335** [comment]
duplicate
https://github.com/Progressive335/Progressive335/issues/199
