### ISSUE TITLE
The Last Element (Quest text bug)

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#204]
Trying to turn in The Last Element (ID 7201) quest: https://i.imgur.com/Yzx5eKM.png looks like it's pulling up a response for an Outland quest?

Turning it in appears to give the correct reward.

**Comment by Progressive335** [comment]
this is a visual bug only. it's related to quest scale progression.

**Comment by LezChap** [comment]
This was the first time I saw the bug.  Since posting this, I've seen it all over, and it's true that it's only visual.  Luckily it doesn't seem to impact any quest where you have to choose your reward.
