### ISSUE TITLE
Hunter Pets losing HP on dismount

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#207]
**Description of the bug:**
When you dismount with a hunter pet, it starts at around 70-80% HP even though you mounted with a pet at 100%.  I believe the pet is given their full health at base Stamina, then the bonus Stamina from gear is applied, increasing maxHP but not currentHP.

**Steps to reproduce the problem:**
Have a hunter with a pet.  Wear Stam gear.  Pet is at 100% HP.  Mount.  Dismount.  Pet is at reduced HP Percentage.  (May also apply to calling dismissed pets).

**How it should work:**
If you mount with a pet at 100% health, it should be at 100% when you dismount.

**Comment by WhiteGazelle** [comment]
also when summoning hit

**Comment by flumby** [comment]
https://github.com/TrinityCore/TrinityCore/issues/873
