### ISSUE TITLE
Wrong items received when Skinning in Sillithus

### ISSUE THREAD

**Issue by Freemind0** [Progressive335/Progressive335#210]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Stonelash Scorpid and Dredge Striker (possibly more mobs)

__Place an X between the brackets to specify the ID__

[] Quest
[x] NPC
[] Quest

**Description of the bug:**
Dredge Striker and Stonelash Scorpid requires atm around 270-280 skinning. They are giving Light leather & Ruined Leather Scraps.
**Current behaviour:**
Gives Ruined leather scrap + Light leather when skinning. 
**Steps to reproduce the problem:**
Skin them. 
**How it should work:**
They should give variants of Rugged/Thick leather. And Scorpids should give, which they do sometimes, Heavy Scorpid Scale.  
**Any other documentation that could be helpful:**
Scorpids sometimes give their correct item which is "Heavy Scorpid Scale", but other than that both Dredge and Scorpids give ruined leather scrap + Light leather. Which should not be in the loot table for skinning them.

**Comment by silverech0** [comment]
https://wotlk.evowow.com/?npc=11740#skinning

https://wotlk.evowow.com/?npc=11735#skinning

seems to be working as intended, reopen the ticket if you find any more evidence pls. thank you.
