### ISSUE TITLE
[SPELL] Warrior Recklessness

### ISSUE THREAD

**Issue by Jparoche** [Progressive335/Progressive335#211]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
1719
__Place an X between the brackets to specify the ID__

[X] Spell
[] NPC
[] Quest

**Description of the bug:**
Recklessness doesn't consume its stacks on ability usage
.
**Current behaviour:**
Recklessness for warriors doesn't consume stacks once u use abilities, meaning you have 100% crit for everything for 12 seconds.
**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**

**Comment by silverech0** [comment]
https://github.com/Progressive335/Progressive335/issues/161
duplicate
