### ISSUE TITLE
Faerie Fire and Shadowmeld

### ISSUE THREAD

**Issue by Singledream32** [Progressive335/Progressive335#214]
**6950 id of the Spell (Faerie Fire):**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest
[X] Spell

**Description of the bug:**

**Current behaviour: While getting the Faerie Fire debuff casted by Rascal Sprite
(id of NPC: 2002), I could use Shadowmeld. **

**Steps to reproduce the problem: Wait for the Rascal Sprite to cast Faerie Fire on you and then Meld.**

**How it should work: You can not turn invisible while being affected by Faerie Fire.**

**Any other documentation that could be helpful:**

**Comment by Tatoepaladin** [comment]
Whether you have the debuff or not you can use your spell against a mob. It doesnt disable your spell just because you have a debuff that prevents you from not being able to stealth. It means if you do stealth you can still be seen.

**Comment by Progressive335** [comment]
as @Tatoepaladin this is not an issue.
