### ISSUE TITLE
Thorns

### ISSUE THREAD

**Issue by Singledream32** [Progressive335/Progressive335#215]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:*467*

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest
[X] Spell

**Description of the bug: While I have Thorns buff on my toon, a mob that I attack would chase me for miles without giving up on the target.**

**Current behaviour:*Hostile NPCs would chase you all around until you kill them if you have Thorns and you aggro them.*

**Steps to reproduce the problem:*Buff yourself with Thorns and attack a melee NPC then run around as much as you want, the target won't leave you alone until you die.*

**How it should work:*If you do not attack the NPC, it should leave you alone even if you have Thorns on you. *

**Any other documentation that could be helpful:**

**Comment by Tatoepaladin** [comment]
Its not because of thorns specifically. If you keep attacking a mob its reset range is actually a timer from last time it took dmg. This is a kiting mechanic possible to kite world bosses to major cities.
