### ISSUE TITLE
[ Mage ] [ Spell ] Frost Nova  important bug . 

### ISSUE THREAD

**Issue by NubHashshin** [Progressive335/Progressive335#216]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**31250 Frost Nova 

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:** so when I want to aoe, and I try to frost nova some mobs (for example from like 10 mobs 2 of them break free) which affects lvling and farming by a lot but not 100% sure if it works also on playres.

**Current behaviour:** 2/10 mobs break free when they should be rooted

**Steps to reproduce the problem:** pull mobs and press frost nova

**How it should work:** they should not break free and get stunned for x amount. 

**Any other documentation that could be helpful:** N/A

**Comment by silverech0** [comment]
duplicate
https://github.com/Progressive335/Progressive335/issues/203
