### ISSUE TITLE
PvE Issues

### ISSUE THREAD

**Issue by Paradoxlol** [Progressive335/Progressive335#220]
Blackrock Depths

1. The dwarf room before Magmus - DWARF DO NOT RESPAWN when killed. 
2. You can light only 1 of the braziers to unlock 1 door making the process easier.

https://www.youtube.com/watch?v=H4D0WOS-hYY  1:18:27 (you can see the dwarfs spawning again) 

Wait few more mins to check the opening of the gates.

**Comment by Progressive335** [comment]
fixed
