### ISSUE TITLE
PvE Issues

### ISSUE THREAD

**Issue by Paradoxlol** [Progressive335/Progressive335#221]
Upper Blackrock Spire

1. PYROGUARD EMBERSEER

Boss takes too long to spawn (roughly 1 minute)
https://www.youtube.com/watch?v=awPyUAF2yU8 
20-25 seconds retail video

Also, it takes more than 3 people to activate. --->  https://wowwiki.fandom.com/wiki/Pyroguard_Emberseer

1.1 Boss doesn't DO FIRE NOVA  https://classicdb.ch/?npc=9816

**Comment by Progressive335** [comment]
from the link u sent it appears that he does fire nova
