### ISSUE TITLE
[Cave Mushrooms] Missing reward icon

### ISSUE THREAD

**Issue by noxaylox** [Progressive335/Progressive335#224]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
[Cave Mushrooms] https://wotlk.evowow.com/?quest=947

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[x] Quest

**Description of the bug:**
Quest is in Darkshore and the NPC is Barithras Moonshade https://wotlk.evowow.com/?npc=3583
Missing icon is shown for quest reward. Only the display is incorrect.  When you turn in the quest you get the correct rewards.

**Current behaviour:**
When you turn in the quest it reward offered is a ?5000 icon labeled Deprecated Nightmare Summoning (Mount)

**Steps to reproduce the problem:**
Complete the quest and turn in for the reward

**How it should work:**
The offered rewards should be 
Gustweald Cloak https://wotlk.evowow.com/?item=5610
Red-speckled Mushroom X 10 https://wotlk.evowow.com/?item=4605

**Any other documentation that could be helpful:**

Screenshot: https://i.imgur.com/kgleVaI.png

**Comment by Progressive335** [comment]
visual bug
