### ISSUE TITLE
[ITEM] BlackSmith Patterns missing spells

### ISSUE THREAD

**Issue by Jparoche** [Progressive335/Progressive335#227]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
7988 - [Plans: Ornate Mithril Boots] 
7987 - [Plans: Ornate Mithril Helm] 
7986 - [Plans: Ornate Mithril Breastplate] 

Patterns do not have the spells attached to them:
Spell IDs:
9979 - [Ornate Mithril Boots, rank 1 enUS]
9980 - [Ornate Mithril Helm, rank 1 enUS]
9972 - [Ornate Mithril Breastplate, rank 1 enUS]

__Place an X between the brackets to specify the ID__

[X] ITEM
[] NPC
[] Quest

**Description of the bug:**

**Current behaviour:**

**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
are u sure this wasn't an occasional bug? there was a problem with mats yesterday making some recipes broken.

**Comment by Jparoche** [comment]
Fixed on PTR
