### ISSUE TITLE
[ITEM] 18357 - [Codex of Defense] 

### ISSUE THREAD

**Issue by Jparoche** [Progressive335/Progressive335#229]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
18357 - [Codex of Defense] 

__Place an X between the brackets to specify the ID__

[X] ITEM
[] NPC
[] Quest

**Description of the bug:**
18357 - [Codex of Defense] 

Item is unable for DK's

https://cdn.discordapp.com/attachments/632696457224519700/632696571028307978/WoWScrnShot_101219_144804.jpg

**Comment by Progressive335** [comment]
how is unable? in the screenshot it says available.

**Comment by Jparoche** [comment]
fixed on PTR, needs pull to main realm
