### ISSUE TITLE
gordunni warlock (in feralas) just spams shrink

### ISSUE THREAD

**Issue by seph187** [Progressive335/Progressive335#233]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:** 

__Place an X between the brackets to specify the ID__

[] Quest
[X] NPC  5240 (per wowhead)
[] Quest

**Description of the bug:** Mob just spam casts Shrink.

**Current behaviour:** See above.

**Steps to reproduce the problem:** Engage in combat.

**How it should work:** Mob should actually attack. Melee. Not sure what else it does, but it's completely ineffective and 0 threat as is.

**Any other documentation that could be helpful:** Gordunni Warlock in Ferelas, at Ruins of Isildien. coords: 58.31, 66.49

**Comment by Jparoche** [comment]
Tested on PTR - Not an issue.

**Comment by seph187** [comment]
okay. then your PTR clearly doesn't completely and accurately reflect the live world. i've attached a youtube video taken this evening (USA time). if this issue is a symptom of some other bug that has already been resolved in a candidate build or something, please do let me know.

https://youtu.be/sNkRD0Nm_zk 

have a look. it happens as i described.

**Comment by Progressive335** [comment]
@seph187 PTR is the same db as main.

**Comment by seph187** [comment]
Did you view the video? Can you get a GM to come out and see the mob? It’s just casting Shrink over and over. If you move out of cast range it just stands there. If you move into melee, it just casts. If you interrupt it, it melees you until it can cast again, and then it resumes casting Shrink.

 

I’ve shown numerous friends. It’s 100% reproducible. If you don’t think the mob just spamming Shrink is a problem, then go ahead and close out the ticket. I think it is, though.

**Comment by seph187** [comment]
Nevermind – it’s working today. That’s weird. Was a build pushed out?

 

Go ahead and close, I guess.

 

From: seph187@gmail.com <seph187@gmail.com> 
Sent: Monday, October 14, 2019 5:27 PM
To: 'Progressive335/Progressive335' <reply@reply.github.com>
Subject: RE: [Progressive335/Progressive335] gordunni warlock (in feralas) just spams shrink (#233)

 

Did you view the video? Can you get a GM to come out and see the mob? It’s just casting Shrink over and over. If you move out of cast range it just stands there. If you move into melee, it just casts. If you interrupt it, it melees you until it can cast again, and then it resumes casting Shrink.

 

I’ve shown numerous friends. It’s 100% reproducible. If you don’t think the mob just spamming Shrink is a problem, then go ahead and close out the ticket. I think it is, though.
