### ISSUE TITLE
primal fury not working (+others,(feral talent))

### ISSUE THREAD

**Issue by oldspices** [Progressive335/Progressive335#234]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
i think its https://www.wowhead.com/spell=16953
__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
its not working in either cat or bear
**Current behaviour:**
its not working in either cat or bear
**Steps to reproduce the problem:**
spec into it and try
**How it should work:**
it should gain cp/rage on crits
**Any other documentation that could be helpful:**
I also heard primal gore/beserk dont work

**Comment by oldspices** [comment]
i guess you guys fixed it on last update? Idk about other items not high enough level.

**Comment by silverech0** [comment]
@oldspices reply to this if you feel is bugged indeed, i will close the issue for now since you say it's "fixed", because we haven't touched it.

**Comment by Broxxi** [comment]
its not fixed, just had some crits not generating 2 combopoints.
