### ISSUE TITLE
Blazefury Medalion does not scale with spell power

### ISSUE THREAD

**Issue by valens14** [Progressive335/Progressive335#236]
The blazefury medallion item is not properly scaling with spell power.  Attacks while wearing the neck only add exactly 2 fire damage regardless of spell power. Comments from wowhead suggest that the item did scale with spell power.

https://www.wowhead.com/item=17111/blazefury-medallion#comments

The SP scaling indicated by the wowhead comments may be a bit much.  With no SP scaling though the item is essentially useless.  I would suggest maybe a ~2-3% SP scaling to make the item useful but not overpowered.

**Comment by Progressive335** [comment]
the item should not scale with spell power

https://github.com/TrinityCore/TrinityCore/issues/1701
