### ISSUE TITLE
[Quest] Redemption

### ISSUE THREAD

**Issue by WhiteGazelle** [Progressive335/Progressive335#237]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
quest -> 5742
__Place an X between the brackets to specify the ID__

[x] Quest
[] NPC
[] Quest

**Description of the bug:**
quest not working
**Current behaviour:**
quest missing gossip
**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**
https://www.youtube.com/watch?v=0GXV77ziJV4

**Comment by Jparoche** [comment]
Fixed the missing Gossip option on PTR. However quest isn't completing, Issue with SAI script.

**Comment by Jparoche** [comment]
Corrected smartAI script to allow quest to be completed.
