### ISSUE TITLE
Fishing Desync/multiple timers?

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#239]
**Description of the bug:**
When fishing, it feels like there are multiple server timers running, sending multiple "splash/fish got away/etc" packets to the client.

**Current behaviour:**
When fishing and the bug is triggered, you have a cast out.  You hear/see the splash and click to catch it, and it says "No Fish Hooked".  Then you cast back out, and you get a message "Fish Got Away" and your bobber disappears despite no splash/JUST casted.  This appears to happen after a cast near max range that doesn't let you actually open the loot window.

**Steps to reproduce the problem:**
1. Fish until you get a bobber you can't "loot" when it splashes.
2. Recast before the Fishing cast timer is out.
3. Try to catch the next splash.
4. Keep casting and fishing as the desync'd/multiple timers interfere with each other.

I think it's multiple timers because the desync/multiple timers seem to stop happening if you stop fishing for 15-20 seconds (Fishing cast shows as 17 seconds) for them all to "run out" and all fishing timers to send the "Fish Got Away" message to the client.

**Comment by Progressive335** [comment]
this was probably due server lagging and such, cannot reproduce such an issue today.
