### ISSUE TITLE
feral bear rage generation broken

### ISSUE THREAD

**Issue by oldspices** [Progressive335/Progressive335#241]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
trying to get rage as Feral bear is like pouring honey in winter. 
**Current behaviour:**
even big critting melee white hits generate barely enough rage to use any ability 
**Steps to reproduce the problem:**
go bear, hit things+get hit. 
**How it should work:**
like 400%+ more rage generation
**Any other documentation that could be helpful:**
maybe just compare it to other server idk.

**Comment by silverech0** [comment]
hello, what is your gear?
