### ISSUE TITLE
[Item] Harnessing Shadows

### ISSUE THREAD

**Issue by Chori97** [Progressive335/Progressive335#243]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
[item=18360]
__Place an X between the brackets to specify the ID__

[X] Quest
[] NPC
[] Quest

**Description of the bug:**
Item does not proceed to give you a quest when right clicked.
**Current behaviour:**
After right clicking the quest item it gives a message: "You don't meet the requirements for that quest"
**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**
I tried using it as a priest, on the item it says that priests and warlock are eligible.

**Comment by Jparoche** [comment]
Fixed on PTR
