### ISSUE TITLE
[Engineering]

### ISSUE THREAD

**Issue by omfgfoo** [Progressive335/Progressive335#245]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**Zap Farflinger <Unbalanced Engineer>:**

__Place an X between the brackets to specify the ID__

[] Quest
[X] NPC
[] Quest

**Description of the bug:**
He isnt teaching Dimensional Ripper - Everlook
**Current behaviour:**

**Steps to reproduce the problem:**
Missing
**How it should work:** 
Teaches you when you meet requirements as Goblin Engineer
**Any other documentation that could be helpful:**
https://classic.wowhead.com/item=18984/dimensional-ripper-everlook#comments

**Comment by Progressive335** [comment]
![image](https://user-images.githubusercontent.com/44980177/67137374-05205a80-f22c-11e9-9ad1-94c3f68b1e66.png)

you need the spell "Goblin Engineer" to be able to learn this.
https://wotlk.evowow.com/?spell=20222
