### ISSUE TITLE
Bug - Dancing rune weapon does not attack

### ISSUE THREAD

**Issue by Nubenai** [Progressive335/Progressive335#247]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:** https://wotlk.evowow.com/spell=49028?spells

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[X] Spell

**Description of the bug:** Dancing rune weapon does nothing when summoned.

**Current behaviour:** dancing rune weapon does not mimic your attacks for 50% damage.

**Steps to reproduce the problem:** Summon dancing rune weapon and attack an enemy.

**How it should work:** Dancing rune weapon should mimic your attacks for 50% damage.

**Any other documentation that could be helpful:** 
http://i.imgur.com/X9LHJ1O.png
Here, rune weapon accounts for ~12% DPS

When I test it, it doesn't even show up when it should be tied or above death coil in the list.
https://imgur.com/l63HABz

**Comment by valens14** [comment]
Been playing blood for a bit and haven't had a single dancing rune weapon actually mimic attacks.

**Comment by silverech0** [comment]
this has been fixed.
