### ISSUE TITLE
The Pariah's Instructions

### ISSUE THREAD

**Issue by misteryodt** [Progressive335/Progressive335#250]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**quest=7067

__Place an X between the brackets to specify the ID__

[] Quest The Pariah's Instructions
[] NPC Centaur Pariah
[] Quest

**Description of the bug:**3rd, 4th and 5th Kahn inside the instances are not spawned/missing.

**Current behaviour:**

**Steps to reproduce the problem:**Get the quest ,go inside Maraudon ,see no Kahn is spawned.

**How it should work:** Kahns should be spawned in Maraudon.

**Any other documentation that could be helpful:**https://www.youtube.com/watch?v=7uwx27uJZ0E the quality of the video is bad i know but its best i could find,skip straight to 2:58,youll see him enter the maraudon violet instance and go for the Kahn,here its missing ,as well the 4th and 5th one.

**Comment by VortexPrecision** [comment]
Quest works completely fine.
https://www.youtube.com/watch?v=QFZDWD974Gg&ab_channel=Bornlesszero
https://classic.wowhead.com/quest=7067/the-pariahs-instructions#comments
