### ISSUE TITLE
Prospector Khazgorm missing

### ISSUE THREAD

**Issue by EnyMan** [Progressive335/Progressive335#252]
**ID of the Spell/NPC/Quest:**

[X] Quest 843
[X] NPC 3392

**Description of the bug:**
Prospector Khazgorm <Explorers' League> is missing

**Current behaviour:**
He is not there

**Steps to reproduce the problem:**
Go there and see

**How it should work:**
Should spawn and on kill drop https://wotlk.evowow.com/?item=5006

**Comment by Jparoche** [comment]
NPC is available, Had a 10 minute respawn. Changed it to a 5 minute respawn
