### ISSUE TITLE
Maraudon Portal to Princess missing

### ISSUE THREAD

**Issue by Sunaqt** [Progressive335/Progressive335#258]
**Hey so the Portal inside Maraudon (outside the instance) which normally teleports you into the Earthsong falls area of Maraudon is visually available but you cant interact with it to enter the instance.**
 
**ID of the Spell/NPC/Quest: https://classic.wowhead.com/spell=21127/maraudon-portal **

[] Quest
[] NPC
[] Quest
[X] Object

**Description of the bug:
Cant interact with the portal to earthsong falls**

**Current behaviour: 
cant enter the portal**

**Steps to reproduce the problem:
Insert the missing object maybe ?**

**How it should work:
You should be able to enter the Portal so dont have run through the whole instance to farm Princess**

**Any other documentation that could be helpful:**

**Comment by flumby** [comment]
Do you have the sceptre ?

**Comment by Sunaqt** [comment]
yes i have it but it shouldnt be required in patch 3.3.5

**Comment by bonfax4** [comment]
Apparently it's only nto working for Alliance players, Horde party members were able to take the portal while I had to do the long path.

**Comment by Progressive335** [comment]
this has been fixed in previous changelog
