### ISSUE TITLE
in game mail lose items all times

### ISSUE THREAD

**Issue by Asherdoom** [Progressive335/Progressive335#259]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
When you send mail (for example to my guild mates) Items disappear in the fucking nowhere . although names are perfect and mail is correctly sent, for some reason items disappears and receiver never gets it
**Current behaviour:**
read above
**Steps to reproduce the problem:**
send a mail with something attached and wait
**How it should work:**
items should not vanish in the nether when sent by mail
**Any other documentation that could be helpful:**
yes, log in retail and look how mail works

**Comment by Progressive335** [comment]
Tested on PTR and on main realm, in both they are working. Have you waited long enough? you seem to be the only person with this issue.
