### ISSUE TITLE
chest of the seven in BRD spawns in wrong place

### ISSUE THREAD

**Issue by seph187** [Progressive335/Progressive335#263]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[x] NPC?
[] Quest

**Description of the bug:**
Chest of the Seven in BRD is in the wrong place.

**Current behaviour:**
Chest spawns at the top of the stairs

**Steps to reproduce the problem:**
kill the boss(es)

**How it should work:**
Chest should spawn near the exit door

**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
any screenshot?

**Comment by seph187** [comment]
I'll run again and get one tomorrow.

**Comment by Progressive335** [comment]
https://www.youtube.com/watch?v=6Mi4ir3A1-I&feature=youtu.be&t=185

**Comment by seph187** [comment]
![WoWScrnShot_101919_151705](https://user-images.githubusercontent.com/56495456/67151035-80622a80-f285-11e9-9197-a0cdb9a6dd99.jpg)

current spawn point
