### ISSUE TITLE
Windfury procc still to low 

### ISSUE THREAD

**Issue by PsychoMantiz** [Progressive335/Progressive335#265]
Windfury Weapon - ID: 16362

**Description of the bug:** WF still procc for around 5% instead of 20%. Full Raid run 4950 autohits with WF weapon, 263 WF proccs -> 5,3% chance

**Comment by Progressive335** [comment]
Tested on PTR proc was above 20%

**Comment by Broxxi** [comment]
maybe if you use it on both weapons, but it defnitly does not procc at a 20% rate.

**Comment by bonfax4** [comment]
That's a little more complicated to theorize if you understand that WF has a 3 sec ICD. You can't just base it off the amount of atacks.

**Comment by S3rafym** [comment]
This needs to be reopened guys. I tested it with a 2h weapon around level 30, it should still have 20% proc rate, it's about 6% atm...
