### ISSUE TITLE
[Dungeon][Loot] Stratholme - Sothos & Jarien D2 boss doesn't drop loot

### ISSUE THREAD

**Issue by crashwizard** [Progressive335/Progressive335#272]
**ID of the Spell/NPC/Quest:**
181083
[] Quest
[] NPC
[] Quest
[X] Object
**Description of the bug:**
When you defeat Sothos & Jarien in Stratholme live side within Balnazzar's room (D2 quest chain summon boss), you receive no loot.
**Current behaviour:**
Once you defeat the encounter, you receive no loot except the respective quest item.
**Steps to reproduce the problem:**
Go to Stratholme Live, Balnazzar's room. Use Brazier of Invocation (Item ID 22057) to summon Sothos & Jarien. Defeat them and you receive no loot.
**How it should work:**
Once you defeat the encounter, a chest should spawn on the ground that contains the loot (Object ID 181083)
**Any other documentation that could be helpful:**
Sothos NPC ID 16102
Jarien NPC ID 16101

Alternatively, you could add the loot from the chest to one of the NPCs for a quick fix (do not overwrite the already dropping quest item!).
Item IDs
22329 Scepter of Interminable Focus
22328 Legplates of Vigilance
22301 Ironweave Robe
22334 Band of Mending
22327 Amulet of the Redeemed

**Comment by Jparoche** [comment]
Items dropping correctly. - http://prntscr.com/pmfv6n

**Comment by crashwizard** [comment]
? the chest literally does not spawn when you kill the boss, I never said the chest loot itself is bugged. please read my ticket appropriately lol
