### ISSUE TITLE
[Mage/Talent] Arcane Potency

### ISSUE THREAD

**Issue by bonfax4** [Progressive335/Progressive335#273]
**ID of the Spell/NPC/Quest:** 31572

**Description of the bug:**
Arcane mage talent "Arcane Potency" is not working properly

**Current behaviour:**
Arcane missiles is consuming the buff even when it procs while the spell is already casting. 
**Steps to reproduce the problem:**
Cast arcane missile, wait for a proc mid cast and watch it fade away after the spell hits a target before the cats ends
**How it should work:**
It should only proc on spell cast . An arcane missile that procs it should not consume the buff while at the same time benefiting from the crit buff until a next spell is casted. Also, arcane missile should fully benefit from the crit and not just 1 missile when casted with the buff on. Basically the cast that consumes Clearcasting should fully benefit from the crit buff.
**Any other documentation that could be helpful:**
 https://wowwiki.fandom.com/wiki/Arcane_Potency

**Comment by bonfax4** [comment]
Forgot to mention but should still be be pretty important, arcane missile should only have a chance to proc clearcasting on spellcast aswell not per missile, hence the 2x benefit from the buff the link refers too. Missile that procs it benefits from the crit and so will the next missile cast.

**Comment by Chumanoyasha** [comment]
Yes i upvote, all missiles, should benefit from Arcane Potency. Makes arcane totally unplayable, without arcane blast.
