### ISSUE TITLE
Extra flight path from faction change

### ISSUE THREAD

**Issue by cyanpill** [Progressive335/Progressive335#274]
After changing faction, flight paths are granted based on your level. I went from Alliance to horde, and noticed I was given the "Shattered Sun Staging Area" which shouldn't be available until Burning Crusades. I didn't take the flight in case it would mess up my character.
I don't know if this would effect horde to alliance, since they don't have the next flight path over, but maybe the FP in front of ZA connects.
![WoWScrnShot_102019_160850](https://user-images.githubusercontent.com/42840505/67166146-c1783e80-f35a-11e9-8082-61c8f3bf5133.jpg)

**Comment by Progressive335** [comment]
you can use the flight path but u get instantly teleported back.

**Comment by cyanpill** [comment]
A minor addition, "The Bulwark, Tristfal" was not granted automatically.
