### ISSUE TITLE
Diremaul Book for Rogues

### ISSUE THREAD

**Issue by Broxxi** [Progressive335/Progressive335#275]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**18356

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[X] Item

**Description of the bug:**
Item says usable for Druids and Rogues, while it should only be for Rogue.
**Current behaviour:**

**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**

**Comment by Jparoche** [comment]
Not a bug, This is intentional.
