### ISSUE TITLE
Pathing mobs stop moving (until respawn) if path is interrupted.

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#276]
Mobs that have paths...whether that's walking back and forth 10 yards, or a long path like the goblin vendor from Tarren Mill to Southshore in Hillsbrad...if that path gets interrupted either via interaction (in the case of the vendor) or other ability (tested with a Rogue's Sap, so I know that works for sure) will stop the mob's pathing as intended...but after a timeout/the sap wears off, the pathing does not continue as it should.

If the mob dies/gets respawned, the pathing will continue on the new spawn.  Otherwise the pathing seems to be permanently stopped...when it should continue.

**Comment by Progressive335** [comment]
fixed in the last commit
