### ISSUE TITLE
[Shaman][Enhancement] Maelstrom Weapon stacks sometimes don't get expended

### ISSUE THREAD

**Issue by DemaciaMaggotPie** [Progressive335/Progressive335#277]
Spell ID: 51532

[] Quest
[] NPC
[X] Spell

**Description of the bug:** Sometimes, upon casting Lightning Bolt (maybe other spells), the shaman won't lose the stacks of Maelstrom Weapon, allowing him to cast an instant spell again.

**Current behaviour:** The shaman sometimes does not lose stacks.

**Steps to reproduce the problem:** Gain stacks by melee attacking, attempt to expend them. Sometimes, they will not be expended (couldn't find a pattern)

**How it should work:** In all cases, using a spell to expend the stacks should expend them.

**Any other documentation that could be helpful:**

**Comment by Jparoche** [comment]
Hi, Can you elaborate a bit on this, So for example when the bug happens if you use the same spell again will the stack disappear?
Is a specific spell that it happens on or any spells?

**Comment by DemaciaMaggotPie** [comment]
> 
> 
> Hi, Can you elaborate a bit on this, So for example when the bug happens if you use the same spell again will the stack disappear?
> Is a specific spell that it happens on or any spells?

1) If I use lightning bolt a second time, the stacks are usually expended, but I'm pretty sure I've casted three instant lightning bolt at some point. As if there was a small chance of it happening each time the stacks are expended.
2) Since it's hard to reproduce I can't tell, but my gut feeling is that it happens mostly on Lightning Bolt casts and not on (Lesser) Healing Waves.

A very bold idea I have, but it's just an hypothesis: Maybe the bug happens  when you connect an autoattack exactly during the cast, and that autoattack procs the gain of a Maelstrom stack. And that causes the x5 stacks to "refresh" while also queueing the instant-cast spell.

**Comment by Progressive335** [comment]
fixed, made the talent aura be removed upon the lightning bolt spell cast.
