### ISSUE TITLE
[SHAMAN] [ITEM] Shaman Totems not destructable

### ISSUE THREAD

**Issue by flumby** [Progressive335/Progressive335#278]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
Shaman Totems 
5175 - 5179 (ITEM ID)

**Description of the bug:**
Due to starting with the totems on character creation, please enable totems to be destroyed.
**Current behaviour:**
Cannot destroy totems

**Comment by Jparoche** [comment]
This is not a bug, Please open a ticket to have it removed. Else allowing shaman's to destroy their totems could cause accidental removals.
