### ISSUE TITLE
PvP Achievements for Alliance/Horde

### ISSUE THREAD

**Issue by Broxxi** [Progressive335/Progressive335#280]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__For example: 246 and 1005

[] Quest
[] NPC
[X] Achievement

**Description of the bug:**
I am a Horde player and i got atleast 3 Achievements 2 times. Mostlikely because of the Factionchange in Battlegrounds.
**Current behaviour:**

**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**

**Comment by Broxxi** [comment]
I'm also getting Alliance PvP Titles.

**Comment by Progressive335** [comment]
what achievements? give some more info, like screenshots and stuff.
