### ISSUE TITLE
Quest Defiling uther's tomb

### ISSUE THREAD

**Issue by S4ff0** [Progressive335/Progressive335#282]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
Quest-Id: 9444
https://www.wowhead.com/quest=9444/defiling-uthers-tomb

[9444] Quest
[Mehlar Dawnblade] NPC
[Defiling Uther's Tomb] Quest

**Description of the bug:**
Quest could not be completed ; button is greyed ;

**Comment by Progressive335** [comment]
![image](https://user-images.githubusercontent.com/44980177/67535542-fffb5980-f6ca-11e9-87b9-e87ede298e49.png)
seems to be a individual bug on your character
