### ISSUE TITLE
Certain Mob Auto Attack Values

### ISSUE THREAD

**Issue by Rorhn** [Progressive335/Progressive335#283]
NPC ID: 7286, 13022, possibly (very likely) many others.

[X] NPC

Mobs auto attack for too much damage.

Currently the zombies/whip lashers auto me as a ret paladin for ~300-400 each, this is significantly more than it should be.

Pull the mobs with any amount of armor, you'll get shredded.

The mobs should attack for significantly less.

https://youtu.be/qoDq2FcYXmE?t=277
You can see here exactly at 4:40 on .25x speed that one mob autos the mage (in Vanilla admittedly) for 148.
https://youtu.be/9MniAwwFKsg?t=115
Here at 1:55 on .25x speed you can see again that one mob autos the mage for 54.

**Comment by Jparoche** [comment]
Corrected

**Comment by Rorhn** [comment]
Thank you.
