### ISSUE TITLE
Mobs casting and moving still?

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#285]
**ID of the Spell/NPC/Quest:**
https://classic.wowhead.com/npc=7115

__Place an X between the brackets to specify the ID__

[] Quest
[X] NPC
[] Quest

**Description of the bug:**
You said in the changelog that: "[Creatures] Fix some cases where creatures could cast while moving."

Found another case where a mob was pathing/walking/moving and casting.  A Jaedenar Adapt was doing his patrol, sent my Felguard after him, he started walking away on his normal path but kept casting fireball.

**Comment by Shoro2** [comment]
Skeletons in western plagueland and dragons in burning steppes do the same

**Comment by LezChap** [comment]
I've seen it on a few other mobs now...seems to happen when they're doing their pathing scripts or whatever it does that makes them patrol/move, and instead of stopping the path to respond to the combat, they keep following the pathing script while in combat...and for some reason this lets them cast while moving.  It's actually kind of obnoxious for a few mobs where I'd have to chase them along their path, get a few spells in, then they're out of my range while continuing to cast at me and I have to run to catch up and try to get enough spells in to kill them before they kill me...

Also, when they're doing this pathing while casting bug, they don't seem to respect/honor threat...my pet is busy attacking, and producing more threat than me...but they often refuse to stop casting at me to target my pet.

**Comment by Progressive335** [comment]
This is a new issue compared to what was fixed, the issue fixed is related to creatures casting WHILE fleeing .
