### ISSUE TITLE
Death Grip

### ISSUE THREAD

**Issue by PrideQualityAssurance** [Progressive335/Progressive335#286]
**Please fill in the below fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
https://wotlk.evowow.com/?spell=49576

(49576)

__Place an X between the brackets to specify the ID__

[X] Spell
[] NPC
[] Quest

**Description of the bug:**
Death Grip doesn't pull the target close to the DK fast. It does the classic private server "jump" thing, where the enemy is jumping slowly to the DK high in the air. 

**Current behaviour:**
It does the classic private server "jump" thing, where the enemy is jumping slowly to the DK high in the air. 
When you grip a casting npc, the casting npc will sometimes stop in the air out of melee range and stand there casting.

**Steps to reproduce the problem:**
Death Grip an enemy.

**How it should work:**
https://www.youtube.com/watch?v=BBHoq6oLYqo

**Any other documentation that could be helpful:**

**Comment by LezChap** [comment]
Death grip currently seems to have all kinds of problems...most mobs seem to be "immune" to it.  It doesn't pull them closer at all right now, just initiates combat.

**Comment by LezChap** [comment]
To further comment on above...mobs not in combat seem to throw the immune message and not be dragged/pulled by Death Grip, and just initiates combat.  Once in combat, it works, but it doesn't always pull them as quickly as it should into melee range of the DK, and sometimes results in the NPC being snagged on invisible barriers in the air.

**Comment by Blindfreak** [comment]
A good idea of how to fix this issue is to use Sunwell as an example. They have the arc of the spell lowered close to the ground so the mobs avoid the stuck in midair problem and have sped the pull mechanic up immensely

![WoWScrnShot_120319_221017](https://user-images.githubusercontent.com/57071693/70117282-eaf2de00-1619-11ea-82de-fd60faf02727.jpg)
.

**Comment by Progressive335** [comment]
https://youtu.be/NsuTsP2Fb4c fixed
