### ISSUE TITLE
[Garona: A Study on Stealth and Treachery] for feral druids

### ISSUE THREAD

**Issue by gauriskion** [Progressive335/Progressive335#288]
https://classic.wowhead.com/item=18356/garona-a-study-on-stealth-and-treachery

**Description of the bug:**
The rogue's book from diremaul si labeled as usable as druids too, but it can't be used, whiel the druid's specific book [The Emerald Dream] can.

**Comment by Zooke** [comment]
Confirmed

**Comment by Jparoche** [comment]
Not a bug. Intended for feral druids.
