### ISSUE TITLE
Rich Thorium Veins

### ISSUE THREAD

**Issue by RemoteDefinition** [Progressive335/Progressive335#290]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

None

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[X] Item

**Description of the bug:**
Rich Thorium Veins when mined produces small amounts (1-2) of Thorium ores in comparison to the Small Thorium Vein which produces at the normal amount (2-4).

We assume that the Rich Thorium Veins would be able to produce or give more when gathering but it tends to fall short on Thorium ores in comparison to the Small Thorium Vein. It doesn't mean that the Small Thorium Veins are broken rather that the Rich Thorium Veins doesn't produce as much as it should.

**Current behaviour:**
Rich Thorium Veins when mined gives about 1-2 Thorium and some Dense Stone making it less valuable in comparison to Small Thorium Veins.

**Steps to reproduce the problem:**
Mining Rich Thorium Veins where you can find them. So far for what I've mined it seems to be every Rich Thorium Vein node that I have found that does it.

**How it should work:**
Rich Thorium Veins should be giving more thorium ores. I think the actual amount is roughly 6-9 thorium ores.

**Any other documentation that could be helpful:**
None that I have.

**Comment by LezChap** [comment]
Rich Thorium Veins do allow access to rare mats you cannot get from Small Thorium Veins...but I agree that the Rich Vein giving half the ore of the Small Veins is a bit off...imo they should both give the same amount of ore, and the chance of the rare mats is what makes them "rich".
