### ISSUE TITLE
D2 quest chain improperly issuing quests

### ISSUE THREAD

**Issue by valens14** [Progressive335/Progressive335#292]
When I did this chain I was issued all of the "Components of Importance" for both horde and alliance factions(two each time I should have been issued one random one).  After completing the quests I couldn't hand in my Right amulet quest and kept getting issued more of them.

**Comment by Jparoche** [comment]
Player is a Death Knight

**Comment by Jparoche** [comment]
https://classic.wowhead.com/guides/dungeon-set-2-quest-walkthrough-classic-wow#dset1tab-warrior

**Comment by Jparoche** [comment]
Quest items from summon-able bosses also allowing players who do not have quest to pick up item - need to look into what the quest items are called

**Comment by valens14** [comment]
Basically for the quest items I had one boss drop both left and right pieces and another dropped left, right, and a completed amulet.  It would only let me loot the piece for the quest I was on but other players were able to loot the other pieces even without being on the quest.
