### ISSUE TITLE
Demonic Pact not increasing warlock spell power 10%

### ISSUE THREAD

**Issue by Nsnugget** [Progressive335/Progressive335#293]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
5/5 demonic pact talent does not increase the warlocks spell power 10%

**Current behaviour:**
does nothing

**Steps to reproduce the problem:**

**How it should work:**
should increase 10% (2% per talent point)

**Any other documentation that could be helpful:**

**Comment by silverech0** [comment]
can you print some of your stats before and after the talent? thank you.
