### ISSUE TITLE
Defense from armor calculations

### ISSUE THREAD

**Issue by JJustop** [Progressive335/Progressive335#295]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
Me and other people have an issue with defense calculations. Currently, all of my gear gives less defense than its written.
**Current behaviour:**
My gear : 
Gyth's skull - Written 14 defense, it gives 9 defense to me
Medallion of grand marshal morris - Written 15, it gives 10 defense
Stockade Pauldrons - Written 15, it gives 10 defense 
Bracers of heroism ( With +5 defense enchant ) - Should give +9 it gives +6
Draconian  deflector - Written +15 gives +10
Stonegrip Gauntlets - Written +15 gives +10
Deathbone girdle - Written +14 gives +9
Naglering - Written +8 gives +5
Ardent Custodian - Written +7 gives +4

Overall my DEFENSE RATING is 300+74 defense , but with correct values i should have 300+112.

**Steps to reproduce the problem:**
Equip any defense gear on lvl 60 character and see that it doesn't give the appropriate amount.
**How it should work:**
It should give the correct amount of defense because it is written so on the item.
**Any other documentation that could be helpful:**
I have noticed that those values are from Vanilla WOW. Most of the items have their defense values from vanilla WoW even tho it is written in WOTLK style. Am i wrong and this is how it should work. Looking for answers.

**Comment by silverech0** [comment]
can't reproduce any issue with the defense rating, maybe you need to clean your cache? Will reopen if any more evidence is found.

**Comment by Snotshots** [comment]
I believe people are missing the difference between defense and defense rating.
