### ISSUE TITLE
Report Two Error Quests

### ISSUE THREAD

**Issue by rikamayaz** [Progressive335/Progressive335#296]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
1. ID 1248 The Missing Diplomat
2. ID 215 Jungle Secrets

__Place an X between the brackets to specify the ID__

[X] Quest
[] NPC
[] Quest

**Description of the bug:**
1. I can start the Quest but cannot end it because I cannot talk to the Quest Ender NPC Mikhail
2. I can start the Quest but cannot end it because I cannot talk to the Quest Ender NPC Lieutenant Doren

**Current behaviour:**
There's no yellow question mark at both of the Quest Ender

**Steps to reproduce the problem:**

**How it should work:**
I should be able talk to the Quest Ender to finish the quest

**Any other documentation that could be helpful:**
https://classic.wowhead.com/quest=1248/the-missing-diplomat
https://classic.wowhead.com/quest=215/jungle-secrets

**Comment by Jparoche** [comment]
Common bug with Trinity Core, Please drop quest and re-take. Let us know if issue still occurs.

**Comment by Progressive335** [comment]
closing this since player did not answer anymore.
