### ISSUE TITLE
Flight Paths between EPL and Ghostlands don't work correctly

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#297]
**Description of the bug:**
Any time you take a FP from one side of the portal to the other, it doesn't matter how far you want to travel, it stops you with a "teleport" at either EPL or Ghostland the moment you hit the portal.

**How it should work:**
You should "zone in" while in flight on the other side of the portal, and land wherever you selected.  If you were trying to fly to Booty Bay, you pay the full cost of the flight, but get stopped in EPL.

**Comment by Progressive335** [comment]
there was a bug before that the griphon would get stuck so this was an workaround to avoid players getting stuck there.
