### ISSUE TITLE
Gamon in Orgrimmar not attackable

### ISSUE THREAD

**Issue by zoomie-zoom** [Progressive335/Progressive335#298]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
6466
__Place an X between the brackets to specify the ID__

[] Quest
[x] NPC
[] Quest

**Description of the bug:**
Gamon cannot be attacked and it is impossible to finish the level 10 rogue quest as an orc.
**Current behaviour:**
Gamon is not attackable.
**Steps to reproduce the problem:**
Attack Gamon lol
**How it should work:**
Gamon should be attackable and remain neutral
**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
nice catch. he is indeed unattackable.
