### ISSUE TITLE
Blackblade of Shahram rarely proccing.

### ISSUE THREAD

**Issue by rick-wild** [Progressive335/Progressive335#299]
ID of the Spell/NPC/Quest:
16596
16597
16598
16599
16600
16601
item:12592

Place an X between the brackets to specify the ID

[x] Spell [] NPC [] Quest

Description of the bug:
Procs are extremely rare.

Current behaviour:
Procs about 1 time every 10 minutes of attacking.

Steps to reproduce the problem:
Farm mobs, attack training dummy for a long period of time.

How it should work:
Procs should be frequent enough that the buffs could actually stack.

Any other documentation that could be helpful:

**Comment by Progressive335** [comment]
you're missing that info that proves this.

**Comment by rick-wild** [comment]
https://classic.wowhead.com/item=12592/blackblade-of-shahram#comments
Most comments talk about a stacking buff which I couldn't achieve while testing. Take that as you will.
