### ISSUE TITLE
Flee movement speed

### ISSUE THREAD

**Issue by Mercath** [Progressive335/Progressive335#300]
Description of the bug: When humanoid mobs "attempts to run away in fear", they do so at very fast speeds, rather than reduced speeds.

Steps to reproduce the problem: Fight a humanoid mob until they try to run away: observer their running speed

How it should work: once injured and trying to run away, their speed should be reduced to 60% or so.

Any other documentation that could be helpful: This was noticed at the Defias mob camp just West of Sentinel Hill in Westfall, haven't tried it elsewhere. Sometimes they run away at the "appropriate" reduced speed, other times they run away at almost normal speeds. Haven't yet been able to pinpoint why this behaviour is erratic

**Comment by Zooke** [comment]
https://us.forums.blizzard.com/en/wow/t/wow-classic-not-a-bug-list-updated-10-28-2019/175887

From the list,
Feared players and NPCs run fast.
