### ISSUE TITLE
Avatar of Hakkar in Sunken Temple unable to be summoned.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#301]
Avatar of Hakkar in Sunken Temple unable to be summoned.
https://classic.wowhead.com/npc=8443/avatar-of-hakkar
Should be noted that in WotLK no items are needed to summon this boss. Can't remember if you had to light the braziers to summon or whether it was just there in WotLK times.
Alliance

**Comment by Progressive335** [comment]
i was able to summon him.

**Comment by Zooke** [comment]
Must have been something wrong with what we did then. Closed

**Comment by Zooke** [comment]
I have since been back to Sunken temple and can find nothing to click to summon the boss, can you elaborate on how you managed to summon the boss ?

**Comment by Zooke** [comment]
Ok, further investigation and I apologise. The summoning item was removed in 4.0.3, although this patch was still in WotLK it is later than our client 3.3.5.
