### ISSUE TITLE
Quest The Challenge (Multiple Bugs with script)

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#302]
Quest The Challenge
https://classic.wowhead.com/quest=9015/the-challenge
Va'jashni Troll Priest does Shadow Word : Pain at 1k/tick.
The Hunter summons multiple copies of his pet.
Wiping does not reset the event and then beating the encounter results in no quest credit.

**Comment by valens14** [comment]
I've seen this in the caster nagas on alcaz island too.  Same thing the SWP hits all targets in range and then ticks on all of them for 1-1.5k.  I think it may be a common problem to all mobs using SWP.

**Comment by Progressive335** [comment]
Seems to be working on PTR:
https://youtu.be/7n1Lrwjw27w

**Comment by Zooke** [comment]
Video is marked as private :(

**Comment by Progressive335** [comment]
check now

**Comment by Zooke** [comment]
Neither the hunter nor shadow priest was spawned, neither did you die and retry it.

**Comment by Progressive335** [comment]
i did die and retry it a couple of times. adds allways had been those and where is that 3k damage?

**Comment by Zooke** [comment]
https://ibb.co/wgHrCqy

**Comment by silverech0** [comment]
No one is thinking your making this up @Zooke we just need more details.

**Comment by ovifla25** [comment]
I can add on the feedback above. I am horde and on The Challenge quest. There are definitely issues, please let's try to test and clarify them,
FYI: I went there with another friend(2 man party, lvl60) and started the quest. 

1. We managed to kill them all, but 1 at a time, wiped, came back, killed the others - as the others did not despawn. 2 of them dropped blue times in accordance tot wowhead loot tables BUT:
Issue1: Chest did not spawn with quest item reward https://classic.wowhead.com/item=22047/top-piece-of-lord-valthalaks-amulet quest did not  acknowledge the kill credit https://classic.wowhead.com/npc=16166/theldren-kill-credit
Issue2: I'm not sure if bug or feature, but even if we've done multiple wipes we killed all and got rewards(blue items) but not quest rewards. Either this should happen or it is a bug and quest rewards are only received while banner is up(to summon them you place a banner down, after wipe the banned disappears. Possible fixes: let players get quest rewards if all killed in any conditions OR make them despawn if there is a wipe .

2. Va'jashni - the priest: puts Shadow Word: Pain that does 2k damage per tick -seems off, but can not prove it is a bug. He also does Renew on himself and on his aprty that ticks for...wait for it 200k per tick. 
Issue3: SW:P  and Renew values of the mob are very high - desing or bug? . 
Just a s FYI we killed him by CC--> Mana burn untill empty and could not renew --> kill

**Comment by Zooke** [comment]
Basically, what needs to happen here is that all adds available to be selected (fight chooses 4 from a pool) need to be checked for abilities.
The fight needs to reset properly on a wipe, being able to single pull them is not the idea of the fight. (Just despawn them on a wipe and make them require another summoning).
The corpses should not have loot, as mentioned above, the loot should be when the fight is over, not per add.
I don't know if a chest is supposed to spawn or not, but Theldren is the last mob killed so he should probably have the loot and quest item.
