### ISSUE TITLE
unable to turn in Wild Leather quests in Feathermoon

### ISSUE THREAD

**Issue by seph187** [Progressive335/Progressive335#308]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[x] Quest 2849, 2850
[] NPC
[] Quest

**Description of the bug:**
quest is flagged complete, but "continue" is greyed out.

**Current behaviour:**

**Steps to reproduce the problem:**

**How it should work:**
"continue" should be active.

**Any other documentation that could be helpful:**
![image](https://user-images.githubusercontent.com/56495456/67637109-368ccc00-f8a5-11e9-8e53-bf78332f73a1.png)
![image](https://user-images.githubusercontent.com/56495456/67637112-41dff780-f8a5-11e9-9b37-41cf7c6a96f5.png)
![image](https://user-images.githubusercontent.com/56495456/67637126-5d4b0280-f8a5-11e9-87c9-bc58341ae83d.png)

**Comment by seph187** [comment]
please check "Wild Leather Boots" and "Wild Leather Leggings" as well.

**Comment by Jparoche** [comment]
Please drop and re-take quests, Common bug on trinity core. If still an issue please reply.

**Comment by seph187** [comment]
Worked like a charm. Will keep in mind with any future quest issue. Thanks!
