### ISSUE TITLE
Caster Mobs don't appear to respect/follow Threat Tables

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#311]
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[X] NPC
[] Quest

**Description of the bug:**
Tested with Jadefire Felsworn, but appears to happen with all caster mobs.  Whoever first causes them to go into combat will be their target until they die (or run out of mana?  Haven't had them stay alive long enough to test when they transition to melee).  If you have a pet that'd supposed to be tanking them, and pulling high threat (double your threat and well above pull aggro according to Omen), the NPC will continue casting attacks against you and not aggro onto the "tank".  Also if the pet is on passive and body pulls, and then you cast spells causing all threat, the NPC will continue to cast on the pet until it dies. Haven't tested this with a player tank.

Caster mobs should respect threat tables just like melee mobs.

**Comment by Progressive335** [comment]
there isn't any difference between caster mobs or melee mobs, they are just mobs. i think this is probably specific.

**Comment by LezChap** [comment]
I was noticing this the most when killing the Jaedenar Felsworn in Felwood on my Warlock...if I was the first to pull aggro, my Felguard wouldn't pull the mob off me until the mob died...even if it had all the rest of the damage.  I'll try to get back there at some point and do more testing.

**Comment by Progressive335** [comment]
doesn't seem to happen anymore.
