### ISSUE TITLE
Pet/Demon Charges are broken

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#312]
**Current behaviour:**
This applies to Hunter pets as well as Warlock's Felguard.  When the pet does the Charge-like ability, the stun and damage apply immediately to the target like the charge happened, but the pet walks at normal speed to the mob to get into melee range before attacking the mob.  It worked fine a week ago, and seems to have become bugged when the NPC Movement fixes were pushed a few days ago.

**How it should work:**
A Charging pet should animate the charge and end up at the target's melee range a split second after the charge lands.

**Comment by Progressive335** [comment]
Confirmed, charge pathing on pets seems to be broken (tested on felguard only, not sure if hunter pets have the same issue one charging abilities)

**Comment by LezChap** [comment]
Impacts Hunter's Pets that spec into Charge as well.
