### ISSUE TITLE
NPCs/Pets don't always Melee attack, appear in melee range but won't move closer.

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#314]
__Place an X between the brackets to specify the ID__

[] Quest
[X] NPC
[] Quest

**Description of the bug:**
Melee NPCs and pets often get close enough to appear in melee range, but no melee attacks take place.  Also sometimes happens with auto-move option for players.

**Current behaviour:**
You send your pet to attack, or aggro a Melee NPC with a ranged attack.  The Pet/NPCs approach and appear to be in melee range, but no melee attacks occur.  Player autoswing melee attacks also don't appear to work if the player was the target of the NPC...the NPC/pet will sit there "idle", not moving closer to allow melee attacks, nor attacking.  Pulling the pet away from the NPC then sending them in to attack again (and also moving the enemy NPC), or if it's triggered via the player/NPC melee, moving a yard or so seems to allow the mob to path into proper melee range.

**Steps to reproduce the problem:**
I can't reproduce it 100% reliably to know what triggers the bug, but it happens regularly (1-5% of the time?).

**How it should work:**
Pets and NPCs should path into melee range so their melee attacks should work, and not get stuck in a range where their pathing says they're in melee but attacks won't work.

**Any other documentation that could be helpful:**
My assumption is somewhere in the code creature pathing into melee is checking if TargetRange <= MeleeRange, but MeleeAttacks code check if TargetRange < MeleeRange, allowing for pathing to get a 5yds == 5yds and return true, but the MeleeAttack checks if 5 < 5 and returns false...or a similar logic dis-congruity between the two sets of code.

**Comment by Progressive335** [comment]
Confirmed, it seems to happen with some pets in certain situations, not all.

**Comment by Progressive335** [comment]
fixed with recent corrections of combat move mobs.
