### ISSUE TITLE
Website progression points not registering.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#315]
Mentioned this to SilveR on Discord and said I would confirm it with a new dungeon run.
Just did BRD Upper RDF. No points scored.

**Comment by Zooke** [comment]
Did a UBRS and scored so closing this for now.

**Comment by Zooke** [comment]
LBRS gave no points so it seems some do and some dont right now.

**Comment by Progressive335** [comment]
Just killed bosses in the dungeon and got the points. can you tell me what bosses were doing this? cannot reproduce

**Comment by Zooke** [comment]
Chatted with SilveR about this on Discord, if you look at my MC boss kills for instance, some say 3, some say 4 (ignore the 5, that was a GM resetting that boss for us). Should be 4 on all.
https://plaguewood.com/index.php?option=armory&characterinfo=3771&viewmode=5&realm=1
Ony just says 1 instead of 2.
Happened on dungeon runs too sometimes.
Tbh I haven't been checking the last few days because I lost interest in it.
