### ISSUE TITLE
Zep from UC -> STV causes death

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#316]
The Zep from UC to STV causes death via fall damage when zoning into STV.  Probably a similar bug that was fixed in #279 when traveling from STV -> UC.

**Comment by Progressive335** [comment]
Tested on PTR and on Live server, no damage taken

**Comment by LezChap** [comment]
That's odd, happened to me last night minutes before making the report.  If there's been no changes, I'll try to test some more and figure out what causes it.
