### ISSUE TITLE
Azuregos drops combat on aggro reset.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#318]
As per the title, the recent 'fix' broke it.
https://github.com/Progressive335/Progressive335/issues/287

**Comment by Progressive335** [comment]
Applied a fix but unable to test as one player (he does not reset aggro before or after the fix for me)

**Comment by Zooke** [comment]
He's still doing it right now.

**Comment by Progressive335** [comment]
Another attempt to it
