### ISSUE TITLE
[NPC] [DROP] - Sharptalon Claw's

### ISSUE THREAD

**Issue by flumby** [Progressive335/Progressive335#320]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[x] Quest = 2
[x] NPC= 12676
[x] Item = 16305

**Description of the bug:**
Sharptalon (12676) Should have a drop rate of 100% for the item 16305 (Sharptalons Claw) which starts quest ID = 2
**Current behaviour:**
Killed once and no drop
**Steps to reproduce the problem:**
Go to ashenvale as horde, kill Sharptalon and find no drop
**How it should work:**
Go to Ashenvale as horde, kill sharptalon and get a 100% drop of the Sharptalon Claw
**Any other documentation that could be helpful:**
https://wotlk-twinhead.twinstar.cz/?item=16305

https://wotlk-twinhead.twinstar.cz/?npc=12676

**Comment by Jparoche** [comment]
Corrected.
