### ISSUE TITLE
Execute Bug

### ISSUE THREAD

**Issue by Estokek** [Progressive335/Progressive335#324]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[X] Spell
[] NPC
[] Quest

**Description of the bug:**
Execute sometimes uses an global but actually does nothing. To be clear it isn't missing or anything similar. It just does nothing. It eats a global and that's it.

**Current behaviour:**
See above.

**Steps to reproduce the problem:**
Not sure it feels pretty random, maybe after switching stances, but more likely because of something else.

**How it should work:**
You press it. It deals damage.

**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
it has a delay, if it's what you're reporting.

**Comment by silverech0** [comment]
can't really understand the bug, the spell is working correctly. gonna close until proper description.
