### ISSUE TITLE
Samantha Swifthoof should be flagged civilian.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#326]
https://classic.wowhead.com/npc=11748/samantha-swifthoof
Ok, so this didnt happen in 1.3, but it was in vanilla, and definitely should be part of a wrath database.

**Comment by Progressive335** [comment]
i don't get the issue, can you please explain ?

**Comment by Zooke** [comment]
Some npc's are flagged as civilians and give dishonorable kills.

**Comment by Jparoche** [comment]
Closed.
