### ISSUE TITLE
Elemental Invasion Boss adds bug out.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#333]
The adds surrounding these bosses can be pulled far enough that the boss and the rest of the pack run back, sometimes they evade and never reset, ever (until a server restart).
Only boss I didnt test was The Windreaver in Silithus, happens on the other 3 though.

**Comment by Jparoche** [comment]
Hi Zooke. Would you be able to provide NPC names or links to wowhead for us to investigate.

**Comment by Zooke** [comment]
https://wowwiki.fandom.com/wiki/Elemental_Invasions
All links avaiable on that page.

**Comment by Progressive335** [comment]
fixed
