### ISSUE TITLE
Duskwood Ogres are "mini me's"

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#338]
Ogres in Duskwood are, well not so ogre like.
<a href="https://ibb.co/T0yjfnn"><img src="https://i.ibb.co/T0yjfnn/Capture.png" alt="Capture" border="0"></a>

**Comment by silverech0** [comment]
any proof that the size is incorrect? your reports need to be way more specific than this.

**Comment by Jparoche** [comment]
unable to locate any information to backup this report - Scale is already set to default (1). Please post information regarding the sizing different between here and elsewhere. Else I'll close this bug until more information is found.
