### ISSUE TITLE
[Ability] Eviscerate (Rogue)

### ISSUE THREAD

**Issue by Kromster** [Progressive335/Progressive335#341]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**  https://wotlk.evowow.com/?spell=8624

__Place an X between the brackets to specify the ID__

**Description of the bug:** Eviscerates damage is low compared to the Tooltip

**Current behaviour:** 5 Combo point Eviscerate (Rank6) should hit 441-557 instead i am doing 300-340 eviscerates on all kinds of mobs (Beasts, Humans, etc)

**Steps to reproduce the problem:** Constantly getting 5cps and eviscerating not seeing the damage it should be doing ever

**How it should work:** It should be doing and scaling with the tooltip when i pop blood fury i get 162 attack power and the tooltip shows 458 -609 with 5 combo points on Eviscerate but the damage is no where near those numbers something is wrong with it or its been under tuned.

**Any other documentation that could be helpful:**
 Can link my twitch vod if you want to see some of the rogue leveling footage where i look at the damage from the ability's let me know on Discord if you need Krom#4691

**Comment by Jparoche** [comment]
Not an issue, The armor values of the mobs are taken into account on the damage. -> The screenshot below is taken on a mob with 0 armor. http://prntscr.com/pricn6

**Comment by Kromster** [comment]
I even used expose armor which reduces armor by 20% and the damage did not increase just seems very underwhelming to use eviscerate, also on that screen shot 500 eviscerates was that max rank evis or rank 6? that damage looks wrong for a 5cp evis
