### ISSUE TITLE
Resource Nodes (mining) don't appear to be respawning properly

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#343]
Kinda hard for me to prove as a player, but since the update to resource nodes, mining nodes seem to have a few problems, which may be related.

One, they don't appear to be respawning properly.  I'm running around Burning Steps looking for nodes, found a couple in VERY out of the way places, but since then, I can't find newly spawned nodes anywhere.  I've done several laps, and then reversed directions to see if I'd run into someone from the other faction farming them (no one was showing up on /who -z).  No luck.

The other problem I've noticed is areas do not have the nodes they should.  Blasted Lands should be full of Mithril and rare Silver nodes, but all I found when doing a few laps was Iron.  It could be related to the above if the Mithril and Silver were mined out, and failed to respawn.

I agree that before the fix earlier tonight, resources were a bit ridiculously abundant...but this nerf is a bit too stronk.

**Comment by Zooke** [comment]
I think this nerf should be abandoned, it is against the spirit of the server.
Xp is increased, crafting rates increased, drop rates increased, crafting cd's removed etc etc.
Making nodes rare doesn't fit. This applies to herbs too.

**Comment by Progressive335** [comment]
@Zooke it's not because of it, is just because the spawns were insanely wierd. they should be fixed and will be fixed, we will reach a point where it's going to be fair.

**Comment by LezChap** [comment]
I agree that how they were a few days ago was a bit...excessive.  20 minutes of farming and you'd have bags full of Thorium (and stone and the rarer gems).  I agree how they were before the reboot in the last hour wasn't better, with almost nothing spawning.  I think it needs to be somewhere in the middle, and look forward to seeing how the fixes pushed tonight look.

**Comment by Progressive335** [comment]
they seem fine now, reopen if you still have issues.
