### ISSUE TITLE
Greater Firebird Fire Nova seems a bit OP

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#344]
https://classic.wowhead.com/npc=8207/greater-firebird

<a href="https://ibb.co/Qrps4rB"><img src="https://i.ibb.co/Qrps4rB/Capture.png" alt="Capture" border="0"></a>

No data as to the actual value it should hit for but judging by the lack of comments regarding an 850 hit every 5 or so seconds I'm guessing he's using the wrong rank of spell.

**Comment by Progressive335** [comment]
need more info.

**Comment by Zooke** [comment]
Couldn't find any information on spells and ranks used by this mob.

**Comment by Zooke** [comment]
https://wotlk.evowow.com/?spell=16079#used-by-npc
Also used by the 61 elites in wetlands.
