### ISSUE TITLE
Dancing rune weapon is now attacking but for far lower damage than it should.

### ISSUE THREAD

**Issue by valens14** [Progressive335/Progressive335#347]
DK dancing rune weapon should mimic all attacks the DK does but for 50% damage.  Currently the damage is far lower than 50%.  The screenshot has recount data from 1 melee attack 1 plague strike and 1 icy touch done with dancing rune weapon on showing the damage done by the DK and the DRW.
![WoWScrnShot_110319_123111](https://user-images.githubusercontent.com/6764108/68089357-14abc000-fe36-11e9-95d2-9567923445c6.jpg)

**Comment by Progressive335** [comment]
missing valid infos

**Comment by Progressive335** [comment]
Next time fill with some info, some links and stuff . Thanks. Fixed
