### ISSUE TITLE
Shattered Necklace dropping for Horde

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#350]
**ID of the Spell/NPC/Quest:**
https://classic.wowhead.com/item=7666
__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[X] Quest/Item

**Description of the bug:**
This item starts an Alliance-Only quest.  It has no other purpose, but drops for Horde characters fairly regularly, and requiring us to manually delete it.  It should not drop for Horde characters.

**Comment by Jparoche** [comment]
Necklase seems to be also used for: https://classic.wowhead.com/quest=2283/necklace-recovery which is a horde quest. - Please confirm.

**Comment by LezChap** [comment]
If that's the case, it should only drop when you're on the quest I think?  Currently it drops regardless, says it starts a quest...but when you right click it to start the quest, it says it's unavailable for your race...I don't believe that's blizlike/intended?

**Comment by RemoteDefinition** [comment]
I can confirm of the item dropping for me as a member of the Horde especially when I don't have the quest . Usually when I RDF for Uldaman, I don't have the correspondent Horde quest to get the item.

**Comment by Progressive335** [comment]
![image](https://user-images.githubusercontent.com/44980177/69167849-80a44e80-0aed-11ea-8b74-1ad48580e8ae.png)
this seems to be used for something else.
