### ISSUE TITLE
Fish schools may stack

### ISSUE THREAD

**Issue by Marluxius** [Progressive335/Progressive335#351]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
All fish schools
__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Item

I'm not sure what fish schools count as.

**Description of the bug:**
Multiple fish schools spawn on the exact same location.
**Current behaviour:**
Fish schools may stack to 2-3 schools on the same spot.
**Steps to reproduce the problem:**
Look for some fish schools and check if there are stacked schools.
**How it should work:**
They shouldn't stack.
**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
can you provide a sample location for testing?

**Comment by Progressive335** [comment]
Can't confirm, looked over their spawns, seem separate. closing this issue until better evidence of the location.

**Comment by Zooke** [comment]
https://youtu.be/msUy9lqut20

**Comment by Progressive335** [comment]
@Zooke location?

**Comment by Zooke** [comment]
That is right by the boat you fixed to summon Negolash

**Comment by Zooke** [comment]
Saw 2 'double pools' in Booty Bay earlier so this is not an isolated case.
