### ISSUE TITLE
[Crashes] - Playername:  Frauke Reports Quests that cause crash.

### ISSUE THREAD

**Issue by flumby** [Progressive335/Progressive335#352]
The following quests causes crashes
Volunteer´s Battlegear
Veteran´s Battlegear
Champion´s Battlegear
Stalwart´s Battlegear
They are located in Cenarion Hold Silithus at Blacksmith Vargus

**Comment by Jparoche** [comment]
Quests are not available - Please advise - Please have player report with a screenshot from ingame.

**Comment by Zooke** [comment]
Revered quest causes a client crash for me. Heard a number of people mention this in chat over the weeks.
