### ISSUE TITLE
[Quest] Kodo Round up - Tamed Kodos move *very* slowly

### ISSUE THREAD

**Issue by noxaylox** [Progressive335/Progressive335#354]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Kodo Roundup
https://classic.wowhead.com/quest=5561/kodo-roundup

[X] Quest https://classic.wowhead.com/quest=5561/kodo-roundup
[X] NPC https://classic.wowhead.com/npc=11627/tamed-kodo

**Description of the bug:**
The quest is to use the item Kodo Kombobulator to tame Aged, Ancient or Dying Kodos to bring back to the Goblin camp at Desolace at 60, 61.  Once the item is used and the Kodo turns in to a "Tamed Kodo" its movement speed drops so low the 5 min timer runs out before you can get them back to the camp.

**Current behaviour:**
Once it becomes a Tamed Kodo, the Ancient, Aged and Dying kodos move at about 10% speed.
Tamed Kodos are also neutral NPCs and can be killed.

**Steps to reproduce the problem:**
Accept the quest from the NPC at Desolace at 60, 61 and take the quest item (Kodo Kombobulator) to The Kodo Graveyard in Desolace 54, 62. Use the item on any Ancient, Aged or Dying Kodo to turn it in to a Tamed Kodo.  Once the Kodo is Tamed its movement speed is reduced.

**How it should work:**
1) Once the kodo is tamed it should follow you at regular speed.
2) Tamed Kodos should not be killable
3) once you turn in the tamed kodo the Kodo Kombobulator debuff should be removed

**Any other documentation that could be helpful:**
Video of how the quest should work: https://www.youtube.com/watch?v=wvPGRKh2dZk
(updated video link to use the example provided by WoWhead recorded on WoW Classic Retail.)

The work around for the quest is to tame the kodo then kill it.  You get credit for quest.  You can only do this once every 5 mins as the quest item applies a 5 min debuff where you cannot use it again for 5 mins.

**Comment by Zooke** [comment]
That link is from a private server.

**Comment by Progressive335** [comment]
> That link is from a private server.
> Private servers taking what other private servers have done to be gospel is like chinese whispers.

??? what are you talking about

**Comment by Zooke** [comment]
Is the video from WoW Classic retail ?
If evidence submitted is from private servers then how can we have any proof that the private server it was recorded from has scripted correctly ?

**Comment by noxaylox** [comment]
I did not verify where the example video came from but this is how the quest functions on Classic.

Even if I remove the video link if you test the quest you can see there is a problem.  The tamed kodos move too slowly for you to get back to the quest giver before the timer runs out.
