### ISSUE TITLE
X-mog Issues with MH/OH

### ISSUE THREAD

**Issue by Blindfreak** [Progressive335/Progressive335#355]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Warpweaver <Transmogrifier>

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest
(Vendor Issue)
**Description of the bug:**
Cant see MH/OH wapons in the X-mog vendor menu.

**Current behaviour:**
The X-mog vendor wont show MH/OH (1 hand weapons, only tried with Quel'serar and Blackguard) but will show armor peices and other weapons (Bows/x-bows/guns)

**Steps to reproduce the problem:**
Go to the vendor, have weapons equipped or in menu, still doesn't show.

**How it should work:**
Should show/allow x-mogging

**Any other documentation that could be helpful:**
![WoWScrnShot_110419_231318](https://user-images.githubusercontent.com/57071693/68186682-91838a80-ff59-11e9-8f55-1b0108a4fab0.jpg)

![WoWScrnShot_110419_231310](https://user-images.githubusercontent.com/57071693/68186656-803a7e00-ff59-11e9-8dd7-8c68c5820fcc.jpg)

**Comment by Progressive335** [comment]
The need to be of the same quality
