### ISSUE TITLE
[Quest] Goldtooth can't be done.

### ISSUE THREAD

**Issue by Nastybitch** [Progressive335/Progressive335#356]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[X] Quest 87
[] NPC
[] Quest

**Description of the bug:**
Quest can't be turned.
**Current behaviour:**
NPC got gray ? mark, even if you got necklace in inventory
**Steps to reproduce the problem:**
Complete first 3 steps of the chain and get this quest, kill Goldtooth, loot necklace, stuck @turning quest.
**How it should work:**
? mark must be orange and quest itself must be doable.
**Any other documentation that could be helpful:**
https://i.postimg.cc/4NWVvGWc/Wo-WScrn-Shot-110519-150530.jpg

**Comment by Progressive335** [comment]
not a quest bug but a generic bug from the client, either delete cache and try again or retake quest and try again.
