### ISSUE TITLE
AoE often puts mobs through walls/floors/roofs into combat.

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#357]
AoE combat abilities will often cause mobs through walls, floors, and other barriers to enter combat with the caster.  Sometimes this will pull the mobs through a dungeon, causing a massive/full dungeon pull.  Sometimes this results in the mob being permanently placing the player in combat.  Probably related to #342 

Tested with Consencration and the boats in the pirate area of Tanaris.

**Comment by Progressive335** [comment]
need a specific case like where, which mobs, and which spell.

**Comment by LezChap** [comment]
I've had it happen with Volley on the ramp before LBRS...pulled extra mobs. that came up from under the ramp.  That's a bit harder to get hard evidence of solo.

Tested the Tanaris boats in the pirate area with Volley and couldn't get it to happen.  Went on my DK and tested with Death and Decay, again didn't have much luck triggering it.

Consecration (Rank 4 tested in screenshot) seems to trigger it on this mob here: https://i.imgur.com/v94RUKX.jpg  I think he doesn't have a path out of the boat and stays aggro'd...though even if I enter the boat giving him a path, he won't aggro onto me without another attack/bodypulling.  He's the one keeping me in combat though.

Here, I'm hitting all the mobs below me on the ship, even though I'm not in combat from it: https://i.imgur.com/IcGmcIp.jpg

**Comment by LezChap** [comment]
Pestilence (https://wotlk-twinhead.twinstar.cz/?spell=50842) appears to be doing the same thing with mobs on the multiple levels of the houses here: https://i.imgur.com/rZspwbh.jpg

They don't get the diseases, but mobs above you when you're fighting on the ground floor will keep you in combat, even tho they won't attack/aggro you until you attack them/body pull.

**Comment by Progressive335** [comment]
related to https://github.com/Progressive335/Progressive335/issues/342, closing this to avoid having multiple tickets of the same issue.
