### ISSUE TITLE
Hunter Dire Maul book not available

### ISSUE THREAD

**Issue by cyanpill** [Progressive335/Progressive335#358]
"The Greatest Race of Hunters" item id 18361 is unavailable. With atlas loot I can look up all the other books from diremaul, but that book specifically is unavailable. Players say no one has seen it drop in game. The royal seal it rewards is available.

**Comment by Zooke** [comment]
Can confirm that these items fail the query on Atlasloot.
Add the Force Reactive Disk (18618) also fails. The recipe for this item (18291) is however valid. This will cause a problem if someone tries to craft it.

**Comment by Jparoche** [comment]
Hi, The book itself isn't locked but was missing, This has been corrected.. I've also added the plans for the Force Reactive Disk to the locked items list(https://wotlk.evowow.com/?item=18291) - thanks for the report
