### ISSUE TITLE
Autolearner - Issues

### ISSUE THREAD

**Issue by LezChap** [Progressive335/Progressive335#360]
Once you buy a weapon skill, at some point you'll be able to buy it again from the Weapon Trainers, even though it's still in your skill list...SilveR said this was a bug with the Auto-Learner unlearning skills when it shouldn't, and in order to fix it, he needed a list of classes/weapon skills that are effected.

This post is my attempt to start to provide that list.  Please comment with your race/class (there are some cases where different races start with different weapon skills) and weapon skills that are purchasable even though you have them in your skill panel, and I'll try to keep this post edited with the list.

- [x]  **Rogue (_Orc_):** One-Handed Axes, One-Handed Maces, One-Handed Swords, Crossbows, Bows, Guns, Fist Weapons
- [x]  **Death Knight (_Orc_):** One-Handed Maces, Two-Handed Maces
- [x]  **Hunter (_Orc_):** Two-Hand Swords, Crossbows, Staves, Thrown, Fist Weapons, Guns
- [x]  **Warlock (_Blood Elf_):** One-Handed Swords
- [x] **Druid (Tauren):** Fist Weapons, Polearms, Two-Handed Maces

**Comment by Zooke** [comment]
Seen this too on rogue and druid.

**Comment by LezChap** [comment]
Yes, pretty much every weapon skill you need to purchase on any character will see this bug.  SilveR said he needed a list of skills by class in order to fix it, so I'm trying to crowd-source creating that list...I don't have EVERY class yet ;)

**Comment by Knight-Pachirisu** [comment]
Yeah, for some reason this happens. I already told SilveR about it on Disc a few days ago.
It's nothing game breaking as you can open the Skill window and they're there, but it's certainly nice to have all the weapon skills listed for each class.

**Comment by silverech0** [comment]
yes, i need to know this to be able to fix it, thanks for infos.

**Comment by Progressive335** [comment]
Another issues:

- [ ] Missing mage portals.
