### ISSUE TITLE
[Website] Timer on homepage wraps to next line occasionally

### ISSUE THREAD

**Issue by noxaylox** [Progressive335/Progressive335#362]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
Just getting a super minor website display buglet logged

**Description of the bug:**
The ticking timer on the homepage of the website wraps to the next line occasionally

**Steps to reproduce the problem:**
Go to the homepage of the website on 
Windows 10/ Chrome Version 78.0.3904.70
Resolution: 3840 x 2160

**How it should work:**
Timer should either stay on 2 lines or not wrap to the next line.  
Timer should not jump back and forth.

**Any other documentation that could be helpful:**
Gif of timer jumping to second line: https://i.imgur.com/ZBZ9jor.mp4

I was able to replicate this on Windows 10 in
* Firefox 70.0.1
* Edge 44.18362.387.0
* 1980 x 1200 resolution

**Comment by silverech0** [comment]
Minor issue.
