### ISSUE TITLE
[Talent] [Hunter] Lock and load proc rate much too low

### ISSUE THREAD

**Issue by Snotshots** [Progressive335/Progressive335#363]
https://wotlkdb.com/?spell=56344

**Description of the bug:**
Lock and load proc rates are not currently 'blizzlike' although this may be intentional?

**Current behaviour:**
From black arrow you are lucky to see a single proc in a boss fight
Frost trap and freezing trap should be 100% but only seems to work on certain mobs (yes i know frost traps shouldn't proc it if a mob is not slowable)

**Steps to reproduce the problem:**
spec survival use black arrow, traps etc, see that lock and load rarely procs
**How it should work:**
can't find an offcial blizzard source at present but will keep on digging. Below link states a 6% proc chance per tic of black arrow or explo/trap and was a fairly reliable source during retail wotlk.
https://huntsmanslodge.com/5663/hunter-basics-explosive-shot/

**Comment by Progressive335** [comment]
need more info about the proc chance. can't know if it's bugged or not.

**Comment by Snotshots** [comment]
I accept that for the Black arrow/Explosive Trap proc chance, but the Freezing/Frost trap chance is clearly stated in the talent.

**Comment by Progressive335** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15262

**Comment by Progressive335** [comment]
@Snotshots can u read that issue and confirm if that's the same thing?

**Comment by Snotshots** [comment]
It's at least a similar issue. IDK anything about the coding side of it but my experience on PW has been that the 100% chance from freezing trap and ice trap doesn't work on some mobs (e.g. onyxia whelps). Explosive trap seems to have a reasonable proc rate although that's probably due to the dot being applied to so many targets, and black arrow's proc rate is almost nothing.

**Comment by Progressive335** [comment]
> It's at least a similar issue. IDK anything about the coding side of it but my experience on PW has been that the 100% chance from freezing trap and ice trap doesn't work on some mobs (e.g. onyxia whelps). Explosive trap seems to have a reasonable proc rate although that's probably due to the dot being applied to so many targets, and black arrow's proc rate is almost nothing.

i was asking about the description of the bug itself. i'm looking into it and provide a fix.
