### ISSUE TITLE
Ancient Sinew Wrapped Lamina stat bonus missing

### ISSUE THREAD

**Issue by KrasterK** [Progressive335/Progressive335#364]
The item Ancient Sinew Wrapped Lamina in vanilla wow used to provide a 15% ranged attack speed increase but it was taken away 3.2.0, Since we're playing on vanilla wow patches rn it would be nice to see it back in the game

item ID_18714

This item is a reward from the quest ''Ancient Sinew Wrapped Lamina'' 
quest=7634

**Comment by Snotshots** [comment]
Quivers do not  give a speed bonus in wotlk though. working as intended.
