### ISSUE TITLE
Herbalism Skill Points

### ISSUE THREAD

**Issue by Brotas63** [Progressive335/Progressive335#365]
**Description of the bug: Example (Photo): My Herbalism is at a high Level and I loot a Plant that is gray (shouldn't give me Skill Points), it sometimes gives me Skill Points.

**Steps to reproduce the problem: Just try to farm outdated Plants and eventually it will give you Skill Points.

**How it should work: You shouldn't get Skill Points for gray Plants

**Any other documentation that could be helpful:**
![WoWScrnShot_110719_075458](https://user-images.githubusercontent.com/57477597/68367826-dc0e2e00-0136-11ea-8066-ce33ed010bc2.jpg)

**Comment by Progressive335** [comment]
i tried and i was unable to reproduce this issue, with the same skill level as you and looting the exact same herb.
