### ISSUE TITLE
Non-hostile Mobs are fleeing mid-fight 

### ISSUE THREAD

**Issue by bthoennes** [Progressive335/Progressive335#367]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Spell
[X] NPC
[] Quest

**Description of the bug:**
When fighting various yellow/non-hostile mobs, they occasionally stop fighting and return to their original position. This is a kind of"de-aggroing". 

**Current behaviour:**
Non-hostile mobs will "de-aggro" mid-fight. 

**Steps to reproduce the problem:**
I have had trouble consistently reproducing this problem, but this is my most reliable method for reproducing this issue. I am using a warlock and have not experienced this on another class. 
1.) I pull the mob with a ranged spell
2.) My pet generates enough threat to pull aggro on the mob
3.) I generate enough threat to pull aggro back to my character
4.) At the moment the aggro is supposed to switch back to the warlock, the mob will de-aggro.

**How it should work:**
The mob should stay "aggroed" to its target until one of the following happens:
1.) the mob has not been attacked by its target while chasing the target for a defined period of time (not related to this issue)
2.) Another character generates enough threat to pull the mob
3.) the mob dies

**Any other documentation that could be helpful:**
https://www.youtube.com/watch?v=WE4Vsa9kliI

**Comment by Progressive335** [comment]
related to latest issue with creature movement, is fixed, check changelog
