### ISSUE TITLE
Engineering allows both specialties.

### ISSUE THREAD

**Issue by ShadowVariable** [Progressive335/Progressive335#371]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[12656] Profession: Engineering

**Description of the bug:**
Currently, if you get to 300 Engineering you can learn the recipes from both specialties, goblin and gnome, without doing the prequests.

**Current behaviour:**
Respective trainers teach the recipes without the quest and you can learn both sets.

**Steps to reproduce the problem:**
Get to 300 engineering, talk to the goblin teacher in everlook and the gnome teacher in gadgetzan/booty bay, and they will teach you.

**How it should work:**
You should have to get to the prerequisite skill level first (225 i think), then choose one and do the quest line to unlock it and then be locked to that specialty unless you drop the profession and restart.

**Any other documentation that could be helpful:**
https://classic.wowhead.com/guides/engineering-profession-classic-wow#engineering-specializations

**Comment by Progressive335** [comment]
this is generic, i've seen other professions with this issue.

**Comment by Zooke** [comment]
I thought it was a 'feature'.

**Comment by Progressive335** [comment]
Gnomish Engineering ( https://classicdb.ch/?spell=20220 ) 
https://classicdb.ch/?quest=3640  ( ALLY)
https://classicdb.ch/?quest=3641 (ALLY) 

https://classicdb.ch/?quest=3642 (HORDE ) 
https://classicdb.ch/?quest=3643 (HORDE )

Goblin Engineering ( https://classicdb.ch/?spell=20221) 
https://classicdb.ch/?quest=3638 
https://classicdb.ch/?quest=3639
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
https://classicdb.ch/?spell=4036  Apprentice Engineering - São 17 Trainers :D
https://classicdb.ch/?spell=4037 Journeyman Engineering  - NPC 8736  / 11031 / 5518 / 3412 / 11017 / 5174 / 11029 
https://classicdb.ch/?spell=4038 Expert Engineering - NPC 8736 / 11017 / 5174 
https://classicdb.ch/?spell=12656 Artisan Engineering - NPC 8736
