### ISSUE TITLE
Cant talk to Rivern Frostwind (wintersaber rep)

### ISSUE THREAD

**Issue by Nsnugget** [Progressive335/Progressive335#376]
[] NPC

Rivern Frostwind is red and only attackable (can't talk to him/get quests for rep)

Go to his location in NW winterspring

He should have a quest to repeat to grind rep.

**Any other documentation that could be helpful:**
![winterspringmob](https://user-images.githubusercontent.com/55918939/68609004-40582700-0482-11ea-851c-cf2be752485b.PNG)

**Comment by Zooke** [comment]
Are you horde ?

**Comment by Nsnugget** [comment]
I am not horde and that seems to have been the problem. Rip

**Comment by Zooke** [comment]
You misunderstand, this is an alliance quest, Horde have the ravensaur guy in Ungoro.

**Comment by Nsnugget** [comment]
Ya I hang my head in shame haha.
