### ISSUE TITLE
Muckshell Snapclaw poison

### ISSUE THREAD

**Issue by Jonsse** [Progressive335/Progressive335#377]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest: 4402

__Place an X between the brackets to specify the ID__

[] Quest
[x] NPC
[] Quest

**Description of the bug: A level 40 mob in dustwallow marsh applies a stacking poison debuff that does 220-280 damage per tick.

**Current behaviour: Applies a stacking dot that does over 220 dmg/tick of poison damage.

**Steps to reproduce the problem: any application

**How it should work: a lvl 40 mob should not have a dot that powerful.

**Any other documentation that could be helpful: https://wotlkdb.com/?npc=4402#.

**Comment by Progressive335** [comment]
> **How it should work: a lvl 40 mob should not have a dot that powerful.

that is not a valid argument for a fix. the spell can be correct, you need to give info where it's incorrect.

**Comment by Jonsse** [comment]
Ok I guess a mob that if you don't kill in 10 seconds will give you two stacks of a 30 sec poison that now ticks for 530 damage every 3 seconds is a perfectly viable monster to have in a world where a level 40 player has 1,5-2k health. Guess it's supposed to do that then since I have no other arguments.

**Comment by Zooke** [comment]
I have no official information either, but https://wotlk.evowow.com/?spell=25645#used-by-npc
does seem to suggest an anomaly.

**Comment by Progressive335** [comment]
> Ok I guess a mob that if you don't kill in 10 seconds will give you two stacks of a 30 sec poison that now ticks for 530 damage every 3 seconds is a perfectly viable monster to have in a world where a level 40 player has 1,5-2k health. Guess it's supposed to do that then since I have no other arguments.

sorry i wasn't trying to be rude, is because info sometimes is needed.

**Comment by Progressive335** [comment]
https://wotlk.evowow.com/?spell=25645
https://wotlk.evowow.com/?npc=4402

in this db is this way too hum.

**Comment by Progressive335** [comment]
wowhead seems to suggest he has no abilities.
https://classic.wowhead.com/npc=4402/muckshell-snapclaw
