### ISSUE TITLE
Lord Alexei Barov bugged pathing.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#379]
https://wotlk.evowow.com/?npc=10504
When pulled this mob and an add go up through the ceiling to the landing above.
This has been happening since the server launched, surprised it's never been reported.
It's almost as if theres an invisible wall mobs cannot pass at the top of the few steps in his room because if you let him go through the roof and come all the way round the stairs back to you he can't navigate the steps again.

**Comment by Jparoche** [comment]
Where is this NPC located? The wiki link doesn't provide much information.

**Comment by Zooke** [comment]
Scholomance, bottom floor by the final boss.
