### ISSUE TITLE
Pathing of Jade Oozes in the Hinterlands

### ISSUE THREAD

**Issue by Knight-Pachirisu** [Progressive335/Progressive335#380]
**Description of the bug:**
Some of the Oozes in the Hinterlands, namely those on the cliffs on Skulk Rock, when aggroed will go underneath the mountain and go through a ridiculously long path to where you are.

**Current behaviour:**
The mob goes underground, likely falling onto the cave's ground, then attempts to get out of the very same hole it got itself into.

**Steps to reproduce the problem:**
Simply aggro a few of them, unless you are within melee range they will fall.

**How it should work:**
Walk/sliding/whatever slimes do to get around, along the mountain.

**Comment by Progressive335** [comment]
print of the map and exact location?
