### ISSUE TITLE
Avalanchion pathing.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#381]
https://classic.wowhead.com/npc=14464/avalanchion
He walks anticlockwise down the path between the hills and then through the hill back to just before the path.

**Comment by Zooke** [comment]
I've definitely seen him do this, but his pathing looks ok.

**Comment by Zooke** [comment]
Ok, so more testing, If you aggro him and the adds, then run away and try and split him from his adds, his pathing will go haywire and the adds can bug out.

**Comment by Progressive335** [comment]
> Ok, so more testing, If you aggro him and the adds, then run away and try and split him from his adds, he will make a direct route to his starting point and the adds can bug out.

That happens because adds wait until boss comes near the zone where he evaded. he looks ok from my testing, this is normal behavior.
