### ISSUE TITLE
Exploration achievement not being applied.

### ISSUE THREAD

**Issue by Blindfreak** [Progressive335/Progressive335#382]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Explore Duskwood Achievement.
__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
Duskwood Achievement not being applied

**Current behaviour:**
I have all the zones for Duskwood explored but the achievement is not being applied.

**Steps to reproduce the problem:**
Not sure if it can be.

**How it should work:**
Achievement given after exploring all of Duskwood.

**Any other documentation that could be helpful:**
![WoWScrnShot_111319_044929](https://user-images.githubusercontent.com/57071693/68765334-650ee480-05d1-11ea-9705-deb2b2bdc1cf.jpg)

**Comment by Zooke** [comment]
I love how you have sent Silver the message about the lockouts.

**Comment by Progressive335** [comment]
tried to do this in the test realm and i was able to explore and get the achievement.
