### ISSUE TITLE
Deathgrip not working properly.

### ISSUE THREAD

**Issue by Blindfreak** [Progressive335/Progressive335#383]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Deathgrip.
__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[x] Spell
**Description of the bug:**
Half the time Deathgrip wont work, and doesnt work on Undead targets at all.

**Current behaviour:**
Deathgrip doesn't work half the time. Half the time it will either not pull the target to the DK or the target will get stuck in midair. And Deathgrip doesn't work on Undead targets at all.

**Steps to reproduce the problem:**
Go up to a target and DG them.

**How it should work:**
DG should always pull the target to the DK unless they are rooted in place or a boss target (dungeon boss as well)

**Any other documentation that could be helpful:**
![WoWScrnShot_111319_045624](https://user-images.githubusercontent.com/57071693/68766573-f67f5600-05d3-11ea-81c2-17a6c844c4f5.jpg)

**Comment by LezChap** [comment]
related to #286

**Comment by Progressive335** [comment]
please write on https://github.com/Progressive335/Progressive335/issues/286 rather than opening a new issue ticket
