### ISSUE TITLE
Dire Maul North Bug (low-medium priority)

### ISSUE THREAD

**Issue by NubHashshin** [Progressive335/Progressive335#384]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[x]  NPC
[x] Instance

**Description of the bug:**As a mage ( or maybe other classes aswell ) if you use blastwave in the room left bottom(in the print screen I sent bellow) u can bug NPCs by throwing them in the wall bugging them out making them fly/reset positions and making players leave combat.

**Current behaviour:**just said above

**Steps to reproduce the problem:**above

**How it should work:**Mobs shouldn't go in walls 

**Any other documentation that could be helpful:** I would show you how to reproduce it but I would need an run/tank and heal to do it. https://prnt.sc/pwmgy1 The "room" I was talking about

**Comment by Progressive335** [comment]
https://github.com/Progressive335/Progressive335/issues/342

isn't this related to this issue? sounds generic and not from "dire maul"

**Comment by NubHashshin** [comment]
Im not sure if it can happen to every instance next time Im doing it Im going to record it,

**Comment by NubHashshin** [comment]
https://youtu.be/ZyldjuCTKB4

**Comment by NubHashshin** [comment]
also it can happen upstairs at the door too x)

**Comment by Progressive335** [comment]
that seems too specific and i'm not sure if its even a blizzlike bug ... hum
