### ISSUE TITLE
Blasted Lands rares should drop Dreanethyst item.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#389]
All rares in Blasted Lands should drop one of the 2 items,
https://wotlk.evowow.com/?item=10593
https://wotlk.evowow.com/?item=8244

The spheres are a zone drop to all mobs in Blasted lands with a low % (probably not as low as the 0.01% listed on the database, that does seem a bit scarce, you have more chance of a world drop epic. 1 in 100 for the imperfect and 1 in 250 for the perfect seems a lot more likely, these did drop if you quested the area). however the rares had a 100% chance to drop one of the versions.

Video here is from Cata, but you can see the drop on all the rares.
https://www.youtube.com/watch?v=pbPGv2EXMU0

**Comment by Jparoche** [comment]
Hi Zooke, The one rare I checked was "Grunter" entry 8302. The items are on its loot table;
8244 - with a 1% drop
10593 - with a .45% drop

Do you know all the rares names/could you provide a list and we can validate.

**Comment by Zooke** [comment]
https://wotlk.evowow.com/?npc=8298
https://wotlk.evowow.com/?npc=8301
https://wotlk.evowow.com/?npc=8302
https://wotlk.evowow.com/?npc=8304
https://wotlk.evowow.com/?npc=8303
https://wotlk.evowow.com/?npc=8296
https://wotlk.evowow.com/?npc=8300
https://wotlk.evowow.com/?npc=8299
The items should be 50/50 1 of the 2 should always drop.

**Comment by Jparoche** [comment]
Hi, I think this might of been a change in cata, Any documentation I can find from Classic wowhead or any WOTLK DBs shows the https://classic.wowhead.com/item=10593/imperfect-draenethyst-fragment to have a 7% drop chance on all mobs in Blasted lands and the https://classic.wowhead.com/item=8244/flawless-draenethyst-sphere to have around a .45% drop chance.

If you have a source for the 50/50 chance of one dropping on or before WOTLK please link.

**Comment by Broker-Precision** [comment]
Closing for lack of info
