### ISSUE TITLE
[Raids/SSC] Leotheras - Chaos Blast

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#39]
**Description of the bug:**
Spell chaos blast is not scaling correctly

Inner Demon
About 25 sec into the Demon Form phase, Leotheras summons Inner Demons for up to five raid members (never for the person with aggro). **The inner demons can only be attacked by the person to whom they belong.** **If Leotheras returns to humanoid form while an Inner Demon is still alive, that person becomes Mind Controlled for 10 minutes (non-removable).** Pet classes must make sure their pet does not get the killing blow, the Mind Control is only prevented if the player deals the death blow.

**Comment by Progressive335** [comment]
https://wowwiki.fandom.com/wiki/Leotheras_the_Blind
