### ISSUE TITLE
ZG PTR Test

### ISSUE THREAD

**Issue by Blindfreak** [Progressive335/Progressive335#390]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Zul'Gurub PTR Test

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[X] Raid

**Description of the bug:**
Tested Bat/Snake/Spider/Raptor Boss's. None are working as they should.

**Current behaviour:**

- [x] High Priestess Jeklik/Bat Boss:

Her Blood Seeker Bats that spawn from the cave behind her get stuck on the wall and stay there.
Her Firebomb Bats are coming into melee range and meleing whoever has highest aggro on them, they are untargetable and their fire bombs do not show up on the ground as they should.
Both her Mind Flay and Healing spells are supposed to be interruptable, they currently are not.

- [x] High Priest Venoxis/Snake Boss:

During phase 1, Venoxis is supposed to use both Holy Nova and Holy Wrath (A chain-lightning form of Holy Nova) on Melee if they are in range of him during phase 1.

- [x] High Priestess Mar'li/Spider Boss:

At the start of the fight, the four spider adds are spawning at the back of the room and not on either side of the path leading up to her as they are supposed to. Spider adds are supposed to spawn occasionally but only one at a time. They are currently spawning solo or in groups with only seconds between spawn timers.
Mar'li is not life draining anyone while in humanoid form.
Mar'li is supposed to be tauntable, but is currently immune to it.

- [x] Blood Lord Mandokir/Raptor Boss:

Mandokir is Charging people far too often and often charges back to back. this is NOT supposed to happen.
Mandokir will cast his 'Gaze' far to often. It is supposed to be one cast about every 10-15 secs, he is currently casting 'Gaze' about every 5 secs and often back to back without any time between casts.
The Spirits in the room are not rezzing people when they die, they are in fact doing nothing.

The Hoodoo Piles are not dropping the class Dolls.

**Steps to reproduce the problem:**
Test again on the PTR.

**How it should work:**
Bat Boss:
Firebats for Bat are supposed to fly around the area at the top and throw firebombs in increasing frequency as the fight goes on.
Bloodseeker bats are supposed to make it to the raid.
Her Mind Flay and Healing spell are supposed to be able to be interrupted.

Snake Boss:
Holy Nova and Holy Wrath (Chain Lightning form of his Holy Nova) are supposed to be used by him if there are multiple players in melee range.

Spider Boss:
Drain Life during her humanoid phase, once every 15-30 secs.
She is supposed to be tauntable.
The starting four spider adds should spawn from the spider eggs on either side of the pathway leading up to her. After that, only one spider add at a time is supposed to spawn about every 15-20 secs.

Raptor Boss:
Madokir is only supposed to charge once every 15-20 secs, and his charge is supposed to prioritize players standing alone (if there are no players alone he will charge the group)
His 'Gaze' should only happen once every 10-15 secs.
The Spirits in the room are supposed to rez a random dead player. They are supposed to move slowly (About walking speed).

**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
Minor details about mandokir:
His 'gaze' is currently between 13-15s
His 'charge' is currently between 33-38s and his charge mechanic works on people within 40y

**Comment by Progressive335** [comment]
@Blindfreak
