### ISSUE TITLE
Crudely-written Log item not Dropp

### ISSUE THREAD

**Issue by KrasterK** [Progressive335/Progressive335#393]
The item Crudely-written Log ID = 12842 on the loot table of the mob High Chief Winterfall npc=10738, is not dropping after being killed 20 times  when the drop rate should be high. Thank you for your time

[x] NPC: 10738
[x] Item: 12842 

Depending on the source the drop rate is different but always high

https://classic.wowhead.com/item=12842/crudely-written-log -->Drop rate = 28%
https://wowwiki.fandom.com/wiki/Crudely-written_Log             -->Drop rate = 59%
https://tbc-twinhead.twinstar.cz/?item=12842                            -->Drop rate = 100%

**Comment by Zooke** [comment]
Have you done the quest to kill him ?
From the comments "This seems to only drop after you've done the quest to kill him. At least I've killed him a hundred times before I did the quest and the next time I killed him after doing it, this thing dropped."

**Comment by KrasterK** [comment]
thank you so much ill try it

**Comment by KrasterK** [comment]
Yeah it was necesary to do the previous quest chain
