### ISSUE TITLE
Magisters set D2 questline not available for priests.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#394]
The Magisters set is originally a mage set is usable for priests here on Plaguewood.
However, in an oversight, the quest to upgrade the set is not marked as available to priests.
Please will you flag the quest accordingly.
I want to do all the set questlines together so need this one flagged before I can start.

**Comment by Zooke** [comment]
https://classic.wowhead.com/quest=8907/an-earnest-proposition

**Comment by Jparoche** [comment]
Corrected on next reboot
