### ISSUE TITLE
Priest talent 'Misery' not proccing from Mind Flay

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#395]
Priest talent Misery should proc from Mind Flay, currently it does not.
Misery:
https://wotlk.evowow.com/?spell=33191
https://wotlk.evowow.com/?spell=33192
https://wotlk.evowow.com/?spell=33193
Mind Flay:
https://wotlk.evowow.com/?spell=15407
https://wotlk.evowow.com/?spell=17311
https://wotlk.evowow.com/?spell=17312
https://wotlk.evowow.com/?spell=17313
https://wotlk.evowow.com/?spell=17314
https://wotlk.evowow.com/?spell=18807
https://wotlk.evowow.com/?spell=25387
https://wotlk.evowow.com/?spell=48155
https://wotlk.evowow.com/?spell=48156

Also, having Misery procced on the target from other spells has no effect on the damage of Mind Flay.

**Comment by Progressive335** [comment]
> Also, having Misery procced on the target from other spells has no effect on the damage of Mind Flay.

Tested with and without misery talent and is working correctly. (fixed the proc from mind flay)
