### ISSUE TITLE
RDF can't start normally.

### ISSUE THREAD

**Issue by rick-wild** [Progressive335/Progressive335#398]
**Description of the bug:**
RDF won't work unless 4 or 5 people queue as a group
**Current behaviour:**
^
**Steps to reproduce the problem:**
Queue alone as a tank, you usually have a healer or a dps missing while it's confirmed by other people (in world chat) that there are more than enough people in each role queued to start a dungeon.
**How it should work:**
Recognize the amount of queued players correctly.
**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
that depends on premades, depends with a LOT of situations, is hard to prove that this is a bug.
