### ISSUE TITLE
Elemental Invasion bosses

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#399]
https://wowwiki.fandom.com/wiki/Elemental_Invasions
I have quoted a somewhat fact sparse article, but it does have some information that can be used as a rough guide.
1. The Elemental Invasion was a 1 off, 2 week event. Notable loot and the reason these mobs are killed is the 'Ace of Elementals' and the 4 types of Essences (earth/water/air/fire) that they drop.
2. Bosses spawn time on Plaguewood is 10 minutes instead of what would seem to be considerably longer on retail.

Now, i do have personal thoughts on things like this when it comes to private servers, we want players to experience content that they have probably never seen before, we have the power to make events like this (it's only 4 mini-boss spawns, hardly world changing) a permanent fixture.

I think that's a good thing, however 10 minute spawns is a bit too often and I would suggest a happy medium of 16-24 hours (do we have min/max spawntimes ? If not then it's something that needs to be coded, WoW isn't supposed to be predictable)

This topic also brings into discussion other 1 off events that may or may not be currently implemented, (the scourge invasion event comes to mind with the extra dungeon bosses) there should be a consistant policy applied.
Thoughts ?

**Comment by Progressive335** [comment]
the event trigger is 2 days up 2 days cooldown.
