### ISSUE TITLE
Rare mob Hemathion (Blade edge mountains)

### ISSUE THREAD

**Issue by dreadnought101** [Progressive335/Progressive335#4]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**

**ID of the Spell/NPC:**
npc=18692

**Description of the bug:**
Hemathion is located through the floor of blade edge mountain

**Current behaviour:**

**Steps to reproduce the problem:**
Hes done it twice as far as I have seen, I have killed him once, and a day later he is in same location below ground

**How it should work:**
He should be gliding near the ground roaming between forge camps (fast solution is to keep him stationary)

**Any other documentation that could be helpful:**
Image Links
-Below Ground
https://imgur.com/G1kBr94
-When I pull him up
https://imgur.com/sdh0NpH

**Comment by jQuery69** [comment]
Confirmed

**Comment by jQuery69** [comment]
Fixed
