### ISSUE TITLE
Some issues with shared armor sets.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#400]
Following on from https://github.com/Progressive335/Progressive335/issues/394
The upgraded set is marked mage only https://wotlk.evowow.com/?itemset=517
Also, the next (class defined) quest in the series is unavailable for priests https://classic.wowhead.com/quest=8932/just-compensation

The T1 set https://wotlk.evowow.com/?itemset=201 is also mage only where shadow priests could use it. (I assume the T2 set is also)

**Comment by Jparoche** [comment]
Corrected
