### ISSUE TITLE
Priest threat issue

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#403]
As a priest, If I attack a turkey outside SW in melee, I pull other neutral turkeys.
Hard to elaborate much more, but a guildie druid did not have the same issue.

**Comment by silverech0** [comment]
Are you sure that they aggroing isn't part of their script?

**Comment by Zooke** [comment]
Didin't happen for the guild druid, but i'll try on my druid.

**Comment by Progressive335** [comment]
what spell you using when they aggro? is all spells? please try to notice if any of your auras could be triggering this behavior. for better understanding of the issue.
