### ISSUE TITLE
[Bosses] Dragons of Nightmare

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#409]
- [x] Dragons Of Nightmare I think should spawn on the ledges right outside the portals, look at the photos from 2007 https://classic.wowhead.com/npc=12496/dreamtracker
 
- [x] These sleeping fog clouds seem to move quite fast, and seem to sleep you from some distance away, even continually moving I was unable to avoid them.

- [x] Lethons https://classic.wowhead.com/spell=24811/draw-spirit wasnt healing him, I didnt see a spirit walking towards him either although this was difficult solo.

- [x] Bosses spawntimes

- [x] Make all patrols

**Comment by Zooke** [comment]
From todays fixes, what is left from above is
Pathing the dragon that spawns in Duskwood, he is the only one that roams.
Moving the other 3 bosses to the platforms right outside the portals.
Lethlas, Dreamroarer, Lethon issues as above.
Verifiying the sleeping cloud movement speed.

**Comment by Zooke** [comment]
https://www.youtube.com/watch?v=cheP7oKQdN4
This video, although awful does show us a couple of things
1. The DK is moving backwards and the sleep clouds appear to be the same speed.
2. Ysondre only summons 1 add which makes me believe that she summons 1 add per person fighting.

**Comment by Zooke** [comment]
https://wotlk.evowow.com/?npc=12498
This npc needs moving to the middle platform of the portal.
He is also listed as having 2 of the each of the same ability, This is an error.

**Comment by Zooke** [comment]
https://wotlk.evowow.com/?npc=12476
This npc has the wrong spell, Fairie Fire, it should be Regrowth
Just transfer the data from the PR on the other oracles
-- Verdantine Oracle
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=12478;
DELETE FROM `smart_scripts` WHERE `entryorguid`=12478 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(12478,0,0,0,14,0,100,0,20000,40,15000,20000,11,20664,0,0,0,0,0,7,0,0,0,0,0,0,0,"Verdantine Oracle - Friendly at 20000 HP - Cast 'Rejuvenation'"),
(12478,0,1,0,14,0,100,0,40000,40,20000,25000,11,20665,0,0,0,0,0,7,0,0,0,0,0,0,0,"Verdantine Oracle - Friendly at 40000 HP - Cast 'Regrowth'");

**Comment by Zooke** [comment]
https://wotlk.evowow.com/?npc=5314
Npc is missing spell
https://classic.wowhead.com/spell=20671/summon-phantim-illusion

**Comment by Zooke** [comment]
https://wotlk.evowow.com/?npc=14888
Lethon, I never saw this npc do Shadow Bolt Whirl, maybe this was because I was alone.
https://classic.wowhead.com/spell=24834/shadow-bolt-whirl
