### ISSUE TITLE
eris havenfire

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#410]
https://classic.wowhead.com/npc=14494/eris-havenfire
NPC is supposed to be invisible without Eye of Shadow equipped.

Also, the quest https://classic.wowhead.com/quest=7622/the-balance-of-light-and-shadow
needs scripting properly, it pretty much auto completes.

**Comment by Zooke** [comment]
This might help
https://github.com/TrinityCore/TrinityCore/issues/11961

**Comment by Progressive335** [comment]
@Zooke that's the script we are using right now

**Comment by Zooke** [comment]
https://www.youtube.com/watch?v=1epxP8zfNGI
Seems to be from legit classic
