### ISSUE TITLE
Tome Of Tranquilizing Shot missing text on item description.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#418]
https://wow.gamepedia.com/Tome_of_Tranquilizing_Shot
Currently there is no text in the "Use :" field.
Should probably say 'Teaches Tranquilizing Shot'

**Comment by Progressive335** [comment]
The text comes from a spell description, if that was changed by blizzard there isn't much to do.

**Comment by Progressive335** [comment]
These items were removed from the game. Closing.
