### ISSUE TITLE
A Pawn On The Eternal Board (AQ Questline)

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#429]
https://classic.wowhead.com/quest=8519/a-pawn-on-the-eternal-board#comments
No video, but some photos to go on from 2008

Test server video : https://youtu.be/AY9FGaCM2ws
As you can see, this needs quite a bit of work, i was also able to attack mobs and get aggro.
Seeing as this is supposed to be a vision of a past event, I am going to guess mobs should be unattackable.
The script also fails to complete and gives no credit for the quest.

WotLK retail video
https://www.youtube.com/watch?v=V_wU8PhIIWU

**Comment by Blindfreak** [comment]
ID of the Spell/NPC/Quest:
A Pawn on the Eternal Board

Place an X between the brackets to specify the ID

[X] Quest
[] NPC
[] Quest

Description of the bug:
After Anachronus says 'The sands of time will halt' the 'vision' doesn't continue and the quest will not complete. The dragons also do not fly properly to engage the mobs.

Current behaviour:
The quest is not finishing after the Staghelm seals the gate, nor is the vision ending (The mobs fighting are still visible, they are also able to be attacked and gain aggro on them, this should not be possible)

Steps to reproduce the problem:
Try the quest as is and watch for the duration.

How it should work:
The mobs should not be able to be attacked, and once Staghelm seals the gate the vision should end and the quest complete.

Any other documentation that could be helpful:
![WoWScrnShot_120319_214542](https://user-images.githubusercontent.com/57071693/70117453-63f23580-161a-11ea-9619-b350a22ff72a.jpg)

**Comment by Blindfreak** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/57071693/70117768-14f8d000-161b-11ea-8ec0-53ba08a35eeb.png)

This is the text that should be showing up after Anacrhonus andStaghelm close the gate, after which the quest should complete.

**Comment by Progressive335** [comment]
https://github.com/azerothcore/azerothcore-wotlk/pull/1493

**Comment by Progressive335** [comment]
https://www.youtube.com/watch?v=V_wU8PhIIWU

**Comment by Zooke** [comment]
Great job, that's so much better.
1 last thing I did notice though, the mobs should be unattackable, you can still pull aggro on them.

**Comment by Progressive335** [comment]
yeah i was not able to do that but still i opened a new ticket for the minor issue
https://github.com/Progressive335/Progressive335/issues/457
@Zooke
