### ISSUE TITLE
Sunken Temple (AQ Questline)

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#431]
Having completed https://classic.wowhead.com/quest=8555/the-charge-of-the-dragonflights

https://ibb.co/phqcpRJ
The script to spawn the npc happens twice.
Also note the 2006 photo for positioning and size of the npc. https://classic.wowhead.com/quest=8733/eranikus-tyrant-of-the-dream

Green Scepter Shard
Enter the Temple of Atal'Hakkar to begin this quest. Approach the Shade of Eranikus and Malfurion Stormrage will appear, offering the quest [60] Eranikus, Tyrant of the Dream. You do not need to kill the trolls or drakes surrounding Eranikus to activate Malfurion. Malfurion directs players to Teldrassil to find his agent.

**Comment by Progressive335** [comment]
https://github.com/TrinityCore/TrinityCore/issues/23229
