### ISSUE TITLE
Azuregos does not offer the RP for the Magical Ledger. (AQ Questline)

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#435]
Only Spirit of Azuregos currently offers the RP chat and hands out https://classic.wowhead.com/item=20949/magical-ledger
It should also be noted that Azuregos and Spirit Of Azuregos are both spawned at the same time, this is obviously incorrect.

**Comment by Progressive335** [comment]
according to the comments, only Spirit of Azuregos should be deliver the letter
https://vanillawowdb.com/?quest=8575
