### ISSUE TITLE
A Pawn on the Eternal Board not finishing

### ISSUE THREAD

**Issue by Blindfreak** [Progressive335/Progressive335#439]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
A Pawn on the Eternal Board

__Place an X between the brackets to specify the ID__

[X] Quest
[] NPC
[] Quest

**Description of the bug:**
The quest is not finishing after the Staghelm seals the gate, nor is the vision ending (The mobs fighting are still visiable, they are also able to be attacked and gain aggro on them, this should not be possible)

**Current behaviour:**
The quest is not finishing after the Staghelm seals the gate, nor is the vision ending (The mobs fighting are still visiable, they are also able to be attacked and gain aggro on them, this should not be possible)

**Steps to reproduce the problem:**
Try the quest as is and watch for the duration.

**How it should work:**
The mobs should not be able to be attacked, and once Staghelm seals the gate the vision should end and the quest complete.

**Any other documentation that could be helpful:**
![WoWScrnShot_120319_214542](https://user-images.githubusercontent.com/57071693/70116237-ef69c780-1616-11ea-8365-5ac7d3808efa.jpg)

**Comment by Progressive335** [comment]
please add to the original report.
https://github.com/Progressive335/Progressive335/issues/429
