### ISSUE TITLE
Death Grip Still Bugged

### ISSUE THREAD

**Issue by Blindfreak** [Progressive335/Progressive335#440]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Death Grip

__Place an X between the brackets to specify the ID__

[X] Spell
[] NPC
[] Quest

**Description of the bug:**
Death Grip almost never actually pulls the target to the player, and it never works on undead targets as well as getting mobs stuck in midair a lot of the time.

**Current behaviour:**
The mobs must be in combat first for Death Grip to actually pull them to the target, a lot of the time mobs will get stuck midair, and undead targets are never pulled.

**Steps to reproduce the problem:**
Use Death Grip, especially in low ceilinged area's. 

**How it should work:**
Death Grip should pull the target (minus some targets like raid boss's and such) to the player.

In retail the arc of the grip itself was set fairly high which looks to be a problem here. A good 
example of how to fix it is how Sunwell does it. They have the arc very low to the ground and have sped the pull up tremendously, this ensures the spell does not stick the target in midair and the target reaches the DK fast.

**Any other documentation that could be helpful:**
![WoWScrnShot_120319_215532](https://user-images.githubusercontent.com/57071693/70116520-d1509700-1617-11ea-9c97-3d81bf146b6c.jpg)

**Comment by Progressive335** [comment]
https://github.com/Progressive335/Progressive335/issues/286

please add to the original report only.
