### ISSUE TITLE
Decoy! (AQ Questline)

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#442]
https://classic.wowhead.com/npc=15554/number-two#comments
Check the Beast Lore on the pic (1.12) note the slight nerf to hp from 1.11.2, (you choose which 1 you'd like)
http://i100.photobucket.com/albums/m14/Vladinator/number_two.jpg
1587-2105 damage, 3622 armor, 78600 health (1.11.2)

Number Two currently hits for 47-63 and his attack speed is pretty damned fast lol

I am guessing that you should have to use the provided item https://classic.wowhead.com/item=21039/narains-turban to be able to place the bag on the floor and summon the boss. Currently you can do it without.

"After dropping off the gold, Dr. Weavil arrives, realizes the trap, and sends Number Two, his ape pet, to attack you. Weavil escapes." I'll look for a video but iirc he flys in on his plane hovers for a while, does some RP then flys off before the ape spawns. I'll try to find a video.

Number Two currently spawns right next to the place you drop the money bag and spawns immediately, this isn't right, no video proof but iirc he spawns down the path out of sight and comes running up the path to the drop point.

He only dropped 2c, maybe this is right, but considering his place in such an epic questline he could possibly be given an appropriate loot table.

**Comment by Progressive335** [comment]
https://youtu.be/7ag6xbC_Yrk?t=315

this?
