### ISSUE TITLE
Field Marshall Snowfall (AQ War Effort progress chat)

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#446]
https://classic.wowhead.com/npc=15701/field-marshal-snowfall
This npc should offer dialog for all the war effort supply quest items, giving the status of each hand-in.
It might also be noted that in the 2007 photo he is mounted.

https://wow.gamepedia.com/Gates_of_Ahn%27Qiraj
An NPC for the opposite faction (General Zog in Ironforge, Commander Stronghammer in Orgrimmar) that could tell you about progress on that side.

**Comment by Progressive335** [comment]
well, there is the .aqstatus command for that, we may not use that since it's a long list on a single npc.

**Comment by Zooke** [comment]
https://youtu.be/4D5LCwAsFJw?t=220
Video showing npc dialog, is it from retail ? who knows.

**Comment by Progressive335** [comment]
added a better info menu
