### ISSUE TITLE
Dancing Rune Weapon does to much damage and does not copy Heart STrike

### ISSUE THREAD

**Issue by Riiion** [Progressive335/Progressive335#447]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**Dancing Rune Weapon 49028:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
Dancing Rune Weapon does not copy all the spells The DeathKnight uses, it specifically does not copy Heart Strike (55050) and other spells do to much dmg (Plague Strike and Blood Strike) about 500% of the dmg they should do. Plague Strike and Blood Strike hit for 2-3k. Icy Touch is doing normal damage tho.
**Current behaviour:**
as stated above
**Steps to reproduce the problem:**
Summoned the Dancing Rnne Weapon against dummies in SW and uise Heart Strike Blood Strike, Icy Touch and Plague Strike
**How it should work:**
Dancing Rune Weapon should copy all the spells the dk uses and do 50% damage with them. 
**Any other documentation that could be helpful:**
Attached screenshots for the damage of Plague Strike and Blood Strike. Recount does not show Heart STrike even tho it was used twice.
![WoWScrnShot_120419_172428](https://user-images.githubusercontent.com/58523786/70160580-0661f580-16bb-11ea-8a29-76634065ab62.jpg)
![WoWScrnShot_120419_172433](https://user-images.githubusercontent.com/58523786/70160585-07932280-16bb-11ea-8d6a-8744a4d7ebc3.jpg)

**Comment by Progressive335** [comment]
![image](https://user-images.githubusercontent.com/44980177/71635615-fe479800-2c1d-11ea-8838-16c36e996bbc.png)
![image](https://user-images.githubusercontent.com/44980177/71635620-06073c80-2c1e-11ea-919e-ef8d1c68b6bf.png)
![image](https://user-images.githubusercontent.com/44980177/71635624-0d2e4a80-2c1e-11ea-9e19-e7485cdb9e97.png)
![image](https://user-images.githubusercontent.com/44980177/71635632-191a0c80-2c1e-11ea-8c7c-569cafedcaaa.png)

added heart strike ability + fixed damage output (according to my combat log)
