### ISSUE TITLE
Chromaggus

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#454]
https://classic.wowhead.com/npc=14020/chromaggus
https://www.tentonhammer.com/guides/blackwing-lair-guide-7-25-06-page-seven.amp
Some details are not consistent between guides, I have used common sense and game knowledge to decide.

Here is a 2006 video, quality is not great but theres plenty to be learnt.
https://www.youtube.com/watch?v=hxS2wQjCvKo
The video is not in real time
At 1:10 he gets the bandaging debuff which we know is 1 minute, that wears off at 1:40 so we can deduce that the video is running at 2x
Notes: (Timings have been adjusted as per above)

Bronze Affliction: Raid wide unavoidable as all afflictions
At 2:41 the player gets Bronze Affliction which he doesn't dispel indicating sands were limited. Remember, this is one of his random abilities so it is not guaranteed to happen every fight. Normally only the tank, o/t and healers would use them.
Around 6s later it procs
It then takes 1m for the next proc (I'm going to guess that this is a hard coded maximum)
The next 2 procs are immediate with a maximum 2s gap
The last proc is then 34s later
From this small amount of data, we can say that the debuff has a 2s cd and can proc at anytime after that up to the 1m max, a 2s proc check seems likely with what I would guess is a 5% chance (this could be very lenient but I am basing it on 20x5 =100% when with a 2s check there are 30 checks)

Breaths: Raid wide avoided by LoS
Frostburn: Manaburn with 5k frost damage (roughly). 70% movement reduction for 5 seconds.
Corrosive Acid: 875-1125 nature damage every 3 seconds for 15 seconds plus 3938-5062 armor reduction for 15 seconds.
Time Lapse: reduces health by 50% stuns for 6s and permanently reduces threat (This was altered at some point, the threat reduction was made into a temporary threat wipe and restored after the stun). Note watching the video we can see that after the time lapse, affected players hp is restored to full.
Ignite Flesh: 657-843 fire damage every 3 seconds for 60 seconds
Incinerate: 3500-4700 fire damage negated by resists.

The players in the video deliberately get the Time Lapse Affliction to reduce their threat (note the o/t standing in LoS ready to pick up the boss, and some healers) but run to the LoS spot for the Red Incinerate breath
The breaths have a 1m cd, they are staggered 30s apart to give a breath every 30s

He uses Frenzy which hunters must dispel using tranquilizing shot (guessing it's a similar or the same spell as Magdamar in MC). He uses this a lot, watch the start of the video, its easy to spot with his size and the flame graphic on his horns. It appears to be on a 15s cd, it seems likely this can have some variation though otherwise it would be a predictable shot in a hunter rotation.
There seems to be a countdown timer for its duration which looks like about 8s

At 20% he uses an Enrage until dead. This enrage is not exclusive and all other abilities continue as normal.

Shimmer:
Chromaggus' skin can "shimmer", changing his vulnerability to a particular school of magic. He will also become more resistant to other schools.

Afflictions: These are all different schools of magic and it makes sense that they can be resisted by the player. Note on the video that sometimes the player does not seem affected by the curse when others do.

**Comment by Progressive335** [comment]
From this fight we must account on the factor that the Afflictions are being casted every 10s , this was originally for 40man, so, if we are doing this a 25man raid, maybe the Affliction cast should be around every 20s

**Comment by Progressive335** [comment]
Tested all the spells, they work as described.
Fixed minor issues with damage outputs.
