### ISSUE TITLE
[Quests] Test Flight: Ruuan Weald 

### ISSUE THREAD

**Issue by jQuery69** [Progressive335/Progressive335#46]
Test Flight: Ruuan Weald

**Comment by silverech0** [comment]
![image](https://user-images.githubusercontent.com/44980456/49106665-a94b8c80-f27b-11e8-95d3-b0ddef869c98.png)
works.

**Comment by silverech0** [comment]
followed this video:
https://www.youtube.com/watch?v=O7f61WsQjp8
