### ISSUE TITLE
Righteous Vengeance

### ISSUE THREAD

**Issue by Rorhn** [Progressive335/Progressive335#462]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
53382
__Place an X between the brackets to specify the ID__

[] Quest
[X] NPC (any)
[] Quest

**Description of the bug:**
Righteous Vengeance damage is too low.
**Current behaviour:**
Currently Righteous Vengeance doesn't deal an additional 30% of the damage over 8 seconds, it deals slightly less. Roughly ~28.4%
**Steps to reproduce the problem:**
Crit any of Judgement, Crusader Strike, or Divine Storm and see that the additional damage over 4 ticks is less than 30% of the original strike's damage.
**How it should work:**
When you crit one of those abilities a debuff should be applied to the target which ticks 4 times (every 2 seconds) dealing 7.5% of the crit's damage again. Additionally, Righteous Vengeance should function like Ignite in that it has a rolling additive effect where if there is still time left on the debuff and a new crit takes place, the new crits damage should be added and the debuff should refresh, however the initial crit should still only benefit the proc 4x.
**Any other documentation that could be helpful:**
EX: Simple
0s: Judgement crit for 1000
2s: Righteous Vengeance tick for 75
4s: Righteous Vengeance tick for 75
6s: Righteous Vengeance tick for 75
8s: Righteous Vengeance tick for 75 and fades.

EX: Detailed
0s: Judgement crit for 1000
2s: Righteous Vengeance tick for 75
4s: Righteous Vengeance tick for 75
4s: Divine Storm crit for 1000
4s: Righteous Vengeance timer reset
6s: Righteous Vengeance tick for 150 (75 from Judgement and 75 from Divine Storm)
8s: Righteous Vengeance tick for 150 (75 from Judgement and 75 from Divine Storm)
10: Righteous Vengeance tick for 75 (Judgement damage has been granted)

https://gyazo.com/49b2f8c9ed1affafd5d34758d4506ca8
https://gyazo.com/571f598e136a734239b99c5d769e8468
https://wowwiki.fandom.com/wiki/Righteous_Vengeance_(removed_retribution_talent)
https://www.wowhead.com/forums&topic=140550

If anything is unclear or you have any concerns/questions please reach out to me via discord if thats a possibility. @jaylen#0300 I just don't use github very often and don't want to miss you.

**Comment by Rorhn** [comment]
Note that on the wowwiki page it has an example like the one I provide however the guy who wrote it must've not been paying attention and considered it doing 40% extra damage instead of 30%. Though the concept remains unchanged.

**Comment by Zooke** [comment]
Have you considered that the % damage discrepency may be due to balance changes 
https://discordapp.com/channels/385247997023354880/648229145368592390

**Comment by Rorhn** [comment]
> Have you considered that the % damage discrepency may be due to balance changes
> https://discordapp.com/channels/385247997023354880/648229145368592390

Thats interesting, no I hadn't. But that would explain it. I don't know if that's intended though because then the nerf sort of double applies to crits. I'll speak with Silver and if necessary remove that part of the report. Thanks for the input.

**Comment by Progressive335** [comment]
> > Have you considered that the % damage discrepency may be due to balance changes
> > https://discordapp.com/channels/385247997023354880/648229145368592390
> 
> Thats interesting, no I hadn't. But that would explain it. I don't know if that's intended though because then the nerf sort of double applies to crits. I'll speak with Silver and if necessary remove that part of the report. Thanks for the input.

was this tested outside? if it was, then there is a reduction indeed.

**Comment by Rorhn** [comment]
> > > Have you considered that the % damage discrepency may be due to balance changes
> > > https://discordapp.com/channels/385247997023354880/648229145368592390
> > 
> > 
> > Thats interesting, no I hadn't. But that would explain it. I don't know if that's intended though because then the nerf sort of double applies to crits. I'll speak with Silver and if necessary remove that part of the report. Thanks for the input.
> 
> was this tested outside? if it was, then there is a reduction indeed.

Yes it was, the screenshots linked in the original report were on an Orgrimmar training dummy

**Comment by Progressive335** [comment]
![image](https://user-images.githubusercontent.com/44980177/72229640-0bfb0700-35a8-11ea-978b-3bbf765d0231.png)
![image](https://user-images.githubusercontent.com/44980177/72229649-23d28b00-35a8-11ea-94ee-c8f1a495ba2d.png)
it seems that is refreshing.

**Comment by Rorhn** [comment]
It was refreshing properly before, just not adding damage together properly.

**Comment by Progressive335** [comment]
closing this. reported as working.
