### ISSUE TITLE
Warlock Demonic Pact

### ISSUE THREAD

**Issue by Nsnugget** [Progressive335/Progressive335#465]
Demonic pact spell=47240

When pet crits it should increase spell power for all party/raid by 10% of mine (542 so should be 54)

Currently only increases by 10 (2% so it is acting like I have 1/5 talents not 5/5)

Copy locksquarius and another char to PTR, send them to the dummy in org and when the effect procs look at the OTHER chars spell power only go up by 10 instead of 54.

Everyones should go up by 10% not 2%

Screesnhots provided
![desqu with NO BUFF 377](https://user-images.githubusercontent.com/55918939/70390656-0f90e200-199b-11ea-81d8-74df5c233e83.PNG)
![withbuff387](https://user-images.githubusercontent.com/55918939/70390657-128bd280-199b-11ea-9587-b80f105309a8.PNG)

![locksquar demo with sp](https://user-images.githubusercontent.com/55918939/70390644-d6587200-199a-11ea-9b04-5378f041be92.PNG)

**Comment by Zooke** [comment]
All that spell power makes me think warlocks need a balance nerf :)
Thanks for bringing it to my attention.

**Comment by Psychh** [comment]
bump, still not working 5/5 talents only give 2% instead of 10%
https://wotlk.evowow.com/?spell=47240
