### ISSUE TITLE
ZG class Enchants

### ISSUE THREAD

**Issue by Blindfreak** [Progressive335/Progressive335#466]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Zanza the Restless
__Place an X between the brackets to specify the ID__

[] Quest
[x] NPC
[] Quest

**Description of the bug:**
ZG Class Enchants not currently available on Zanza the Restless

**Current behaviour:**
Only Savage Guard head enchants available

**Steps to reproduce the problem:**
talk to the NPC once friendly with Zadalar Tribe

**How it should work:**
Once you reach friendly with Zandalar Tribe you should be able to turn in a Punctured Voodoo Doll
of  your class and a Primal Hakkari Idol for your class Head/Leg enchant. The Enchants are not currently available on Zanza the Restless.

**Any other documentation that could be helpful:**
![Screenshot (2)](https://user-images.githubusercontent.com/57071693/70391021-3d6b2c00-1985-11ea-900e-d6b92c9b72a5.png)

**Comment by Zooke** [comment]
I was able to get head / leg enchants at friendly and nature resistance encahnt at honored.
Are you telling us no-one in your guild can get these enchants ?

**Comment by Zooke** [comment]
Add DK class to
https://classic.wowhead.com/item=19717/primal-hakkari-armsplint
https://classic.wowhead.com/item=19719/primal-hakkari-girdle
https://classic.wowhead.com/item=19723/primal-hakkari-kossack
https://classic.wowhead.com/quest=8184/presence-of-might
https://classic.wowhead.com/quest=8058/paragons-of-power-the-vindicators-armguards
https://classic.wowhead.com/quest=8078/paragons-of-power-the-vindicators-belt
https://classic.wowhead.com/quest=8079/paragons-of-power-the-vindicators-breastplate
https://classic.wowhead.com/quest=8041/strength-of-mount-mugamba
https://classic.wowhead.com/item=19574
https://classic.wowhead.com/quest=8042/strength-of-mount-mugamba
https://classic.wowhead.com/item=19575
https://classic.wowhead.com/quest=8043/strength-of-mount-mugamba
https://classic.wowhead.com/item=19576
https://classic.wowhead.com/quest=8044/the-rage-of-mugamba
https://classic.wowhead.com/item=19577

Hopefully that's all of them for DK's.

**Comment by Blindfreak** [comment]
My DK was the only one with a Primal Hakkari Idol so it could very well be that it just doesn't show up for DK's.

**Comment by ShadowVariable** [comment]
Checked on my mage today which was honored and only saw the nature resist enchants.
