### ISSUE TITLE
Nightmare Dragon World Boss Pathing Issues

### ISSUE THREAD

**Issue by Blindfreak** [Progressive335/Progressive335#467]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Nightmare Dragon World Boss's.
__Place an X between the brackets to specify the ID__

[] Quest
[x] NPC
[] Quest

**Description of the bug:**
The Pathing at Seradine in the Hinterlands, Bough Shadow in Ashenvale and Dream Bough in Feralas are all not working properly.

**Current behaviour:**
The Pathing at Seradine in the Hinterlands, Bough Shadow in Ashenvale and Dream Bough in Feralas are all not working properly. The World Boss Dragons (Taerar, Lethon and Ysondre  this week) currently at the locations (Lethon in Seradine is dead)  cannot be brought off the ramps to the ground where they are supposed to be fought. They keep resetting and/or dropping aggro before getting to the ground.

**Steps to reproduce the problem:**
Fight the dragons as is.

**How it should work:**
The Dragons should be able to be dragged down to the ground so that players can fight them without having to clump on the ramps.

**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
that's already fixed, check #changelog. it's not applied to the main realm yet.
