### ISSUE TITLE
BWL trash mobs

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#470]
Only certain mobs in BWL are known for BoE epics, 1% is purely guessing. Currently mobs have such ridiculously high rates it makes me wonder how it's never been reported and adjusted before.
All BWL trash seems to have a 'stock' melee damage which clearly is not correct, but with no proper data to go on there seems no point adjusting any of them.
All BWL trash immunities will need correcting once data becomes available
A general note on trash respawns and the ingots we discussed some time ago from 2011 https://us.battle.net/forums/en/wow/topic/3840664371
A lot of stuff here that makes our BWL sound like a different instance, but lacks offical spells id's https://www.theamazonbasin.com/wiki/index.php/Blackwing_Lair Most of this is NOT included in my review because it's a redesign of so many packs of mobs.

- [x] The 6 adds surrounding Vaelastrasz can be pulled separately (1's, 2's etc). 

Death Talon Seether https://wotlk.evowow.com/?npc=12464
- [ ] https://wotlk.evowow.com/?spell=22433 doesn't add +1000 a stack damage as it says
- [x] Epic drops need rates adjusting to 1%

Death Talon Flamescales https://wotlk.evowow.com/?npc=12463
- [x] https://wotlk.evowow.com/?spell=22423 casts this a lot, probably too much unless it is directed at random targets in which case it's fine. I was unable to test that.
- [x] Epic drops need rates adjusting to 1%

Death Talon Captain https://wotlk.evowow.com/?npc=12467
- [x] https://wotlk.evowow.com/?spell=22438 This is the wrong spell, it's also currently undispellable (magic)
https://wowwiki.fandom.com/wiki/Death_Talon_Pack "The Mark of Detonation is a debuff cast on someone randomly in the raid, which explodes to hit everyone around the target for decent damage. This needs to be dispelled."
- [x] He isn't casting https://wotlk.evowow.com/?spell=22436 "This aura affects all the death talons within range"
- [x] He isn't casting https://wotlk.evowow.com/?spell=22440 which he should probably do every so often to break mobs out of cc
- [x] Epic drops need rates adjusting to 1%

Death Talon Hatcher https://wotlk.evowow.com/?npc=12468
- [x] https://wotlk.evowow.com/?spell=22442 does lower than stated damage

Blackwing Guardsman https://wotlk.evowow.com/?npc=14456
- [x] Only does melee and 'Strike'. Oddly this npc is listed as having 2 enhanced melee abilities which seems out of place. Lets remove 'Strike' and keep 'Dragonbane'
- [x] He isn't casting either 'Dragonbane' or 'Cleave'

Grethok the Controller https://wotlk.evowow.com/?npc=12557
- [x] Mob starts meleeing which he shouldn't do, he's a caster with MC, Poly and Arcane Missiles. he should stand there chain casting these.
- [x] His 'Arcane Missiles' doesn't work properly and only hits for 1 tick
- [x] He has 'Slow' which he should no doubt cast on himself immediately and look to refresh it when it ends. Currently he isn't casting it at all.

- [x] The above mobs (Grethok + 2 Guardsmen) respawn after Razorgore has been killed. They shouldn't do this.

Hourglass Sand https://wotlk.evowow.com/?item=19183
- [x] Now that Chromaggus has been fixed, Hourglass sand drops should be returned to normal as they trivialise the debuff if everyone has a stack each. 50% rate on a single sand until we get genuine info ?

Blackwing Technician https://wotlk.evowow.com/?npc=13996
- [x] https://wotlk.evowow.com/?spell=22335 does less damage than stated

Blackwing Spellbinder https://wotlk.evowow.com/?npc=12457
- [x] NPC should probably not melee unless out of mana and chain cast his 2 abilities at random raid members instead.
- [x] Epic drops need rates adjusting to 1%

Death Talon Overseer https://wotlk.evowow.com/?npc=12461
- [x] Epic drops need rates adjusting to 1%

**Comment by Progressive335** [comment]
https://www.youtube.com/watch?v=_1SlQ7rvS74
