### ISSUE TITLE
The Great Masquerade completes but messy scripting.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#472]
https://classic.wowhead.com/quest=6403/the-great-masquerade
Marshall Windsors pathing all the way is scruffy.
At the start where he talks to the General, some of the guards are spawned twice in the same spot.
At the end when he walks towards the King, he turns back 3/4 way up and goes back to the castle entrance where the script continues as if he were standing next to the King.

**Comment by Progressive335** [comment]
script was working fine at launch, for some reason is bugging now.
