### ISSUE TITLE
Gurubashi Arena event

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#477]
https://classic.wowhead.com/npc=14508/short-john-mithril

The event should take place at 12/3/6/9 etc, ours is 1hr early.

I suspect there is a rogue entry in the database for a 2nd chest making it spawn independently of the event as the chest spawns at other times too. Using GM mode you can see the 2 chests spawned at slightly different coords.

There is a missing graphical effect when opening the chest as seen on this video https://www.youtube.com/watch?time_continue=37&v=MaOIv7bZ6RU
This was added in 1.9 "The Short John Mithril's chest in Stranglethorn Arena will now display an effect when it is being opened so its harder to open the chest unnoticed. "

It should take 10s to open the chest, ours is currently 8s.

When he has placed the chest, the npc is suppose to run back to his starting point, not walk.

**Comment by Progressive335** [comment]
fixed
