### ISSUE TITLE
Essence of the Red does not give runic power to DKs

### ISSUE THREAD

**Issue by Nubenai** [Progressive335/Progressive335#478]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:** https://classic.wowhead.com/spell=23513/essence-of-the-red

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[X] Spell

**Description of the bug:**
https://classic.wowhead.com/spell=23513/essence-of-the-red does not give runic power to DKS
**Current behaviour:**
https://classic.wowhead.com/spell=23513/essence-of-the-red does not give runic power
**Steps to reproduce the problem:**
fight the boss who gives the buff
**How it should work:**
https://classic.wowhead.com/spell=23513/essence-of-the-red should give DKs runic power
**Any other documentation that could be helpful:**

**Comment by Nubenai** [comment]
Closed accidentally, was going to write a comment. This was tested over multiple attempts at the boss, it does not give runic power at all, I waited 20 seconds at one time and gained nothing over the course of the fight.

**Comment by Progressive335** [comment]
hm, where it's said it should give runic power?

**Comment by Nubenai** [comment]
The tooltip of the debuff when fighting the boss says it should give 20 runic power per second.
