### ISSUE TITLE
Rage generation

### ISSUE THREAD

**Issue by rick-wild** [Progressive335/Progressive335#482]
The way rage is being generated does not at all agree with any of the formulas I could find for wotlk on the internet. Those include:
https://vanilla-wow.fandom.com/wiki/Rage
https://wowwiki.fandom.com/wiki/Rage
https://project-ascension.com/forum/index.php?/topic/551-a-thought-on-ascensions-rage-generation/
https://sunwell-community.com/index.php?/topic/5161-warrior-protection-guide-elitistjerks/ (rage generation section)

![hits1](https://user-images.githubusercontent.com/57038931/70993709-39ea4a00-20d5-11ea-93a2-a217c17f59cb.png)
Taking this example, where I start attacking the mob out of combat at 0 rage, 3 swings of
290 /normal/ mh
376 /crit/ oh
588 /crit/ mh
should generate respectively
conversion_value=230.6
mh_crit_factor=7.0
oh_crit_factor=3.5
mh_normal_factor=3.5
oh_normal_factor=1.75
speed=3.40 #(wielding 2xhttps://classic.wowhead.com/item=18822/obsidian-edged-blade)

((15*(290)/(conversion_value)+(mh_normal_factor)*(speed))/2) = 15.38

((15*(376)/(conversion_value)+(oh_crit_factor)*(speed))/2) = 18.17

((15*(588)/(conversion_value)+(mh_crit_factor)*(speed))/2) = 31.02

Total: 64.57 rage
while I only have 37 (+3 from unbridled wrath) in the screenshot.

**Comment by Progressive335** [comment]
are you sure those formulas are from WOTLK? i can't be sure of that. also, our core is TC based, i looked all over the place for an rage issue there, the last one reported was from 2011
https://github.com/TrinityCore/TrinityCore/issues/2696
i wonder if this is really bugged, first link belongs to vanilla, which isn't really our case, the second don't specify anywere that is WOTLK related, the others, i can't really relate since they are also private servers and i can't know if they changed the formula somewhere.

**Comment by rick-wild** [comment]
At https://wowwiki.fandom.com/wiki/Rage, the rage conversion value table goes up to only level 80, which obviously hints at wotlk. In general, the information and formulas written on the wowwiki specifically concern pre-cata expansions, mostly wotlk.
https://sunwell-community.com/index.php?/topic/5161-warrior-protection-guide-elitistjerks/ is a repost from elitist jerks, which I believe should be a credible enough source, even though it's about TBC.
Here is also a blue post from vanilla https://forum.elysium-project.org/topic/22647-rage-explained-by-blizzard/, the formula hasn't changed that much since then apparently.

**Comment by Progressive335** [comment]
https://github.com/TrinityCore/TrinityCore/issues/2327

another issue that could relate this. still, they never took it seriously.,.

**Comment by rick-wild** [comment]
Yup these formulas check out with the reality of the server. This is why warriors are severely gimped. Prot has the worst tps of all tanks and fury is flat out unplayable.

**Comment by Progressive335** [comment]
i wouldn't say unplayable, actually the rage rate is 2x currently. there were many warriors that played in this server in the last few years and didn't complain about rage while pulling great dps...

**Comment by rick-wild** [comment]
I don't think there's any place to doubt that the formula is wrong, provided blizzard themselves have provided it (https://forum.elysium-project.org/topic/22647-rage-explained-by-blizzard/). Where exactly is the guarantee that the TC formula is any more accurate than this?
If current rage generation is actually multiplied by 2 there is no way the base rage generation is even remotely correct.  A proper fury rotation in wotlk would have your core abilities (bt and ww) constantly on cooldown while leaving rage to be dumped into heroic strike in contrast with casting a single BT before you have to wait for another mh+oh auto attack to generate barely 20 rage for the next BT leaving WW completely out of the rotation.

**Comment by Progressive335** [comment]
the rage itself is way more than a simple formula, also counts the gear you have on and many more variables than that. that is a forum topic from other private server...

**Comment by rick-wild** [comment]
> that is a forum topic from other private server...
Did you even bother to read what I linked? There's a reference to an actual blizzard post from the official forums. https://web.archive.org/web/20071012151506/http://forums.wow-europe.com/thread.html?topicId=83678537&pageNo=1&sid=1
If you won't take this as proof there is literally no convincing you.

>the rage itself is way more than a simple formula, also counts the gear you have on and many more variables than that.
Can you provide proof for that? It sounds like complete fanfiction. 
So far the only function responsible for generating rage I'm finding in trinity core is at https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Entities/Unit/Unit.cpp, line 12780, I don't see armor being a factor there. 
Do you mind maybe posting the function here so we can confirm for ourselves that plaguewood is using this exact same function? 

>The formulas that i saw basically describe what is in the core, that explains why TC never changed, because feels correct. their formula is there since 2010 and still the same in 2019 where many other pservers use it.
As far as I know, sunwell for example use trinity core as well, and I've never had any problems with rage there.

**Comment by Progressive335** [comment]
that's the same formula, and it's the same used by all pservers. 
you're probably not accounting lvl 60 and many other things. 
yes, if you have better gear, you deal more damage, if you deal more damage, you gain more rage, i don't have all the info now to explain to you based on code on where you can gain rage, **this never have been an issue before** that's why i'm wondering that you may have been doing your calcs wrong.
Please note that forum topic from blizzard is from 2006, WOTLK release was in 2010, formulas are different.

**Comment by rick-wild** [comment]
> Please note that forum topic from blizzard is from 2006, WOTLK release was in 2010, formulas are different.

The formula might be from 2006, but it accounts for crits, something I can't see in the TC code. If you think it's fair to balance rage as if this were vanilla, it's a different matter. Also, do you think it's fair to calculate the rage after the damage reduction given the state of many other classes?

**Comment by Progressive335** [comment]
> > Please note that forum topic from blizzard is from 2006, WOTLK release was in 2010, formulas are different.
> 
> The formula might be from 2006, but it accounts for crits, something I can't see in the TC code. If you think it's fair to balance rage as if this were vanilla, it's a different matter. Also, do you think it's fair to calculate the rage after the damage reduction given the state of many other classes?

all classes have damage reductions, they all suffer the same reduction, wouldn't be fair to boost rage with that. also, i don't think warriors are performing bad in terms of dps.

**Comment by rick-wild** [comment]
Yeah I guess ferals are good too, we can close this issue.

**Comment by Progressive335** [comment]
> Yeah I guess ferals are good too, we can close this issue.

what that has to with this?
