### ISSUE TITLE
Darkmoone Faire Setup event timing wrong

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#490]
Earlier this week I saw the Darkmoone Faire setup event, however today (Saturday) the area is empty.
The 2 events need to be sychronized.

**Comment by Progressive335** [comment]
never heard that a setup of darkmoon fair exists. the darkmoon faire even spawns at sunday

**Comment by Zooke** [comment]
Yeah, theres a setup event where there are some fairground carts spawned and some workers and npc's telling you DMF is coming soon.
The event must be listed in the database, but if I remember I will tell you when it's active on live.
