### ISSUE TITLE
Improved Devouring Plague talents not increasing damage by 5%/10%/15% when base Spell power is 0

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#496]
https://wotlk.evowow.com/?search=improved+devouring+plague
1/2 the spell works, it does do the initial damage hit as stated.
However it does not increase damage done by 5%/10%/15% as it should.

**Comment by Progressive335** [comment]
![image](https://user-images.githubusercontent.com/44980177/71473218-0a6ec800-27ce-11ea-8f72-a2b86c63bd06.png)
without talent
![image](https://user-images.githubusercontent.com/44980177/71473241-1f4b5b80-27ce-11ea-9e10-5c710b4397a1.png)
with talent

**Comment by Zooke** [comment]
https://www.youtube.com/watch?v=YHUtu1X72a8

**Comment by Zooke** [comment]
Improved Devouring Plague Rank 3
"**INCREASES THE PERIODIC DAMAGE**" done by your Devouring Plague by 15%, and when you cast Devouring Plague you instantly deal damage equal to 30% of its total periodic effect.

I fail to see how this is not clear, please explain how you come to the conclusion that this talent does not increase periodic damage.

**Comment by Progressive335** [comment]
my conclusion is that the talent is currently increasing the periodic damage, the prints i posted are damage that comes from periodic ticks.

**Comment by Zooke** [comment]
Ok, so we have solved this.
Currently the damage increase only calculates from bonus SP. It fails to take into consideration base SP.
This is minor as the increased damage from that is negligible.
Although still technically a bug, this can be considered to be irrelevant in a non testing environment.
Up to you whether you want to consider this closed.

**Comment by Progressive335** [comment]
i will place in low priority, is still bug but wont affect much players.
