### ISSUE TITLE
suggestion / enhancement

### ISSUE THREAD

**Issue by Fudgehog97** [Progressive335/Progressive335#498]
More staffs at the Visionweaver <Secret Artifacts> vendor for transmog.

**Comment by Progressive335** [comment]
Check this
https://www.youtube.com/watch?v=KLjzE9TObsQ
and this
https://www.youtube.com/watch?v=Sw4rau1itMA

tell me what models you like most.

**Comment by Fudgehog97** [comment]
Not so many staves in the videos.
Maybe some of these?

https://www.wowhead.com/item=30883/pillar-of-ferocity
https://www.wowhead.com/item=47302/twins-pact
https://www.wowhead.com/item=28633/staff-of-infinite-mysteries
https://www.wowhead.com/item=54806/frostscythe-of-lord-ahune#comments
