### ISSUE TITLE
Item missing from bags

### ISSUE THREAD

**Issue by Sagitar-g** [Progressive335/Progressive335#502]
https://wotlk.evowow.com/?item=18878

Description of the bug:
 - Item 18878 disappeared/destroyed while I wasn’t online. 

Current behaviour:
 - The item still show up as part of my caster item set on the “Outfitter” addon. I believe my bags were full and as I tried to logon, the addon likely attempted to equip my caster set but was unable to due to full bags. My Offhand was somehow recovered but the weapon was not.

**Comment by Progressive335** [comment]
sorry, theres nothing unusual in our system to provide proof there is any issue with items. I recommend you to change your password for better security.
