### ISSUE TITLE
[AQ20] Corrections

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#504]
- [x] Moam is missing spells. https://wowwiki.fandom.com/wiki/Moam

- [x] Ayamiss the Hunter missing spells/logic. https://wowwiki.fandom.com/wiki/Ayamiss_the_Hunter

- [x] Buru the gorger 

- [x] Improve General Andorov fight

- [x] Remove book drops that are worth 10g

- [x] Check boss spawns/saves

**Comment by Zooke** [comment]
http://www.bankofwow.com/cart.php?target=articles&mode=article&article_id=67
Looks like an early guide before some nerfs
