### ISSUE TITLE
[Blackwing Lair] Nefarian

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#510]
Priest call not working correctly (see below)

**Comment by cyanpill** [comment]
The priest's call "corrupt healing" is supposed to only work on direct heals https://classic.wowhead.com/spell=23401/corrupted-healing
but with shadow embrace's indirect heals I had this:
![corrupt](https://user-images.githubusercontent.com/42840505/71787383-fc4a5400-2fe4-11ea-9f40-d8bdbec6784b.png)

**Comment by Broxxi** [comment]
Got no screenshots for this, but if you are in Catform and the druid classcall hits, you cant see combopoints on the target. you can still use them but its kinda shit to play like that.

**Comment by Progressive335** [comment]
> Got no screenshots for this, but if you are in Catform and the druid classcall hits, you cant see combopoints on the target. you can still use them but its kinda shit to play like that.

well, not sure if that's actually intended.
