### ISSUE TITLE
[Spells][Druid] Primal Fury

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#513]
Proc is not working correctly for rank 2

**Comment by Broxxi** [comment]
Some additional info for this: It seems to be working correctly, when you respecc, but as soon as you relog or shift out of catform it is back to being bugged. Hope thats helpful in some way.

**Comment by Progressive335** [comment]
> Some additional info for this: It seems to be working correctly, when you respecc, but as soon as you relog or shift out of catform it is back to being bugged. Hope thats helpful in some way.

it is very. thanks.

**Comment by Progressive335** [comment]
> Some additional info for this: It seems to be working correctly, when you respecc, but as soon as you relog or shift out of catform it is back to being bugged. Hope thats helpful in some way.

i was able to find the issue based on your description! thanks a lot :)

**Comment by Progressive335** [comment]
it's combo points are getting triggered without having to crit, needs review
