### ISSUE TITLE
Rogue T1 5piece setbonus

### ISSUE THREAD

**Issue by Broxxi** [Progressive335/Progressive335#519]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**21975 from 204

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[X] Setbonus/Itemset

**Description of the bug:**The Setbonus is gone when you switch out of catform and back into it.
**Current behaviour:**

**Steps to reproduce the problem:**
Equip 5 Setpieces in catform, you have 110 Energy. if you now switch out and back in the setbonus is gone until you unequip and reequip it.
**How it should work:**
If possible it should be applied when entering catform without reequipping it.
**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
looks like a related issue similar to the primal fury talent bug.
