### ISSUE TITLE
Facing Negolash

### ISSUE THREAD

**Issue by Lampolo** [Progressive335/Progressive335#522]
Quest: Facing Negolash

Description: The boat that is to be interacted with after having the required materials (Barbecued Buzzard Wing x10, Junglevine wine x5)  for the quest is still not able to be interacted with after multiple attempts. Should be able to interact with the boat in Stranglethorn Vale South East coast after having the required materials and turn them in to summon Negolash for the remainder of the quest.

**Comment by Zooke** [comment]
https://github.com/Progressive335/Progressive335/issues/509

**Comment by Progressive335** [comment]
duplicate.
