### ISSUE TITLE
Postmaster Malown does not spawn.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#536]
https://classic.wowhead.com/npc=11143/postmaster-malown
Mob is supposed to spawn upon opening the 3rd postbox, He doesn't.

**Comment by Progressive335** [comment]
I think you meant Malown? XD

**Comment by awatenn** [comment]
Explaining what this is about:
You kill the Stratholme Courier, located @ Fras Siabi quest location.
https://wotlk.evowow.com/?npc=11082
(not sure if he should be spawned there when zoning in, if he has multiple spawnpoints he can choose from or if you need to do something for him to spawn)

The courier drops guaranteed 3 of the keys on his loot table. There are mailbox objects located everywhere in places with similar name to the keys inside Stratholme. Whenever you open a mailbox, three mobs (Undead Postman) will spawn near the mailbox and attack you immediately.
https://wotlk.evowow.com/?npc=11142

Also, when you open a mailbox, there will a parcel spawned inside the mailbox so you can loot it for vendor trash.
https://wotlk.evowow.com/?object=176360

Additionally, when you open the third mailbox in that instance: with the 3 mobs, Postmaster Malown spawns too.
https://wotlk.evowow.com/?npc=11143

Sources
https://classic.wowhead.com/npc=11143/postmaster-malown#comments
https://youtu.be/tCwpCbnSWE4?t=337 starting at 5:40

I have not tested this myself but you asked for an explanation so I hope it helps
