### ISSUE TITLE
Buru the Gorger

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#547]
Appears to target totems and pets.
From watching, I'm not sure this is working how we would want it, the boss seemed to be taking considerable damage from player attacks.
Also, from memory I think 2 eggs must be spawned at all times, pretty sure there was only 1 spawned at times during the fight.

**Comment by Progressive335** [comment]
there was 6 eggs.
yes i saw him targettng totems and pets.
is there anything about him taking reduced damage from player attacks?

**Comment by Zooke** [comment]
The idea of the fight is that the eggs are the thing that damage his shell to get him past 20% when the shell comes off and phase 2 begins, without this mechanic the eggs can be completely ignored.

**Comment by Progressive335** [comment]
there are enough eggs for the fight @Zooke you're mistaken or didn't see them.
