### ISSUE TITLE
Major Yeggeth

### ISSUE THREAD

**Issue by cts17** [Progressive335/Progressive335#556]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
Major Yeggeth in AQ20 has spell to make immune to magic.
**Current behaviour:**
Currnetly makes immune to everything
**Steps to reproduce the problem:**
2nd boss in AQ20
**How it should work:**
physical DPS should still work
**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
https://wotlk.evowow.com/?spell=25282
https://www.wowhead.com/spell=25282/shield-of-rajaxx
Effect #1 | Apply Aura: School Immunity (Physical, Holy, Fire, Nature, Frost, Shadow, Arcane)

Seems correct to me.
