### ISSUE TITLE
Princess Tempestria Doesn't Spawn

### ISSUE THREAD

**Issue by cts17** [Progressive335/Progressive335#562]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[14457] NPC
[] Quest

**Description of the bug:**
Princess Tempestria announces her arrival in Winterspring, but only her guards spawn in

**Current behaviour:**
She announces coming, but doesn't show up.

**Steps to reproduce the problem:**
Go to Lake Kel'Theril and wait for her to yell. Her adds will spawn, but she won't.

**How it should work:**
She should spawn.

**Any other documentation that could be helpful:**
https://wowwiki.fandom.com/wiki/Princess_Tempestria

**Comment by Zooke** [comment]
What happens here is that there is a game event announcing the Elemental bosses which happens about every 10m.
We spoke about this ages ago and until it was fixed, I changed the spawn timers of the bosses to be longer.

**Comment by Progressive335** [comment]
so it spawns or it doesn't?

**Comment by Progressive335** [comment]
tested and it spawns

what happened could have been:
- the event ending at the same time it was triggered by the player being close
- the boss has been killed by someone else?

either way, cannot reproduce. it's working.
