### ISSUE TITLE
2H Weapon Mastery not working for Warriors

### ISSUE THREAD

**Issue by Estokek** [Progressive335/Progressive335#569]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

12712

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[X] Talent

**Description of the bug:**
Talent is not adding any damage % amplifiers
**Current behaviour:**
bugged
**Steps to reproduce the problem:**
just talent into it and equip 2h wep
**How it should work:**
as it says in the talent
**Any other documentation that could be helpful:**

**Comment by VortexPrecision** [comment]
one hand/two hand talents of paladin/warrior/etc won't show in stats as %modifier, just plain additive bonus to white text for each point spent

**Comment by VortexPrecision** [comment]
![image](https://user-images.githubusercontent.com/71529592/133697619-26637329-55f5-4b19-92a7-c34e61fd704e.png)
