### ISSUE TITLE
Head of Balnazzar (Strat)

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#593]
https://classic.wowhead.com/item=13250/head-of-balnazzar#comments
This item is 100% once you have completed https://classic.wowhead.com/?quest=5251

It is not dropping.

This answers a question I had been pondering for a while, 'What is that box in Light's Hope Chapel for ?'
The head starts a quest chain that leads to opening it.

**Comment by Zooke** [comment]
The whole questline is already implemented and working, it just needs this item added to the loot table with the correct requirement.

**Comment by Progressive335** [comment]
This is working correctly, i tested, the head can only drop for you if you completed the quest "The Archivist", it's a requirement. Check:
https://classic.wowhead.com/quest=5262/the-truth-comes-crashing-down
