### ISSUE TITLE
Demon Scarred Cloak

### ISSUE THREAD

**Issue by mikedej** [Progressive335/Progressive335#597]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**  4854

__Place an X between the brackets to specify the ID__

[X] Quest 4854
[X] NPC 3056
[] Quest

**Description of the bug:**
The Demon Scarred Cloak is an item that gives a quest.
It's supposed to be dropping of an NPC called "Ghost Howl" (Located in Mulgore).

**Current behaviour:**
Not dropping.

**Steps to reproduce the problem:**
Killed it 3 times sofar with no drop.

**How it should work:**

**Any other documentation that could be helpful:**

**Comment by Zooke** [comment]
He doesn't appear to drop it.
https://classic.wowhead.com/npc=3056/ghost-howl
https://classic.wowhead.com/item=4854/demon-scarred-cloak

Thanks for the report.

**Comment by Progressive335** [comment]
it drops, but the rate is currently very low compared to wowhead data, fixing it...
