### ISSUE TITLE
Naxx missing npc Master Craftsman Omarion

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#604]
This npc was removed in Wrath.
https://classic.wowhead.com/npc=16365/master-craftsman-omarion#comments
https://wow.gamepedia.com/Master_Craftsman_Omarion
- [x] He was spawned in the cage that is directly in front of you as you enter the military wing.

- [x] He needs to be flagged so that mobs do not kill him as soon as he spawns

- [x] Upon talking to him, players could receive https://classic.wowhead.com/item=22719/omarions-handbook#comments
This book starts a quest which is a pre-requisite for the https://wow.gamepedia.com/Craftsman_Wilhelm raid quests (with the exception of 'The only 1 I know')
- [x] Currently these quests are available without having done the pre-quest.

- [x] He is also a trainer and can teach the recipes listed to players with the required reputation.

**Comment by Zooke** [comment]
https://youtu.be/KCb1zHhSTKY
Video from cmangos

**Comment by Progressive335** [comment]
Scripted but not exactly as the video, still it ends in the same result.
