### ISSUE TITLE
Naxx Instructor Razuvious

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#605]
Originally this fight required 2 priests to MC.
However, this was with 40 players available.

Putting this in the bug tracker to be considered as it is Blizzlike for vanilla Naxx.

**Comment by Progressive335** [comment]
The fight required 4 priests for MC because of the 4 adds in Vanilla, but since this is a 25man we have two adds on it.

**Comment by Zooke** [comment]
https://wowwiki.fandom.com/wiki/Instructor_Razuvious
This says that the wrath 25m Naxx had 4 understudies and MC had to be used.
