### ISSUE TITLE
Fragmented Magic (Mage quest)

### ISSUE THREAD

**Issue by mikedej** [Progressive335/Progressive335#606]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:** 3964

__Place an X between the brackets to specify the ID__

[X] Quest 3964
[] NPC
[] Quest

**Description of the bug:**
You have to sheep any of the Spitelash creatures in Azshara, after a few seconds it should split itself into a couple of "Polymorph Clones" of which you need to kill 50.

**Current behaviour:**
When I sheep a Spitelash creature, it just dissapears after a few seconds, not splitting into clones

**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**
Here's a video of someone doing the quest on classic
https://www.youtube.com/watch?v=XJFNI2Aljj8

**Comment by Zooke** [comment]
Seeing the video creators long list of classic videos got me all excited, until I noticed the dates on some of them.
However, this particular video does demonstrate what is supposed to happen so thanks for the report.

**Comment by mikedej** [comment]
Any progress on this? I know it's not priority.

**Comment by mikedej** [comment]
Asking again on progress? 

This quests gives me a cool polymorph spell, hence why :)
