### ISSUE TITLE
Naxx: Missing npc Archmage Tarsis Kir-Moldir

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#610]
https://wow.gamepedia.com/Archmage_Tarsis_Kir-Moldir
https://classic.wowhead.com/npc=16381/archmage-tarsis-kir-moldir

This npc does nothing critical, he is there to explain the lore behind Atiesh
He sits on the platform between the spider wing and the plague wing entrances.

**Comment by Zooke** [comment]
I have spawned him, you will have to do the dialog.
He needs to be sitting the whole time and to cry on the correct chat option.

**Comment by Progressive335** [comment]
https://wowwiki.fandom.com/wiki/Tarsis_Kir-Moldir info

**Comment by Progressive335** [comment]
https://youtu.be/QWBE-20lDNc
