### ISSUE TITLE
Maexxna - Outer Web Door

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#616]
Maexxna - Outer Web Door missing, should be at the top of the web you walk up to enter her lair
https://wotlk.evowow.com/?object=181209

**Comment by Zooke** [comment]
Seems fixed

**Comment by Progressive335** [comment]
sure but remember that "door" is triggered by a script to open/close during an enconter, it will be messy to deal with that, what i think is another gameobject could be used or something like that.

**Comment by Zooke** [comment]
in cmangos, the web is there to be clicked by players, this may not seem so obvious in this case but it follows the same logic as the Anub'rekhan door. That door is the 1st in the wing and is therefore obviously not open by default or by any script.
