### ISSUE TITLE
Master Crafstman Omarion

### ISSUE THREAD

**Issue by cts17** [Progressive335/Progressive335#631]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC Master Crafstman Omarion
[] Quest

**Description of the bug:**
https://wowwiki.fandom.com/wiki/Master_Craftsman_Omarion

he's supposed to be in the cage

**Current behaviour:**
He's not in the instance.

**Steps to reproduce the problem:**
Go to DK wing and clear first room. No NPC in the cage.

**How it should work:**
Should be an NPC here to teach us icebane patterns for Sapph

**Any other documentation that could be helpful:**

**Comment by Zooke** [comment]
Duplicate #604

**Comment by Progressive335** [comment]
https://github.com/Progressive335/Progressive335/issues/604
