### ISSUE TITLE
Cryptfiend Silk Clock

### ISSUE THREAD

**Issue by Thugawa** [Progressive335/Progressive335#641]
When i equipped the item;
Cryptfiend Silk Cloak
Item ID: 22938
The WoW crashed, i enter again and i was teleported to the inicial zone from DK lvl 55 and my second spec got reset.

At the moment of bug i was in group raid inside the naxx with 24 members.
I tried to reproduce the bug again but without success, switched my back a lot of times and it didnt happen again.

**Comment by Progressive335** [comment]
can't reproduce. my wow does not crash. seems a client bug rather than a server one.
