### ISSUE TITLE
Request for the skill [Call Stabled Pet]

### ISSUE THREAD

**Issue by KrasterK** [Progressive335/Progressive335#652]
This skill was introduced in wotlk to improve the quality of life of the hunters and not forcing them to go to a stable master, with dual talents this is more relevant now since i need to go to a stable master every time i switch from BM to MM or viceversa. 

Spell ID = 62757
[Call Stabled Pet]

It would be a really big improvement in terms of quality of life, playability, and it doesnt add to damage or anything of the sort, thank you in advance.

**Comment by Zooke** [comment]
I would agree that this change is in line with the Wrath dual talent ability and does not adversely affect gameplay.
