### ISSUE TITLE
Hunter T2 8pc bonus doesnt seem to be applying correctly

### ISSUE THREAD

**Issue by KrasterK** [Progressive335/Progressive335#655]
After trying my damage against a dummy for an hour or so in many sessions i've noticed that my damage doesnt go up as it should when the debuff is applied on the target, 

"You have a chance whenever you deal ranged damage to apply an Expose Weakness effect to the target. Expose Weakness increases the Ranged Attack Power of all attackers against that target by 450 for 7 sec."

Expose Weakness ID = 23578

450 AP is 35% of my AP unbuffed, and my dps goes down as it if wasnt applied. The proc rate seems to be working properly but the result is not. Thank you for your time

**Comment by Zooke** [comment]
I tried this on the training dummy and the damage increased.

**Comment by KrasterK** [comment]
ok thank you so much, if it works properly i must've missed something, thank you for your time
