### ISSUE TITLE
AQ40 Twin Emperors incorrect loot

### ISSUE THREAD

**Issue by vaxxvaxvax** [Progressive335/Progressive335#657]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
Twin Emperor custom Loot chest (I do not know the ID)

**Description of the bug:**
Twin Emperors are supposed to drop two offset items unique to their respective loot tables.
**Current behaviour:**
In the chest, there is only one offset item, not two.
**Steps to reproduce the problem:**
Defeat the Twin Emperors and loot the chest.
**How it should work:**
There should be two offset item groups (next to the two T2.5 token and the other loot
Item Group 1 (Vek'lor):
21598 (royal qiraji belt)
21602 (qiraji execution bracers)
21601 (ring of emperor veklor)
21599 (veklors gloves of devastation)
21600 (boots of epiphany)
21597 (royal scepter of veklor)
Item Group 2 (Vek'nilash):
21608 (amulet of veknilash)
21604 (bracelets of royal redemption)
21606 (belt of the fallen emperor)
21605 (gloves of the hidden temple)
21607 (grasp of the fallen emperor)
21609 (regenerating belt of veknilash)
21679 (kalimdors revenge)
**Any other documentation that could be helpful:**
https://www.youtube.com/watch?v=RrXUFgPSE6k retail proof (disregard blue coffer key, that was a post-cata item change)

otherwise just increase the items that drop of existing itemgrp to 2 if you dont want to type it all out

**Comment by Progressive335** [comment]
the video is not in vanilla. also:
https://classic.wowhead.com/npc=15276/emperor-veklor
https://classic.wowhead.com/npc=15275/emperor-veknilash

https://classicdb.ch/?npc=15276
https://classicdb.ch/?npc=15275

do not match your description, if you see, there are chances for the loot, and even if they were grouped loot there only two distinct groups. which means that it drops at least 2 items OR more.

**Comment by vaxxvaxvax** [comment]
https://www.youtube.com/watch?v=PVuPmDuGXpI here video from vanilla lol

Each Emperor drops their T2.5 token, one offset item, one white reputation idol, and a chance to drop regalia/enchant pattern

In the chest, it should be guaranteed that both the T2.5 token and two offset items are inside. Currently only one offset item is contained. I never said anything about regalia/enchant patterns or crowns, those are correct

just because the kill video in the first yt link is from beyond vanilla, doesnt mean the loot magically changes. the loot still will be the same lol (exception is that blue key item in first video, that was due to keyring changes in cata+ and has nothing to do with this server)

**Comment by vaxxvaxvax** [comment]
also pls dont rely on wowhead % data, that is datamining/-gathering and has nothing to do with actual correct precise drop rates of boss loot

**Comment by Zooke** [comment]
https://wowwiki.fandom.com/wiki/Twin_Emperors
My understanding of this is that each emperor drops an insignia, a set token and an item of loot from their personal loot table as listed (or 2 items if thats the AQ boss protocol you are using)
Basically this fight is a 2 boss fight and awards 2 seperate boss loots.

**Comment by Progressive335** [comment]
so is rather two insignias against two offset pieces. thing is, videos shown on loot sample, that is not enough to prove that the loot **will always be the same**.

**Comment by vaxxvaxvax** [comment]
The boss loot should be as follows:

GUARANTEED
Veklinash Circlet
Veklor Diadem
2x Qiraji rep idol
offset item 1 (example: royal qiraji belt)
offset item 2 (example: amulet of veklinash)
CHANCE TO DROP:
like 5%: either one of the regalia item (the one that gives weapon as questreward)
up to you: enchanting pattern

T2.5 token is obvious

https://wowwiki.fandom.com/wiki/Twin_Emperors
"You get two Qiraji Lord's Insignias from this boss encounter, one from each boss."
ok that looks like proof to me

http://ropetown.com/ropedkp/listitems.php?s=fd5e759e0668d830e0d22bef0dc66d25&p=history
here loot history from a 2006 guild that cleared aq40/naxx regularly. just ctrl+f "emp"

is that enough proof? i challenge you to go out of your way to find proof that says that more or less than 2 offset items drop. you will NOT find it. it wouldnt even make any sense

pls fix offset loot.. i dont want to dig through archive.org just to "prove you wrong". i just want this mistake to be fixed alrdy xd

**Comment by Progressive335** [comment]
> The boss loot should be as follows:
> 
> GUARANTEED
> Veklinash Circlet
> Veklor Diadem
> 2x Qiraji rep idol
> offset item 1 (example: royal qiraji belt)
> offset item 2 (example: amulet of veklinash)
> CHANCE TO DROP:
> like 5%: either one of the regalia item (the one that gives weapon as questreward)
> up to you: enchanting pattern
> 
> T2.5 token is obvious
> 
> https://wowwiki.fandom.com/wiki/Twin_Emperors
> "You get two Qiraji Lord's Insignias from this boss encounter, one from each boss."
> ok that looks like proof to me
> 
> http://ropetown.com/ropedkp/listitems.php?s=fd5e759e0668d830e0d22bef0dc66d25&p=history
> here loot history from a 2006 guild that cleared aq40/naxx regularly. just ctrl+f "emp"
> 
> is that enough proof? i challenge you to go out of your way to find proof that says that more or less than 2 offset items drop. you will NOT find it. it wouldnt even make any sense
> 
> pls fix offset loot.. i dont want to dig through archive.org just to "prove you wrong". i just want this mistake to be fixed alrdy xd

fine but this response is how a report like this should be filled. there are many claims of many stuff all the time here, you have to understand that.

**Comment by Zooke** [comment]
Vax, this kind of attitude is not appreciated.
We put in many hours of work to make the server you play on.
Not all issues can be our top priority and "be fixed alrdy".

**Comment by Gubbyfishy** [comment]
> _basically it has to drop at least 1 item from group 1 and 1 item from group 2.

This is nonsense in this scenario. If this were the case, you would have Imperial Qiraji Armaments and Imperial Qiraji Regalia dropping in all kills, which frankly is not the case. The drop pool in group 2 on classic DB only takes up 6%, and group 1 is equally chanced (100 divided by 7 equals 14, rounded down).

The ideal scenario since you questionably ended up moving everything into a gameobject rather than keeping loot on the creatures themselves is that you simply continue using the references originally given on the creatures and set the MaxCount to one on each group. You don't need to do it for the tokens since there is no requirement for an entry to be grouped.
