### ISSUE TITLE
Priest Shadowform spell

### ISSUE THREAD

**Issue by Leithmorien** [Progressive335/Progressive335#664]
**Description of the bug:**

Priest Shadowform spell simply becomes unusable after turning it off. 
It does that randomly and only solution is to completely close the game and relaunch it.

It's happening always in the last days, without a specific timing.

**Comment by Progressive335** [comment]
known bug, happens with the death knights summon ghoul spell . it's not a constant bug but it's anyoing.

**Comment by Leithmorien** [comment]
Not constant... mmm I rather have some doubts about it, happening a lot of times... 
Not 100% sure bout it but seems happening after using a gryphon taxi
