### ISSUE TITLE
Thunderfury, Blessed Blade of the Windseeker

### ISSUE THREAD

**Issue by misteryodt** [Progressive335/Progressive335#675]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 It does the nerfed damage that it was implented after vanilla,aka 213 dmg not 300.
**ID of the Spell/NPC/Quest:**
/item=19019
__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
 It does the nerfed damage that it was implented after vanilla,aka 213 dmg not 300.
**Current behaviour:**
At this moment it does 213 damage on proc
**Steps to reproduce the problem:**
Equip TF and let it proc 
**How it should work:**
Should damage for 300 nature damage,not 213. Doing 213 damage is in tbc when it gets nerfed.But even in TBC only the threat was nerfed i think,not the damage.
**Any other documentation that could be helpful:**
https://imgur.com/EW2bKw2

**Comment by Zooke** [comment]
Items are in their wrath conditions. This is a wrath client capped at 60.
It was never our intention to have a general vanilla database.
Raids have been modified to emulate their vanilla states but changing items is simply not within the current scope of the project.
As you are no doubt aware, many things were altered between vanilla and 3.3.5. Some are of great benefit, others come as nerfs.
