### ISSUE TITLE
[Spells] increases damage against undead

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#710]
Items that have the description "increase damage against undead" don't seem to work.

example:
Mark of the Champion
Blessed Wizard Oil

**Comment by KrasterK** [comment]
Same for the Mark of the Dawn trinket and the consecrated sharpening stones.

**Comment by Zooke** [comment]
Do any of these type of auras work ? i.e. increased damage against beasts / elementals / demons etc.

**Comment by Progressive335** [comment]
i don't know @Zooke , needs testing.
