### ISSUE TITLE
[Warlock/Pet] Mobs Evade when Aggro changes between Imp (pet) and Player

### ISSUE THREAD

**Issue by Miranai** [Progressive335/Progressive335#722]
**Description of the bug:**
When the Aggro changes from Player to Imp to Player and then to Imp again, sometimes the Mobs are in an Evade Status and they can be damaged.  They are following the Imp.

**Steps to reproduce the problem:**
Frequent aggrochanges between player and pet seems to be the issue (back and forth).

**Any other documentation that could be helpful:**
Video: https://imgur.com/a/4kwJavK

**Comment by Zooke** [comment]
I have to say that in my somewhat brief time playing a warlock, I have never seen this happen.
The video starts with the mobs already evading and does not show the cause.
This may however be related to an issue I have seen with raid bosses with an imp pet.
If you could manage to reliably reproduce the issue it would be most helpful.

**Comment by Progressive335** [comment]
> I have to say that in my somewhat brief time playing a warlock, I have never seen this happen.
> The video starts with the mobs already evading and does not show the cause.
> This may however be related to an issue I have seen with raid bosses with an imp pet.
> If you could manage to reliably reproduce the issue it would be most helpful.

already fixed that issue.

**Comment by VortexPrecision** [comment]
fixed
