### ISSUE TITLE
Beacon of Light doing 50% of what's intended

### ISSUE THREAD

**Issue by KrasterK** [Progressive335/Progressive335#733]
The spell ``Beacon of Light´´ from holy paladins is being affected by the healing nerf inside naxx twice apparently, since it only heals the target of the beacon for 50% of what the healing amount on the other target was, when it's supposed to be 100%

ID spell= 53563
https://wotlk-twinhead.twinstar.cz/?spell=53563

**Comment by Progressive335** [comment]
there are many other classes with similar effects cut off twice or triple or even more. by allowing the beacon to be ignored is giving advantage to holy paladins i think.

**Comment by Progressive335** [comment]
fixed recently
