### ISSUE TITLE
Mind Controlled npc's cannot seem to target the player controlling them.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#736]
I cannot target myself when MC'ing a mob.

You would typically do this when the mob has a beneficial spell to cast on allies, heals, buffs etc.

**Comment by VortexPrecision** [comment]
tested in game and cannot be reproduced

![image](https://user-images.githubusercontent.com/71529592/134014691-322fb8e2-a570-4443-8a9e-6c44b3a728a1.png)
