### ISSUE TITLE
[Shaman] T3 Hunter 4 set Bonus doesn't work

### ISSUE THREAD

**Issue by Miranai** [Progressive335/Progressive335#737]
**Description of the bug:**
T3 Hunter 4 set Bonus doesn't work on Shamans with Feral Spirit, even tho they are considered pets.
**Current behaviour:**
Doesn't give the 50 Attackpower Bonus

**Any other documentation that could be helpful:**
Video: https://imgur.com/a/4kewLQA

**Comment by Progressive335** [comment]
not sure if i can consider this a bug since the set is originally intended for hunters.

**Comment by Miranai** [comment]
Chat with Silver: https://imgur.com/a/nc922qK

**Comment by Progressive335** [comment]
> Chat with Silver: https://imgur.com/a/nc922qK

yeah, it was me, i said "should be", what i mean is that in theory it could work, but if it doesn't it also doesn't mean that is a bug. I don't know if the bonus is actually balanced to be used with shaman wolves, needs proper investigation and testing.

But i can confirm this bonus is also bugged for hunters.
