### ISSUE TITLE
Mage  questline unavailable

### ISSUE THREAD

**Issue by mikedej** [Progressive335/Progressive335#748]
A chain that starts with the quest:  Fetch! (9402)

It's pure for a horde mage to pick it up. (But I'm unable to as an undead mage)

This quest leads to: The Purest Water (9403)
This quest leads to: Recently Living (9404)

Side node: These are TBC quests, but we're on patch 3.3.5 so they should be available.

**Comment by Progressive335** [comment]
the quest works, the thing with these kind of quests is that you can only pick one from a possible group of quests, for example, if you pick the one from the starting zones of the undeads then you're not able to pick "Fetch".

![image](https://user-images.githubusercontent.com/44980177/81030765-e5781900-8e81-11ea-89c8-52c5e3a7f3e6.png)
