### ISSUE TITLE
Death Knight, Spell, Raise Dead

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#753]
**ID of the Spell:** [46584](https://wotlk.evowow.com/?spell=46584) (this is not the npc id)

**Description of the bug:** [[Raise Dead]](https://wotlk.evowow.com/?spell=46584) requires you to relog to cast the spell

**Current behaviour:** sometimes gets disabled & requires you to relog to cast the spell

**Steps to reproduce the problem:** Cast [[Raise Dead]](https://wotlk.evowow.com/?spell=46584) while a corpse is too far away

**Suggestion:** maybe put a range check on the spell or remove corpse requirement

**Comment by Progressive335** [comment]
duplicate
https://github.com/Progressive335/Progressive335/issues/714
