### ISSUE TITLE
Small Thorium Vein Mineable early

### ISSUE THREAD

**Issue by cts17** [Progressive335/Progressive335#756]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

Unknown.

**Description of the bug:**
Small Thorium Veins can be mined before 235

**Current behaviour:**
Uncertain at when they become available, but I discovered while leveling a mining alt that I could mine Small Thorium veins somewhere in the 220 mining level.

**Steps to reproduce the problem:**
1. Having Mining skill ~225-234
2. Attempt to mine Small Thorium Vein
3. Succeed, despite it requiring 235 skill

**How it should work:**
1. Be unable to mine Small Thorium Veins before 235

**Any other documentation that could be helpful:**

**Comment by Zooke** [comment]
I see various numbers for this, my guess is that it was changed in later expansions to make it easier to level up, much the same as was done with other professions where items were given greater skill point ranges, had materials changed or completely new items were added.
Wowhead classic currently has this listed at 245 https://classic.wowhead.com/object=324/small-thorium-vein

**Comment by cts17** [comment]
Agreed, but given as we're on a 3.3.5 client, it should probably follow 3.3.5 expectations. And if Silver wanted to modify it to be in line with vanilla, it should be the opposite of what I experienced ;)

**Comment by VortexPrecision** [comment]
not a bug. intentional for wotlk
