### ISSUE TITLE
Halaa PVP zone bugged with duplicate spawns

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#763]
The guards around Halaa are stacking spawns, I counted 15 spawns on a single spawnpoint. This was in a group of 3 so thats 45 mobs in 1 pull.
Correction, every mob there is stacking, even the vendors.
What's happening is that every so often we get 'The horde has taken control of Halaa' emote, when it's already under their control. This is no doubt spawning the duplicates.

**Comment by Progressive335** [comment]
fixed recently
