### ISSUE TITLE
Primal Nether

### ISSUE THREAD

**Issue by cts17** [Progressive335/Progressive335#766]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[23572] Item
[] NPC
[] Quest

**Description of the bug:**
Heroic dungeons should have 100% drop rate of 1 Primal Nether on final boss

**Current behaviour:**
Final bosses are not dropping Primal Nethers.

**Steps to reproduce the problem:**
Kill boss on heroic mode, check loot.

**How it should work:**
Kill final boss on heroic mode, get Primal Nether

**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
source?

**Comment by cts17** [comment]
https://www.wowhead.com/item=23572/primal-nether#comments
