### ISSUE TITLE
The Stones of Vekh'nir - Cannot complete

### ISSUE THREAD

**Issue by Anthaney** [Progressive335/Progressive335#769]
[X] Quest - The Stones of Vekh'nir ID:10565
[X] Quest Item - Charged Vekh'nir Crystal ID:30567

**Description of the bug:**
During the quest, I killed the mob and it dropped the quest item. I used the quest item on the circle where it gives me the crystal. I obtained the crystal but, I can't turn in the quest.

**Current behaviour:**
Cannot turn in to start quest chain.

**Steps to reproduce the problem:**
Kill any of the Vekh'nir Owls in Blades Edge Mountain.
Obtain a Vekh'nir Crystal from the mob.
Go to the purple circle in the middle of Vekh'nir.
Charge the crystal.
Can't turn in the quest because its still silver.

**How it should work:**
Once you received the Charged Vekh'nir Crystal, you should be able to turn in the quest and obtain your reward.
**Any other documentation that could be helpful:**
https://i.imgur.com/eJfBnWA.jpg

**Comment by Jparoche** [comment]
This quest is do-able. However if you drop the quest and re-take you can hand in the quest. Common issue on private servers.
