### ISSUE TITLE
[Quest}  Declawing Doomclaw Quest # 10235

### ISSUE THREAD

**Issue by liquidsnakeblue** [Progressive335/Progressive335#773]
When you obtain the quest item and return to the NPC to turn in the quest, you cannot turn it in.  The quest log shows 1/1 complete and I confirmed the needed item is in my bags.

**Comment by Jparoche** [comment]
This is a common issue on Private servers, Drop the quest and re-take, The quest item won't be removed if it wasn't provided by the quest itself.
