### ISSUE TITLE
The Cipher of Damnation

### ISSUE THREAD

**Issue by RdyyG** [Progressive335/Progressive335#789]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:(The cipher of Damnation)

__Place an X between the brackets to specify the ID__

[x] Quest 
[] NPC
[] Quest

**Description of the bug:** After you summon the mob that we need to kill, he is untargetable.

**Current behaviour:** Mob is untargetable

**Steps to reproduce the problem:** do the quest

**How it should work:** Kill the Mob that players summon

**Any other documentation that could be helpful:** https://www.wowhead.com/quest=10588/the-cipher-of-damnation

**Comment by Jparoche** [comment]
For this quest to work you need to start the event by speaking to the NPC, 
The Required kill mob is summoned by the player, However will be un-attackable until the event is started, By speaking to Earthmender Torlok

**Comment by Progressive335** [comment]
> For this quest to work you need to start the event by speaking to the NPC,
> The Required kill mob is summoned by the player, However will be un-attackable until the event is started, By speaking to Earthmender Torlok

as reported, quest works, you just need to talk to the npc that is the back.
