### ISSUE TITLE
Deathblow to the Legion

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#802]
https://www.wowhead.com/quest=10409/deathblow-to-the-legion#comments
https://www.youtube.com/watch?v=67iFZ7I0Nno
https://wow.gamepedia.com/Deathblow_to_the_Legion

This quest is not scripted, and is not completable.

**Comment by Progressive335** [comment]
dupe
https://github.com/Progressive335/Progressive335/issues/800
