### ISSUE TITLE
Nazan

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#805]
**ID of the NPC:** [17536](https://wotlk.evowow.com/?npc=17536)

__Place an X between the brackets to specify the ID__

[x] NPC

**Description of the bug:** [Nazan ](https://wotlk.evowow.com/?npc=17536)refuses to land permanently

**Current behaviour:** [Nazan ](https://wotlk.evowow.com/?npc=17536)fly up and down

**Steps to reproduce the problem:** engage combat with [Vazruden ](wotlk.evowow.com/?npc=17537)

**How it should work:** land when [Vazruden ](wotlk.evowow.com/?npc=17537)dies

**Comment by Progressive335** [comment]
that happens mostly because you taunt him down.

**Comment by Jparoche** [comment]
Issue is now Nazan will continue his flight plan until the set time is done. However he should fly down when Vazruden is at 25% or lower.
