### ISSUE TITLE
Death Knight, Healing Reduced

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#812]
**ID of the Spell/:** 
[48266 Blood Presence](https://wotlk.evowow.com/?spell=48266)
[45463 Death Strike](https://wotlk.evowow.com/?spell=45463)
[62908 Death Strike Talent](https://wotlk.evowow.com/?spell=62908)
[53365 Unholy Strength](https://wotlk.evowow.com/?spell=53365)

**Description of the bug:** healing done by death knight reduced

**Current behaviour:** 
[Blood Presence](https://wotlk.evowow.com/?spell=48266) heals for 1.94%
[Death Strike](https://wotlk.evowow.com/?spell=45463) with talent [62908](https://wotlk.evowow.com/?spell=62908) heals for 7.32% (with [Frost Fever](https://wotlk.evowow.com/?spell=59921) & [Ebon Plague](https://wotlk.evowow.com/?spell=59879) on target)
[Unholy Strength](https://wotlk.evowow.com/?spell=53365) heals for 1.46%

**How it should work:** 
[Blood Presence](https://wotlk.evowow.com/?spell=48266) should heal for 4% of damage dealt
[Death Strike](https://wotlk.evowow.com/?spell=45463) with talent [62908](https://wotlk.evowow.com/?spell=62908) should heal for 15% of maximum health (with [Frost Fever](https://wotlk.evowow.com/?spell=59921) & [Ebon Plague](https://wotlk.evowow.com/?spell=59879) on target)
[Unholy Strength](https://wotlk.evowow.com/?spell=53365) should heal of 3% of maximum health

**Comment by Progressive335** [comment]
intended
