### ISSUE TITLE
Death Knight, Rune Strike

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#813]
**ID of the Spell:** [56815](https://wotlk.evowow.com/?spell=56815)

**Description of the bug:** [rune strike](https://wotlk.evowow.com/?spell=56815) does incorrect damage

**Current behaviour:** [rune strike](https://wotlk.evowow.com/?spell=56815) does around 100% weapon damage

**How it should work:** [rune strike](https://wotlk.evowow.com/?spell=56815) should do 150% weapon damage [source](https://wotlk.evowow.com/?spell=56815)

**Comment by Progressive335** [comment]
intended, related to damage reduction
