### ISSUE TITLE
Eclipsion Soldier

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#814]
**ID of the NPC:** [22016](https://wotlk.evowow.com/?npc=22016)

__Place an X between the brackets to specify the ID__
[x] NPC

**Description of the bug:** [Eclipsion Soldier](https://wotlk.evowow.com/?npc=22016) has too much armor

**Current behaviour:** [Eclipsion Soldier](https://wotlk.evowow.com/?npc=22016) has effectively -75% physical damage taken (31k armor)

**Steps to reproduce the problem:** do physical damage vs [Eclipsion Soldier](https://wotlk.evowow.com/?npc=22016)

**How it should work:** [Eclipsion Soldier](https://wotlk.evowow.com/?npc=22016) should have around -33% physcial damage taken (5k armor) [source](https://wotlk.evowow.com/?npc=22016)

**Comment by wiceJ** [comment]
Not an issue. Armor is actually slightly lower than what is detailed in https://wotlk.evowow.com/?npc=22016
