### ISSUE TITLE
Unholy Blight

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#817]
**ID of the Spell:** 50536

**Description of the bug:** deals incorrect damage

**Current behaviour:** deals 1 damage

**Steps to reproduce the problem:** use death coil with talent Unholy Blight

**How it should work:** 
my average death coil damage is 350
350 x 0.1 / 10 = 3.5 damage

**Comment by Progressive335** [comment]
intended, related to damage reduction
