### ISSUE TITLE
Death Knight, Talent, Necrosis

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#821]
**ID of the Spell:** 
51465

**Description of the bug:** 
deals incorrect damage

**Current behaviour:** 
auto attack hit 820
Necrosis damage 79
79 / 820 = 9.6% weapon damage

**Steps to reproduce the problem:** 
auto attack with talent 51465 learned

**How it should work:** 
820 x 0.2 = 164

**Comment by Progressive335** [comment]
intended, related to damage reduction
