### ISSUE TITLE
Conditional/Trigger Effects double dips into % reduction

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#824]
**Description of the bug:**
Examples:
Necrosis talent by death knight
Beacon of Light talent by paladin
Titan's Grip talent by warrior
Chain Heal ability by shaman
Physical damage dealt to NPC with armor

**Current behaviour:**
Example:
Titan's Grip reduces physical damage by 10%
Average armor on lvl 70 npc appears to be 33% less physical damage taken
Physical damage appears to be 50% less

100 damage 
-10%
-33%
-50%
= 30.15 damage

100
-30.15
= 69.85% fury warriors effective damage reduction 

If 50% is the intended reduction
69.85 / 50 = 39.7%
Fury warriors deals effectively 39.7% less damage than intended

**Any other documentation that could be helpful:**

Solutions:

Manually go to each spell:
Necrosis talent by death knight
Beacon of Light talent by paladin
Titan's Grip talent by warrior
Chain Heal ability by shaman
Physical damage dealt to NPC with armor

or,

Buff monster health/damage & player health to effectively achieve the same intention by reducing player power (this way u dont have to fine tune the unintended reductions on Conditional/Trigger Effects)

**Comment by Progressive335** [comment]
intended, related to damage reduction
