### ISSUE TITLE
Warlock Talent [Siphon Life]  healing received penalized twice for dmg/healing nerf

### ISSUE THREAD

**Issue by weldim** [Progressive335/Progressive335#832]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[X] Spell 63108
[] NPC
[] Quest

**Description of the bug:**

Siphon life is being double penalized from the 35% damage healing reduction.  Corruption does 35% less damage, and then the amount healed is further reduced by 35%

**Current behaviour:** 179 49
Corruption tick = 179
Expected heal = 179 * .4 = 71.6
Actual heal = 179  * .4 * .68 = 49            (i assume its actually * .65 and this is just due to rounding)

**Steps to reproduce the problem:**

cast corruption on a target with no buffs  while having the Siphon life talent

**How it should work:**
Since overall damage is nerfed, and the heal is based off of your damage the healing portion should not have the 35% nerf again.  the total healing should be

((unmodified corruption tick) * (.65)) * .4 =healing received by warlock 

Ex:  Warlocks corruption ticks for 200 before the damage reduction is reduced to 130:

200*.65 = 130

That 130 tick should then heal the warlock for 40% of that (52) and should not be reduced by 35% again to (34)

130 * .4 = 52

**Any other documentation that could be helpful:**

**Comment by Progressive335** [comment]
this is intended, many other classes suffer for the same situation and is related to the damage/healing reduction scripts.
