### ISSUE TITLE
[Quest] Cypher of Damnation

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#836]
You can't attack the mob you're supposed to kill.

**Comment by Zooke** [comment]
If you notice, 3 npc's spawn at the questgiver. talk to 1 of them and the script will start making him attackable.
The script could do with some improvements to make it Blizzlike.

**Comment by Progressive335** [comment]
duplicate
https://github.com/Progressive335/Progressive335/issues/789
