### ISSUE TITLE
[Alchemy] Discovery system

### ISSUE THREAD

**Issue by JakDeabel** [Progressive335/Progressive335#837]
The discovery system grants a very small chance to learn a new recipe when making other potions.

Example : https://wowwiki.fandom.com/wiki/Flask_of_Mighty_Restoration

Aparently that is not working, even if its a small chance.

**Comment by Progressive335** [comment]
Same happens with prospecting

**Comment by pwtaka** [comment]
I had two discoveries (both transmutation), no flask yet though.
