### ISSUE TITLE
[Gruul's Lair] Issues

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#846]
- [x] Lair Brute missing charge / threat reset

- [x] Gronn-Priest should be immune to all except interrupt/dispell

- [x] Olm should move melee.

- [x] Check if Maulgar can be killed while adds are up.

**Comment by wiceJ** [comment]
Check if Maulgar can be killed while adds are up. - He can be.

**Comment by Progressive335** [comment]
> Check if Maulgar can be killed while adds are up. - He can be.

okay
