### ISSUE TITLE
Rift Lord & Rift Keeper Immune

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#855]
**ID of the NPC:**
21140
21104

__Place an X between the brackets to specify the ID__
[x] NPC

**Description of the bug:**
Immune

**Current behaviour:**
Rift Lord & Rift Keeper Immune to interupt & disease

**Steps to reproduce the problem:**
enter the black morass on heroic

**Comment by wiceJ** [comment]
Hi Treskoo - Could you please proof that Lords/Keepers can be interrupted. I'll fix the diseases now.

**Comment by wiceJ** [comment]
Closing ticket. Lack of information
