### ISSUE TITLE
Quest Enraged Sirits of Water; Cannot be completed

### ISSUE THREAD

**Issue by ythugarada** [Progressive335/Progressive335#858]
So I was doing the quest below mentioned and the NPC, didn't allow me to complete the quest, I didn't take a screenshot and I'm trying again if I can indeed complete it
 
[Quest Enraged Sirits of Water]

[X] Quest
[] NPC
[] Quest

**Description of the bug:** Once I completed the mentioned quest the NPC doesn't allow me to complete it, and not because I don't have a specific Item, I simply can't complete the Quest at the NPC

**Current behaviour:** Unfixed

**Steps to reproduce the problem:** Do the quest and try to complete it

**How it should work:** When you got all the items, you should be able to get the quest from the NPC

**Comment by wiceJ** [comment]
I've completed the quest, Can you please retest and let me know if it's still not working.

**Comment by Progressive335** [comment]
it's working fine.
