### ISSUE TITLE
[item] Xiris Gift and Scryers bloodgem share CD

### ISSUE THREAD

**Issue by pwtaka** [Progressive335/Progressive335#860]
http://www.wowhead.com/item=29179/xiris-gift
http://www.wowhead.com/item=29132/scryers-bloodgem#.

can't be used after the 15 seconds of the effect of the first use, like almost all trinkets should.
What's happening now is that on the UI we can see that when we use any of the trinket, the other has a 15seconds CD but when it ends we can't use it until the first trinket used is up. That makes it useless, except from the passive buff.

**Comment by wiceJ** [comment]
This is correct, The two trinkets share internal cooldowns.

https://www.wowhead.com/item=29179/xiris-gift#shared-cooldown:100+3-2

**Comment by pwtaka** [comment]
As you can see in the list posted basically every on use trinket shares CD. But this is only for the 15sec downtime so you cant use the trinkets at the exact same time. They should still be usable right after another.
Otherwise having two on use trinkets would be useless.
