### ISSUE TITLE
skettis-windwalker bugged.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#863]
https://www.wowhead.com/npc=21649/skettis-windwalker
This is a caster with the known bugged effects. i.e casting once or twice then just standing there.

https://www.wowhead.com/npc=21911/skettis-soulcaller
This mob is also bugged in the same way.

**Comment by Progressive335** [comment]
i think this is a generic smartai issue. going to apply a fix to see if it helps globally.
