### ISSUE TITLE
Kristen Dipswitch not scripted.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#877]
https://www.wowhead.com/npc=18294/kristen-dipswitch#comments

This npc is supposed to spawn evey so often (90m reported) and ride down to the Nesingwary camp where she gets attacked by the stealthed rogue just as she is about to enter the camp.
If no players kill the rogue, he will kill Kristen (this should take around a minute)
If any players save Kristen by killing the rogue she offers https://www.wowhead.com/quest=9897/im-saved
She will despawn around 3m after being saved and the 90m timer can start again.
Should Gankly kill her, he will despawn too so that the event can replay over again without having multiple copies of him.

The way the quest works is to have the rogue spawned in her path to attack her, if she makes it to her final waypoint, she has obviously been saved and can offer the quest.

Currently she is spawned at her start point but does not move and wrongly offers the quest (as she has not been saved).
https://www.wowhead.com/npc=18297/gankly-rottenfist is also spawned at the camp.
The rogue should only spawn as Kristen approaches the camp.

**Comment by VortexPrecision** [comment]
related
https://github.com/TrinityCore/TrinityCore/issues/24983

**Comment by VortexPrecision** [comment]
fixed
