### ISSUE TITLE
Armor VS % Reduction Debuff

### ISSUE THREAD

**Issue by treskoo** [Progressive335/Progressive335#880]
**ID of the Spell:** 
% reduction debuff

**Current behaviour:**
Example using in-game stats May 24:
My Raise Dead auto attack before reductions:
341 + 376 / 2 = 358.5 average auto attack damage 

My Raise Dead auto attack after reductions:
101 + 123 / 2 = 112 average auto attack damage

112 / 358.5 = 0.3124128312412831

1 - 0.3124128312412831 = 0.6875871687587169% reduction

**Any other documentation that could be helpful:**
Average physical damage reduction from NPC Armor is -33%

Assuming 50% is the intended total reduction:
-0.37594 x 1.33 = -0.5000002%

The % reduction debuff should be -37.594% for physical damage

**Comment by Progressive335** [comment]
yeah there is damage reduction for players , specially DKs. nothing wrong here, the formulas are correct most of DK nerf is intended.
