### ISSUE TITLE
isla-starmane not setting correct faction on starting escort

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#881]
https://www.wowhead.com/quest=10052/escape-from-firewing-point

https://www.wowhead.com/npc=18760/isla-starmane

Mobs should be hostile to this npc once the quest is accepted and she starts her walk through the village for the escort quest.

**Comment by wiceJ** [comment]
npc_isla_starmane

**Comment by VortexPrecision** [comment]
Tested it, the mobs attack her. Cannot reproduce the issue.
