### ISSUE TITLE
Grand Warlock Netherkurse

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#892]
Grand Warlock Netherkurse death coil should be a debuff instead of a buff

**Comment by Zooke** [comment]
Olm the summonner in Gruuls Lair also uses a death coil with the same effect.

**Comment by wiceJ** [comment]
Spellid of death_coil - 30500
Spellid of Death_Coil, Mass death Coil - Has a cast and will fear the caster (tested on player account not a NPC). (from heroic) - 30741
