### ISSUE TITLE
Allegiance to the Aldor/Scryer Reputation bug

### ISSUE THREAD

**Issue by cts17** [Progressive335/Progressive335#900]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**
10522
__Place an X between the brackets to specify the ID__

[x] Quest
[] NPC
[] Quest

**Description of the bug:**
Does not give full reputation

**Current behaviour:**
Gives 2887 instead of the intended 3500 to place you at Friendly.

**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**
https://wowwiki.fandom.com/wiki/Quest%3AAllegiance_to_the_Scryers
https://wowwiki.fandom.com/wiki/Quest%3AAllegiance_to_the_Aldor

**Comment by Progressive335** [comment]
wrong quest id made me confused :)
