### ISSUE TITLE
[PvP] Call to arms

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#914]
Call to arms doesn't seem to be correctly triggered in TBC

**Comment by Progressive335** [comment]
reason to close: it seems to have happened once, not sure why. cannot reproduce it anymore.

**Comment by silverech0** [comment]
it's happening again, needs checking

**Comment by Broker-Precision** [comment]
Fixed via https://github.com/VortexPrecision/PrecisionWoW/issues/432
