### ISSUE TITLE
Priest Mind control regression.

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#916]
MC seems to have regressed to an earlier state.
Now it breaks reliable once you go outside the initial range of the spell https://wotlk.evowow.com/?spell=605
This is not how it works, the range is just for the initial cast, not the channelled spell which has a 100yard range.

**Comment by Progressive335** [comment]
https://github.com/Progressive335/Progressive335/issues/386
added to the initial issue.
