### ISSUE TITLE
Magtheridon's Lair

### ISSUE THREAD

**Issue by Zooke** [Progressive335/Progressive335#918]
https://www.wowhead.com/npc=18829/hellfire-warder

- [x] One pack of these patrols, but the patrol is not synced very well, the 3 soon lose each other and walk around alone.

- [x] Melee seems very low, taking ~2300 on a naked character instead of the 7.1k on cloth quoted on the wiki.

- [x] Shadow Burst https://wotlk.evowow.com/?spell=34436 should have a threat removing mechanic.

- [x] Does not currently cast Fear, probably this spell https://wotlk.evowow.com/?spell=31970 if you can give it a melee only range

**Comment by Zooke** [comment]
https://www.wowhead.com/npc=17256/hellfire-channeler

There are 2 of these spawned on top of each other at a couple of the cubes

**Comment by Progressive335** [comment]
> https://www.wowhead.com/npc=17256/hellfire-channeler
> 
> There are 2 of these spawned on top of each other at a couple of the cubes

can't reproduce this... never seen such thing.
