### ISSUE TITLE
[TBC] Loot

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#923]
Rework/Review TBC loot from raids

- [x] Karazhan (also add progressive changes to enchanting recipes (buffed in WOTLK) (also note that the mount from the first boss may also have been nerfed in terms of drop chance in WOTLK)

- [x] Gruuls Lair (Pre-nerf/Post-nerf)

- [x] Magtheridon's Lair (Pre-nerf/Post-nerf)

- [x] Serpentshrine Caverns

- [x] Tempest Keep (check if the Ashes of Al'ar drop rate is blizzlike for TBC, because i think it was changed in WOTLK)

- [x] Black Temple (check if Warglaives drop chance is blizzlike for TBC, because i think it was changed in WOTLK)

- [x] Zulaman

- [x] Sunwell

- [x] Raid Trash Loot

- [x] World drops

- [x] Recipes (Epic)

- [x] Recipes (Rare)

- [x] Recipes (Uncommon)

**Comment by Progressive335** [comment]
related
https://github.com/Progressive335/Progressive335/issues/952

**Comment by Progressive335** [comment]
also, loot in early patches was different.
for example: In gruuls lair it drops 3/4 tier pieces currently but in the first patches it dropped less (needs confirmation)

**Comment by Broker-Precision** [comment]
Fixed via other issue log
