### ISSUE TITLE
Uldaman Reagent Run - ID:17

### ISSUE THREAD

**Issue by Anthaney** [Progressive335/Progressive335#925]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[x] Quest - Uldaman Reagent Run ID:17

**Description of the bug:*
There is not enough spawns for a whole run.
**Current behaviour:**
Respawn times are about 7 minutes in between.
**Steps to reproduce the problem:**
Pick the mushrooms, all of them and then afk for new ones
**How it should work:**
Probably make them have a little bit faster respawn rate for the quest.
**Any other documentation that could be helpful:**

**Comment by wiceJ** [comment]
Increased the amount of mushrooms that can drop from one cluster, To be inline with what wowhead has.
https://classic.wowhead.com/object=126049/magenta-cap-clusters#contains
