### ISSUE TITLE
[Progression] Implement item data change on patch

### ISSUE THREAD

**Issue by silverech0** [Progressive335/Progressive335#930]
Like title says, implement item stat change on patch.

Why?
Examples:
Primal Nether stopped being bop on 2.3.0.

**Comment by Progressive335** [comment]
Another example, i made the rep pvp items be bought with honor but in this case they should have the rep removed for patch 6 then placed back at patch 7

**Comment by Progressive335** [comment]
related
https://github.com/Progressive335/Progressive335/issues/965
