### ISSUE TITLE
Blade Flurry Not Working Properly

### ISSUE THREAD

**Issue by Wowm** [Progressive335/Progressive335#934]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**Description of the bug:**
Rogue blade flurrry white hits  not cleaving
**Current behaviour:**
When you pop spell poisons/combo builders/finishers(spells. yellowhits) cleaves as they should be but white hits doesnt 
**Steps to reproduce the problem:**

**How it should work:**

**Any other documentation that could be helpful:**

**Comment by silverech0** [comment]
how come? i just tested and it cleaves white hits.

**Comment by Progressive335** [comment]
works on autos
![image](https://user-images.githubusercontent.com/44980177/85081404-ccbe8b00-b1c3-11ea-8427-deed3717c128.png)
