### ISSUE TITLE
TBC transmutes | Cloth craft cooldowns

### ISSUE THREAD

**Issue by wiceJ** [Progressive335/Progressive335#935]
**Description of the bug:**
Missing spell cooldown on the below spells(4 day correct)@
31373
26751
36686

also 20h cooldown on transmutes:
29688: //transmute: Primal Might
32765: //transmute: Earthstorm Diamond
32766: //transmute: Skyfire Diamond

**Comment by wiceJ** [comment]
Possibly have cooldown as 2 days from TBC release, Reduce to 12 hours when T6 is released. Remove cooldown in Patch 3.1

**Comment by Progressive335** [comment]
https://wowwiki.fandom.com/wiki/Spellcloth

http://prntscr.com/t078x3

**Comment by Progressive335** [comment]
these changes are saved in code but wont be applied for the current version
