### ISSUE TITLE
Midsummer: Feralas Alliance not working

### ISSUE THREAD

**Issue by Fudgehog97** [Progressive335/Progressive335#940]
No midsummer NPC's on Sardor Isle.

![image](https://user-images.githubusercontent.com/51416024/85206050-91d16a00-b31f-11ea-8f74-2c2ab3c50592.png)

**Comment by wiceJ** [comment]
Hi, Do you know the names of the NPCs that should be spawned? Or are they generic ones?
There is a camp set up back on the main island, Beside where the boat to Sardor Isle is: http://prntscr.com/t4ap25

**Comment by Fudgehog97** [comment]
I'm not sure if it's supposed to be two. Since it's already on the beach I see the issue as closed.

**Comment by Anthaney** [comment]
[] NPC - https://wotlk-twinhead.twinstar.cz/?npc=25899
[] Quest - https://wotlk-twinhead.twinstar.cz/?quest=11817
