### ISSUE TITLE
[DK] [Unholy]

### ISSUE THREAD

**Issue by Progressive335** [Progressive335/Progressive335#945]
https://ibb.co/Z15tVgP
https://ibb.co/KLqWKQ0
https://ibb.co/KKxCHrf
https://ibb.co/wzpZb5q

these prints describe some issues with this spec

**Comment by Sagitar-g** [comment]
Sorry to not post this on Github earlier. I don't believe the Unholy Blight or Scourge Strike values are hitting for the correct value.

**Comment by silverech0** [comment]
> Sorry to not post this on Github earlier. I don't believe the Unholy Blight or Scourge Strike values are hitting for the correct value.

accounting with damage reduction?
