### ISSUE TITLE
armor penetration issues and Bonereaver's Edge uptime problems

### ISSUE THREAD

**Issue by spaccacerque** [Progressive335/Progressive335#949]
**Please fill in the bellow fields to create a meticulous report so that we can fix the issue properly.**
 
**21153**

__Place an X between the brackets to specify the ID__

[] Quest
[] NPC
[] Quest

**buff  i think doesn't proc enough**

**procs less than 17% for hti and is impossible to keep at 3 stack even with flurry**

**Steps to reproduce the problem:**

**should be uptime for like 90% of the time, i also think that the 44% arp you get from the 3 stacks should boost dmg more... is actually a lot and on dummy i see no much difference in dps... can you pls check?**

**just watching footage from vanilla retail or classic wow. **

**Comment by spaccacerque** [comment]
All of the information of 1.12 vanilla BRE has the proc % at being around 15 - 17% chance on hit (I used 15% as a low end conservative number). Hence the Vanilla 1.10 patches use of the descriptor “substantially increased” in regards to the proc.

Basically, the consensus was that the proc was up around 90% of the time with the authentic 15-17% proc rate since the proc had a 10 second duration that refreshed with each subsequent proc. The only thing that fluctuated during uptime was how many stacks of the armor pen buff you had at a time.

**Comment by spaccacerque** [comment]
The item is outdated so you could even put to 20% proc on hit without impacting gameplay, the only question is now if arp is calculated well, cause as i've seen there is no substantial damage boost on 44% arp...

**Comment by silverech0** [comment]
don't take things in consideration like classic wow/vanilla specially for spell effects, in here we are using WOTLK formulas for those calculations. How vanilla works spell wise is not the same how it works in WOTLK.

**Comment by spaccacerque** [comment]
https://imgur.com/Q8lhbAX

here an example ^_^
