### ISSUE TITLE
Flame Warden of Kalimdor, Feralas Alliance

### ISSUE THREAD

**Issue by Anthaney** [Progressive335/Progressive335#951]
**ID of the Spell/NPC/Quest:**

__Place an X between the brackets to specify the ID__

[] NPC - https://wotlk-twinhead.twinstar.cz/?npc=25899
[] Quest - https://wotlk-twinhead.twinstar.cz/?quest=11817

**Description of the bug:**
why no mob i cant get achievement pepehands pepega
**Current behaviour:**
No mobs
**Steps to reproduce the problem:**
Fly there
Cry

**How it should work:**
Fly there
pepeclap
turn in
ez achievement
**Any other documentation that could be helpful:**
https://i.imgur.com/uyJ0S5k.jpg

**Comment by mikedej** [comment]
Same for the Horde Flame warden at Stranglethorn Vale.
