### ISSUE TITLE
Living Root of the Wildheart never procs

### ISSUE THREAD

**Issue by Fudgehog97** [Progressive335/Progressive335#972]
**These are the buffs that it should give:**

Spell proc in moonkin form is:
http://www.wowhead.com/?spell=37343

Bearform Proc:
http://www.wowhead.com/?spell=37340

Catform Proc:
http://www.wowhead.com/?spell=37341

Treeform Proc:
http://www.wowhead.com/?spell=37342

Casterform Proc:
http://www.wowhead.com/?spell=37344

Extremely high priority.

**Comment by wiceJ** [comment]
Moonkin:
http://prntscr.com/t90fth
Bear:
http://prntscr.com/t90e9z
Cat:
http://prntscr.com/t90crc
Tree:
http://prntscr.com/t90hxm
Caster:
http://prntscr.com/t90jf9

Unable to find accurate proc chance details, Please provide if possible.

**Comment by Fudgehog97** [comment]
I got this to work in moonkin form but not in tree form.

**Comment by Progressive335** [comment]
it works, is just low proc rate (3%)
https://wotlk.evowow.com/?spell=37336
