### ISSUE TITLE
(suggestion) Transmog restrictions are too severe.

### ISSUE THREAD

**Issue by 13b-t** [Progressive335/Progressive335#973]
As shown in https://www.wowhead.com/patchnotes=5.2.0 (Items section), the official transmog rules are much more lax than the server's custom transmog system. I believe the feature will see much more use if the rules described in the linked patch notes were to be applied.

**Comment by Progressive335** [comment]
this isn't an issue, this is a suggestion.

**Comment by 13b-t** [comment]
It's both.
