### ISSUE TITLE
Fingers of Frost/Frostbite

### ISSUE THREAD

**Issue by Talthos** [Progressive335/Progressive335#985]
**Wowhead/WotLK database link(s):**
[Fingers of Frost](https://db.rising-gods.de/?spell=44545)

[Frostbite](https://db.rising-gods.de/?spell=12497)

**Description:**
Fingers of Frost and Frostbite are not proccing together; they currently proc independently of one another.

**How it should work:**
When fully talented, these two procs should share the same roll; if one procs, the other should automatically proc with it.

**How to replicate issue:**
Use a mage with both these talents fully upgraded, and repeatedly use frost spells with chill effects that can trigger the effects. Notice how they proc separately, rather than simultaneously.

**Any other documentation that could be helpful:**
[2009 forum post from MMO Champion that touches on this exact quirk.](https://www.mmo-champion.com/threads/641024-FrostBite-Fingers-of-Frost-question)

[Another MMO Champion forum post, this time from 2010. Makes direct mention of the simultaneous proc.](https://www.mmo-champion.com/threads/744737-WoW-based-Math)

[2009 Wowhead forum post, makes direct mention of the simultaneous proc.](https://www.wowhead.com/forums&topic=129936)

[Another 2009 Wowhead forum post, also makes direct mention of the simultaneous proc.](https://www.wowhead.com/forums&topic=117786)

[Yet another 2009 Wowhead forum post. Makes direct mention of the simultaneous proc.](https://www.wowhead.com/forums&topic=92604)

**Comment by silvermcd123** [comment]
A forum post isn't enough evidence. I'm sorry

**Comment by Talthos** [comment]
[Have a video for extra evidence then](https://www.youtube.com/watch?v=rUBDHbONDq8)

**Comment by Progressive335** [comment]
> [Have a video for extra evidence then](https://www.youtube.com/watch?v=rUBDHbONDq8)
> 
> (Mute the music if desired)

i would prefer something more solid, i can't find any report about this situation on major emulators. so it's one of those _highly doubt_ cases without proper data.

**Comment by Talthos** [comment]
Updated the report with links to additional forum posts made on both MMO Champion and Wowhead, all dated from during the WotLK-era of retail.
