### ISSUE TITLE
Eva Sarkhoff

### ISSUE THREAD

**Issue by Talthos** [Progressive335/Progressive335#986]
**Wowhead/WotLK database link(s):**
[Eva Sarkhoff](https://classic.wowhead.com/npc=11216/eva-sarkhoff)

[Wowpedia page](https://wow.gamepedia.com/Eva_Sarkhoff)

**Description:**
Eva Sarkhoff and her 7th, 8th, 9th, and 10th dialogue parts are incorrectly ordered.

**How it should work:**
Refer to the Wowpedia link for the correct dialogue ordering, regarding the conversation you have with her.

**How to replicate issue:**
Right-click on Eva Sarkhoff, and advance through her dialogue. Note the incorrect ordering at the 7th, 8th, 9th, and 10th parts, as mentioned above.

Especially note how her "exposed us to pain that we did not know existed" comment is (incorrectly) seen at her last dialogue part.

**Comment by Broker-Precision** [comment]
No issue found
