### ISSUE TITLE
A Matter of Time (Quest)

### ISSUE THREAD

**Issue by Talthos** [Progressive335/Progressive335#987]
**Wowhead/WotLK database link(s):**
[The quest](https://classic.wowhead.com/quest=4971/a-matter-of-time)

[The item provided by the quest](https://classic.wowhead.com/item=12627/temporal-displacer)

**Description:**
Using the Temporal Displacer currently only spawns a single Temporal Parasite at a time.

**How it should work:**
Using the Temporal Displacer should spawn anywhere between 1-6 Temporal Parasites.

**How to replicate issue:**
Accept the quest, and use the Temporal Displacer on the glowing silos. Notice how only one Temporal Parasite ever gets spawned this way.

**Any other documentation that could be helpful:**
[Found a Youtube video with footage of this quest from the official Classic client](http://www.youtube.com/watch?v=AIltUHurAN8&t=0m42s)

**Comment by Progressive335** [comment]
duplicate
https://github.com/Progressive335/Progressive335/issues/162
